### ISSUE TITLE
Application for Membership: fullstacklive

### ISSUE THREAD

**Issue by geewiz** [livecoders/Home#10]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
Stream: https://twitch.tv/fullstacklive
Long-term archive: http://youtube.fullstacksensei.com

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Ruby, Rails, Chef, DevOps and SRE in general

**Why do you write code on stream?**
I'd love to share what I've learned in more than 3 decades of coding and systems work. It's also good for people to see that even after all this time, I'm still failing and learning. (Also, the chat is helpful for rubberducking. xD)

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Every time a follower returns for a new session and says Hello is a favourite moment!

**Comment by geewiz** [comment]
Now that I've recovered from a travel bug, I'm doing live coding again. https://www.twitch.tv/fullstacklive/videos

**Comment by geewiz** [comment]
Now that I've recovered from a travel bug, I've been live coding again. I'll do another session later at 3:30pm BST/IST.

**Comment by geewiz** [comment]
@csharpfritz If there's anything you need from me to approve my application, please let me know.

**Comment by csharpfritz** [comment]
Approved!  I will DM you a link to the team Discord.

Thank you for applying!
