### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by Jindatesha** [livecoders/Home#100]
**What is the URL for your Twitch channel?**
https://www.twitch.tv/jindatesha

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Game maker language which is specific for Game Maker Studio (an engine to make games)

**Why do you write code on stream?**
talk to new people, helps to deter distractions and motivates me to continue coding 

**What is your favorite moment from coding on stream?  Share a clip if one is available**
well one time some newcomer said I sit like a gargoyle and I thought it was funny/accurate XD.

https://www.twitch.tv/jindatesha/clip/YummyZealousSoymilkTBCheesePull?filter=clips&range=all&sort=time

**Comment by csharpfritz** [comment]
Stream has a lot of potential.  I'd like to invite you to the team and some of our team members can help with your stream setup.

Welcome to the Live Coders!  You'll receive an email with an invite from Twitch.  Once you join the team, I'll Twitch whisper you a link to join the team Discord
