### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by DarkNight-Studio** [livecoders/Home#101]
**What is the URL for your Twitch channel?**
https://twitch.tv/darknightstudio

What languages / frameworks / tools do you program in while streaming on Twitch?
GML (Game Maker Language) that is for Game Maker Studio 1&2
Live Learning (Unreal Engine Blueprint)

**Why do you write code on stream?**
I enjoy meeting new people along with trying to teach people the right way of doing things and not the incorrect ways I like to do. Also, it helps me deal with my depression and social anxiety. 

What is your favorite moment from coding on stream? Share a clip if one is available
A code messes up where all the locks and keys turned in to still image of the alien. I sadly didn’t manage to clip but it's one of my new game maker streams.

**Why I am not Twitch Affiliate**
I was originally Affiliate on Twitch for 24 months I think before I chose to leave the program. This was done by me so I could sign a deal with one of my sponsor who was working with promoting another platform and offered monthly pay to make up for what I would lose not be a twitch affiliate any more as under twitch agreement restreaming is not allowed.

(i am autistic so my spelling is not best along with English write is my second language)

**Comment by csharpfritz** [comment]
Live Coders are Twitch affiliates or partners.  

Declined.  You can re-apply once you have reached Affiliate status
