### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by nnja** [livecoders/Home#102]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/nnjaio

**What languages / frameworks / tools do you program in while streaming on Twitch?**
I mostly stream programming in Python and CircuitPython for hardware devices, along with occasional hardware builds like soldering and assembling a mechanical keyboard.

**Why do you write code on stream?**
I've been an author of recorded screencast courses on FrontEnd Masters for several years, as well as a speaker at conferences and Meetups. Streaming has been a way to interact with a new community of people who are interested in the projects I'm working on, while also having an opportunity to chat, make friends, and ask questions. It takes the mystery out of programming and shows viewers that everyone makes mistakes in the learning process. 

I'm still learning the tools and the etiquette, but so far I've been really impressed with the small but wholesome community that's joined me on my streams. They've been inspiring me to stay motivated and focused.

**What is your favorite moment from coding on stream?  Share a clip if one is available**

A user shared an adorable banana themed terminal theme created by his daughter. [Clip](https://www.twitch.tv/videos/539876625)

**Comment by csharpfritz** [comment]
This is a GREAT stream and exactly what we look for in a Live Coder teammate.

Welcome to the Live Coders!  You'll receive an email with an invite from Twitch.  Once you join the team, I'll Twitch whisper you a link to join the team Discord
