### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by jamesqquick** [livecoders/Home#103]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://www.twitch.tv/jamesqquick

**What languages / frameworks / tools do you program in while streaming on Twitch?**
JavaScript, React, Gatsby, JAMstack, Node, HTML, CSS

**Why do you write code on stream?**
Streaming is a great way to get real-time interaction with developers across the world. I hope others learn as I write code and expect myself to learn from others as they review my code. 

**What is your favorite moment from coding on stream?  Share a clip if one is available**
In my most recent stream, I had the most engagement in the chat room of any of my streams. We talked about hacking the demo project I was working on. Attendees were able to hack the site, talk through how, and then together, we updated the site to prevent those kinds of hacks. This was a lot of fun.

https://www.twitch.tv/videos/554514863

If you have any questions about this process, please contact [_KittyKerns on Twitter](https://twitter.com/_kittykerns)

**Comment by csharpfritz** [comment]
Welcome to the Live Coders!
