### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by spherous** [livecoders/Home#104]
**What is the URL for your Twitch channel?**
https://twitch.tv/spherous

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Mostly C#/VSC/Unity/Blender, current heavy focus in DOTS/ECS

**Why do you write code on stream?**
Outside of general enjoyment, I really like how it holds me accountable while keeping me consistently working on something that I care about.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Pretty much every time some bit of code works on the first try. Satisfying. (now that you mention clip, I should start clipping those moments)

Thanks for the consideration guys! :D

**Comment by csharpfritz** [comment]
Look for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.
