### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by playdeezgames** [livecoders/Home#105]
**What is the URL for your Twitch channel?**
https://www.twitch.tv/thegrumpygamedev

**What languages / frameworks / tools do you program in while streaming on Twitch?**
F# gamedev in dotnet core with vscode, and Lua (in the Defold engine)

**Why do you write code on stream?**
After realizing that coding streams were a thing, I couldn't help but try it. I've made several streamerfriends to raid/heckle/faff about with, two of whom (GarethHubball and tbdgamer) are already on-team and suggested I apply. "hashtag-namedrop"

**What is your favorite moment from coding on stream?  Share a clip if one is available**
It has been some time, but some of my favorite moment were from about a year ago, when I got to do some VS liveshare stuff and mentor some fellow streamers.

**Comment by garethhubball** [comment]
I would really like to see playdeezgames become a member of the team, he streams frequently and has some very interesting topics, is incredibly accommodating to viewers and welcomes any opportunity to help no matter how much it side-tracks him.

**Comment by csharpfritz** [comment]
Look for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.
