### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by brob** [livecoders/Home#106]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/bryanlrobinson

**What languages / frameworks / tools do you program in while streaming on Twitch?**
JAMstack, CSS, Web development, 11ty, HTML, web design

**Why do you write code on stream?**
Looking to build a fun community and promote the technologies that I like (things like static sites, CSS, etc.) that sometimes get less promotion in the world

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I was live coding some web building with 11ty and was having some struggles with something I knew should work and finally figured it out (with some testing ideas from chat) and then jokingly got smug with my code.

Highlight: [https://www.twitch.tv/videos/554073404](https://www.twitch.tv/videos/554073404)

**Comment by csharpfritz** [comment]
Look for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.
