### ISSUE TITLE
Rerun the Twitch to markdown converter periodically

### ISSUE THREAD

**Issue by garethhubball** [livecoders/Home#107]
I've noticed that the status that is showing for my stream is a very old one and bears no resemblance to what's going on in the stream, it looks like the data was last scraped in October last year so I expect that it will be out of date for a lot of people. Would it be worth investigating the idea of making it a periodic task and maybe automate the twitch teams to markdown converter to keep the data fresh?

**Comment by csharpfritz** [comment]
Great idea...  is there a  way to schedule a GitHub action to run periodically?

**Comment by garethhubball** [comment]
I've just had a quick look at the docs and found this: https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule which seems to use cron syntax to run an action periodically, however I have yet to use Github actions so I'm not sure if I'm looking in the right places.

**Comment by asottile** [comment]
here's an example for periodic execution: https://github.com/pre-commit/pre-commit.com/blob/043c9e5e3583687fd044639894fd711f75b65a29/.github/workflows/deploy.yml#L6-L7

**Comment by LuckyNoS7evin** [comment]
Removed the markdown converter in #261 reason is to keep a single page for the team rather than multiple sources. as livecoders.dev didn't have a site previously this was needed, it's no longer an issue
