### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by ScooterSam** [livecoders/Home#108]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/iDevelopThings

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Laravel, AdonisJS, Vue, TailwindCSS

**Why do you write code on stream?**
I share my work programming journeys and my personal project streams

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Fixing all the little bugs i discover

If you have any questions about this process, please contact [_KittyKerns on Twitter](https://twitter.com/_kittykerns)

**Comment by CaptCalli** [comment]
@ScooterSam Your vods are currently set for subs only, Could you set them to be viewable by everyone so we can review them? Thank you!

**Comment by ScooterSam** [comment]
@CaptCalli I've disabled it, sorry about that!

**Comment by csharpfritz** [comment]
Look for an invite in your email from Twitch to join.  I'll then whisper your account on Twitch with a link to join the team Discord.

Welcome to the Live Coders!
