### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by SquidMonkeyStudios** [livecoders/Home#109]
**What is the URL for your Twitch channel?**
https://www.twitch.tv/squidmonkeystudios

**What languages / frameworks / tools do you program in while streaming on Twitch?**
I use C# in Unity using Visual Studio.

**Why do you write code on stream?**
I am a game developer streaming to get community feedback on my games design and code. I've found that streaming makes me accountable for not only what I write but also for what I set out to do.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I like those "Aha!" moments, whether they're positive or negative. They show me what I need to learn or that I can apply what I've learned in a new way.

https://www.twitch.tv/squidmonkeystudios/clip/SucculentChillyLemurKappaClaus?filter=clips&range=all&sort=time

**Comment by SquidMonkeyStudios** [comment]
I'm curious if my application has been rejected or if I have not provided the necessary information?

Any insight would be greatly appreciated.

**Comment by csharpfritz** [comment]
I take a few weeks to review applications, and then go through a bunch all at once.

Look for an invite in your email from Twitch to join.  I'll then whisper your account on Twitch with a link to join the team Discord.

Welcome to the Live Coders!
