### ISSUE TITLE
Application for Membership: syropian

### ISSUE THREAD

**Issue by syropian** [livecoders/Home#11]
**What is the URL for your Twitch channel?**
https://twitch.tv/syropian

**What languages / frameworks / tools do you program in while streaming on Twitch?**
- JavaScript (mostly Vue.js)
- [Laravel](https://laravel.com/)

**Why do you write code on stream?**
I've always enjoyed teaching and mentoring, and Twitch was a great opportunity to do both, and allow people to see how I go about building real-world projects using some awesome and popular tools.

I recently took a break from streaming (took a vacation, was kinda burnt out from regular job), and I wanted to wait until I could complete my Hackintosh build before continuing to stream. Now that my Hackintosh is up and running, I plan on continuing my Saturday morning streams on a consistent basis! 

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I've had a few moments where I couldn't figure out a problem, and I've had some viewers come in and bounce ideas off me that ultimately ended up fixing the problem. It's always good for a laugh when it's something super trivial, but I absolutely love the interaction with both the new and returning viewers.

**Comment by csharpfritz** [comment]
Looks great!  Please accept our invite to join the Live Coders team, and I will DM you a link to join our team Discord

**Comment by syropian** [comment]
Thanks Jeff! I went ahead and accepted the invite 🎉
