### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by assertchris** [livecoders/Home#110]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://www.twitch.tv/assertchris

**What languages / frameworks / tools do you program in while streaming on Twitch?**

- PHP
- [Laravel](https://laravel.com)
- [Livewire](https://laravel-livewire.com)
- [Inertia](https://inertiajs.com)
- JS
- [Adonis](https://adonisjs.com)
- Python
- [Masonite](https://docs.masoniteproject.com)

**Why do you write code on stream?**
I am motivated to build cool things when I can share them with other people in real time. Also a good opportunity for people to ask questions about the languages and frameworks I'm using.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
No huge moments, but many days when I feel like I've been super productive on stream. I limit my streams to around an hour, so that I can keep regular without it becoming a huge drain on time and energy. Some times an hour is not enough to make huge progress, but when it is it feels like an explosion of creativity and productivity. I love those moments.

If you have any questions about this process, please contact [_LilyHazel on Twitter](https://twitter.com/captcalli)

**Comment by csharpfritz** [comment]
Look for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.

**Comment by assertchris** [comment]
Much appreciated!
