### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by kesne** [livecoders/Home#111]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/VapeJuiceJordan

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Mostly TypeScript / GraphQL / Node.JS / React / Svelte

**Why do you write code on stream?**
I like to keep my skills sharp, and side-projects are my jam! Learning in public is the best.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
briefly describe
There are too many moments to really pick a favorite! My community constantly makes me laugh (and yell at them a little bit, but in good spirit I promise).

If you have any questions about this process, please contact [_LilyHazel on Twitter](https://twitter.com/captcalli)

**Comment by brandoncc** [comment]
I enjoy watching Jordan's stream. When he isn't teaching others by allowing us to watch him build open source software, he uses his time on the stream to do code reviews or work through interview questions so others can learn from him.

I believe he is a good candidate for Live Coders.

**Comment by erkrnt** [comment]
Hands down one of the most knowledgeable people I have met on Twitch. Incredibly helpful and willing to go the extra mile to make sure a viewer leaves with more than they came with.

Provides insights into real world engineering scenarios and sets good exceptions for people interested in the field.

10/10 - Would Watch Again

![Yes](https://media.giphy.com/media/l3E6z6QxD2uKoRTDq/giphy.gif)

**Comment by mtheoryx** [comment]
lol bump

Don't leave our man hangin! <3

**Comment by opti21** [comment]
He's really good at the coding thing, and has bigger hands than the Primeagen ;)

**Comment by ThePrimeagen** [comment]
Ohh I feel something so deep in my bones I thought it was the coronavirus, but no, it was actually Vape Juice (Grape juice for the insiders) Jordan.  This is the man.  Thee man.  Thy man.  Thoust man.  Him on the team right meow.

**Comment by csharpfritz** [comment]
Look for an invite in your email from Twitch to join.  I'll then whisper your account on Twitch with a link to join the team Discord.

Welcome to the Live Coders!
