### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by scheerer** [livecoders/Home#112]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://www.twitch.tv/blendedsoftware

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Java / SpringBoot / Docker / AWS / Serverless / Terraform / Ansible

**Why do you write code on stream?**
To "Give em the love" - https://www.youtube.com/watch?v=01h_yzyEtWM
Streaming is forceful accountability to accomplish something in front of an audience. Gathering with others to demonstrate how to leverage cloud services, automation, and how it applies to a mixed set of languages and technologies. My goal is to learn/demonstrate how traditional skillsets such as Java development can be leveraged in the cloud as well. Also, I just like being silly and having fun with chat.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Although my streaming has been rather short lived so far, we 
https://www.twitch.tv/blendedsoftware/clip/TrustworthyBoxyTroutTinyFace

**Comment by csharpfritz** [comment]
Caught some of the stream today, and saw the team comments on Discord.

Look for an email from Twitch with the invite to the team.  Once you're on the team on Twitch, I'll whisper you an invite to the team Discord
