### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by 7sharp9** [livecoders/Home#113]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://www.twitch.tv/7sharp9_dev

**What languages / frameworks / tools do you program in while streaming on Twitch?**
.Net with F#, vscode

**Why do you write code on stream?**
Its fun to share and interact with viewers

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Mainly whenever a viewer interacts and what was failing becomes a success!!   
e.g. https://www.twitch.tv/videos/562510876

If you have any questions about this process, please contact [_LilyHazel on Twitter](https://twitter.com/captcalli)

**Comment by csharpfritz** [comment]
Look for an invite in your email from Twitch to join.  I'll then whisper your account on Twitch with a link to join the team Discord.

Welcome to the Live Coders!

**Comment by 7sharp9** [comment]
Woo hoo!  Ive accepted the invite
Thanks @csharpfritz
