### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by asweigart** [livecoders/Home#114]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/AlSweigart

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Python

**Why do you write code on stream?**
Either I'm working on my open source projects (PyAutoGUI, mostly), reviewing Stackoverflow questions (and discussing how to write good programming questions), but mostly I'm working on a large collection of text-based Python games to provide beginners with example programs.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
None so far, I usually don't make clips.

If you have any questions about this process, please contact [_LilyHazel on Twitter](https://twitter.com/captcalli)

**Comment by csharpfritz** [comment]
Al, you're ABSOLUTELY welcome to join the team.

Look for an invite in your email from Twitch to join.  I'll then whisper your account on Twitch with a link to join the team Discord.

Welcome to the Live Coders!
