### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by rochacbruno** [livecoders/Home#115]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/codeshow

**What languages / frameworks / tools do you program in while streaming on Twitch?**
- Python
- Rust

**Why do you write code on stream?**
I stream as a way to keep myself updated on the technologies I use, in my current job I am a Quality Engineer (at Red Hat) and I work only with test automation.
Streaming is a way to put my hands more in to coding different challenges and be aware of recent updates while I share this with my followers and subs.
(also, maybe I can make some money from supporters and I plan to invest it 100% on my streaming setup)

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I am learning the Rust Programming Language by doing live streams of Exercism.io challenges, last week I was finishing my Atbash-Cipher exercise and i was about to submit it for review when one of the exercism mentors entered on my chat and asked to help me and give me mentorship right on the stream.

We shared a discord voice channel and he helped me to make my code better.

Clip: https://www.twitch.tv/videos/565317434
Youtube: https://www.youtube.com/watch?v=eozFDBG0aiA

Note:
I use to stream in 2 languages. English on Tuesdays and PortugueseThursdays.
I also host another Youtube Channel in portuguese https://youtube.com/CodeShowBR

If you have any questions about this process, please contact [_LilyHazel on Twitter](https://twitter.com/captcalli)

**Comment by csharpfritz** [comment]
Look for an invite in your email from Twitch to join.  I'll then whisper your account on Twitch with a link to join the team Discord.

Welcome to the Live Coders!

**Comment by rochacbruno** [comment]
Hi @csharpfritz thanks I just accepted! :)

**Comment by rochacbruno** [comment]
Hi, @csharpfritz I still haven't received the link to the discord, maybe I missed it.

tks
