### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by Niggelgame** [livecoders/Home#116]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/niggelgame

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Flutter in VS Code --> Bloc
IntelliJ Ultimate for Kotlin --> Ktor, Jetbrains Exposed
PhpStorm --> Blade, Vendor Router
Python --> Flask

**Why do you write code on stream?**
Because I want to show how to code, motivate other people to do the same. I like coding, and I asked myself, why shouldn't I stream it. Mostly I was surprised that only a few Coding-Streamers are German, so I hooked myself up and started Coding-Streaming. I like to help other people while coding too, of course, but it is not rare, if I just figure out a solution for my problem together with my chat.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
When I think something works, but then suddenly my whole computer crashes (;.
Some would say, when I try to use Kotlin for the first time, but then I completely fail, but for me it is just when there are some people trying to help you understand to what you are coding.

If you have any questions about this process, please contact [_LilyHazel on Twitter](https://twitter.com/captcalli)

**Additional Information**
I also speak English, but I would be the first german speaker in this team.

**Comment by csharpfritz** [comment]
Look for an invite in your email from Twitch to join.  I'll then whisper your account on Twitch with a link to join the team Discord.

Welcome to the Live Coders!
