### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by omarcresp** [livecoders/Home#117]
**What is the URL for your Twitch channel?**
https://twitch.tv/jackcres

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Javascript - Angular, NodeJS
C# - Unity

**Why do you write code on stream?**
Know people, create community, help others, just get company while i'm working on projects, teach any if posible

**What is your favorite moment from coding on stream?  Share a clip if one is available**
It was about 2 moths ago, so i haven't a clip. One guy join the stream and start to make a lot of questions about their struggles with Angular, i stopped my project for 20 minutes and invite him to join the stream and solve the problemos together live

**Aditional Information**
I don't speak english, i would be the first spanish speaker in the team ^^

**Comment by LuckyNoS7evin** [comment]
Live Coder Intern - Nurturing Program - Acceptance

With The Live Coders growing rapidly the team introduced a minimum viewership and other criteria. 

- Interactivity
- Inclusivity
- Community
- Teaching
- Learning

You are invited to become a Live Coders Intern, not a part of the full Twitch team (some of the benefits are excluded) you will be invited to The Live Coders Discord server where you can learn from the rest of the team. (restricted access not all channels)

Please contact me to get your access

- @TheS7evin -> Twitter
- LuckyNoS7evin#0001 -> Discord
- LuckyNoS7evin -> Twitch
