### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by nicolaiparlog** [livecoders/Home#118]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**

https://twitch.tv/nipafx

**What languages / frameworks / tools do you program in while streaming on Twitch?**

Mostly Java, sometimes JavaScript and others

**Why do you write code on stream?**

I like sharing what I know, but more than that I like learning with others. At least half of what I do on stream is tinkering with things that I never used before to figure out how they work. Doing that with company is more fun, but also helpful because viewers often know more about what the tech than I do. Basically, I trick them into teaching me. :wink: 

**What is your favorite moment from coding on stream?  Share a clip if one is available**

* [when things work](https://www.twitch.tv/nipafx/clip/EasyHelpfulSageHassanChop)
* [when things don't work](https://www.twitch.tv/nipafx/clip/WittyAbnegateJuiceOSfrog) :grin:

**Comment by csharpfritz** [comment]
Look for an invite in your email from Twitch to join.  I'll then whisper your account on Twitch with a link to join the team Discord.

Welcome to the Live Coders!

**Comment by nicolaiparlog** [comment]
Thanks for having me. :)
