### ISSUE TITLE
Application for Membership (SirLynixVanFrietjes)

### ISSUE THREAD

**Issue by SirLynix** [livecoders/Home#119]
Warning, french streamer ahead (with little to non-existent english).

**What is the URL for your Twitch channel?**
https://www.twitch.tv/sirlynixvanfrietjes

**What languages / frameworks / tools do you program in while streaming on Twitch?**
I'm mostly doing C++, Lua and Rust (in that order), sometimes other stuff as well.
I'm making my own game engine from scratch (in C++) and I use it to make some games (2D & 3D).

**Why do you write code on stream?**
I love to explain stuff to people and frequently pause my own work to explain stuff about C++, my game engine, etc.
I also like to entertain people, act like crazy (all natural) and have opinions about my own work.
Also, being watched helps a lot to focus on my work.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
[Explaing how my ships will act when I reload the scripts](https://www.twitch.tv/sirlynixvanfrietjes/clip/ObservantTangentialBeanSquadGoals)
[Some viewer asked me what would happen if two players were to use a gravgun on each other](https://www.twitch.tv/sirlynixvanfrietjes/clip/JazzyThoughtfulHerbsMingLee)
[Me using my potato brain to compute 30 degrees as radians](https://www.twitch.tv/sirlynixvanfrietjes/clip/MuddyLitigiousThymeBlargNaut)

**Comment by csharpfritz** [comment]
Welcome to the Live Coders!  Look for a Twitch team invite in your email.  Click through to accept that invite and we'll get you on our team mailing list and Discord
