### ISSUE TITLE
Application for Membership: jumpystick

### ISSUE THREAD

**Issue by kayteh** [livecoders/Home#12]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/jumpystick

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Typically JS/TS, Go, really whatever's best for the job.

**Why do you write code on stream?**
When I started over 2 years ago, I did it to show off what I was building. In the middle of that, someone asked me a really intermediate JS question and I decided to explain it, and from that point, I was hooked forever; and it led me into my own way of teaching through Twitch.

I do it because I enjoy the community I've fostered into life, giving both new and seasoned engineers a place to share their knowledge. I do it because building whatever I want is always something I can teach others and myself from, and letting others in on that cycle is a driving factor. Seeing engineers in the community go from "Hi, I'm learning React!" to "I just got my first code job!" never gets old, either.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
My favorite that I have a clip of was when I explained Go mutexes, without totally knowing how it's going to turn out, to completely ninja the explanation.
https://clips.twitch.tv/InexpensiveBashfulCrocodileMrDestructoid

Pretty much anything that causes memes are my real favorites, especially when I find them in clips later!~

**Comment by csharpfritz** [comment]
Looks great!  Please accept an invite to join the Live Coders team!  I'll DM an invite to the team Discord
