### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by MishManners** [livecoders/Home#120]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://www.twitch.tv/mishmanners

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Regularly stream lots of random things. I've hosted the GitHub Actions hackathon go to live on Twitch, and now been asked to host many other virtual hackathons live on my Twitch channel.
Done a couple of streams on GitHub Actions
Python stream (I'm not that great at it, but I try!)
Coming streams include:
Unity programming
Deep Racer
+ heaps more

Oh and I also host weekly AMA sessions where people can ask questions. Lots of questions around hackathons (I'm known as the Hackathon Queen), streaming, GitHub Actions, GitHub, upcoming coding events.

I do also play lots of games on my Twitch stream, and I've done hardware streams in the past building things like robots, showing off Spheros, building RC cars etc.

**Why do you write code on stream?**
Because I love to interact with people. I like teaching things and having a community, but I also like LEARNING! I can learn from the community and they can learn from me. It's what we do in DevRel, plus it's super fun, it's just my personality.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Would have to be this one from a recent stream:
https://www.twitch.tv/mishmanners/clip/RockyEnticingRutabagaM4xHeh?filter=clips&range=7d&sort=time

If you have any questions about this process, please contact [_LilyHazel on Twitter](https://twitter.com/captcalli)

As an FYI @csharpfritz invited me to make this application. Thanks for taking the time to read my application and looking forward to your response 😄

**Comment by csharpfritz** [comment]
For sure!  Welcome to the Live Coders.  Look for an invite from Twitch, and I'll Twitch-whisper you a link to the team's private Discord.

**Comment by MishManners** [comment]
OMG yay!!! Will accept the invite, and look out for your whisper @csharpfritz - still haven't received yet ❤️

**Comment by csharpfritz** [comment]
Invite email sent! You should have an email in your Twitch account's inbox


Jeff
