### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by mrdon** [livecoders/Home#121]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/mrdonbrown

**What languages / frameworks / tools do you program in while streaming on Twitch?**
- Python
- Django
- Docker
- Terraform

**Why do you write code on stream?**
- Helps keep me focused on the task and meet new folks

**What is your favorite moment from coding on stream?  Share a clip if one is available**

No real moment comes to mind, but I'm always pleasantly surprised when someone takes the time to follow what I'm doing in detail and make suggestions.  Hours have been saved so far.

If you have any questions about this process, please contact [_LilyHazel on Twitter](https://twitter.com/captcalli)

**Comment by LuckyNoS7evin** [comment]
Live Coder Intern - Nurturing Program - Acceptance

With The Live Coders growing rapidly the team introduced a minimum viewership and other criteria. 

- Interactivity
- Inclusivity
- Community
- Teaching
- Learning

You are invited to become a Live Coders Intern, not a part of the full Twitch team (some of the benefits are excluded) you will be invited to The Live Coders Discord server where you can learn from the rest of the team. (restricted access not all channels)

Please contact me to get your access

- @TheS7evin -> Twitter
- LuckyNoS7evin#0001 -> Discord
- LuckyNoS7evin -> Twitch
