### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by davidwengier** [livecoders/Home#124]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/davidwengier

**What languages / frameworks / tools do you program in while streaming on Twitch?**
C#, .NET, Visual Studio, SkiaSharp, Comet ☄

**Why do you write code on stream?**
I previously have spoken at a bunch of meetups and conferences, and I enjoy explaining coding things to people in that environment, but by far my favourite time is always after a talk, when people came up and asked questions and chatted free of the social pressure of putting their hand up in a dark room. I wanted to start streaming as a way to focus on that part of the experience, and hopefully teach some things along the way. I also wanted to reach .NET devs in Australia, or at least the Australian timezone, where there isn't a _huge_ number of tech conferences.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Any time something I've been building up to works, makes me happy. Streaming is also good for _me_ as a forcing function to work on a project I'm passionate, so the first time a train moved, or went around a corner, or two tracks joined up, they're all my favourites.
A most recent example, from last nights stream: https://clips.twitch.tv/LuckyEnjoyableYakinikuSpicyBoy
Or in case that one times out: https://clips.twitch.tv/NaiveDeafJalapenoPermaSmug

If you have any questions about this process, please contact [_LilyHazel on Twitter](https://twitter.com/captcalli)

**Comment by csharpfritz** [comment]
Look for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.

**Comment by davidwengier** [comment]
Thanks @csharpfritz I've accepted the invite!
