### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by kkemple** [livecoders/Home#125]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/theworstdev

**What languages / frameworks / tools do you program in while streaming on Twitch?**
- JavaScript
- React
- GraphQL
- TypeScript
- Apollo GraphQL
- Node.js

Design/video/photo/podcasting
- Photoshop
- Audition
- Premiere Pro
- Sketch

**Why do you write code on stream?**
I really enjoy collaborating with others. Every time I get to share something useful and generally also learn something new. It's a really great way to engage with developers outside of my team at work.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
My favorite moment is definitely this clip where I was caught bouncing something back and forth in my head and couldn't decide if something was correct or not. The reason I love it so much is that it's one of the first times someone created a clip from my stream and found my banter amusing enough to share. I really enjoy feeling connected like that. It's almost like an inside joke except you didn't have to be there, because it was recorded.

https://www.twitch.tv/theworstdev/clip/TsundereTangibleCaterpillarOptimizePrime

**Comment by LuckyNoS7evin** [comment]
Unfortunately at this time did not meet the standard for becoming a live coder. Can discuss further privately if required

**Comment by kkemple** [comment]
No need for further discussion. I would like to note that I applied months ago and did meet the requirements at the time, I had actually forgotten I'd applied. This process is very slow. :(
