### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by 1kevgriff** [livecoders/Home#126]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/1kevgriff

**What languages / frameworks / tools do you program in while streaming on Twitch?**
C#
.NET Core
ASP.NET Core
Microsoft Azure
JavaScript
Vue.JS

Visual Studio
Visual Studio Code

**Why do you write code on stream?**
I've always been a fan of learning in public and teaching everything I know.  Long before streaming, I have hosted webinars and other online gatherings.

And as an independent consultant, it's rare that I have projects that I'm able to talk about publicly.  I've found that streaming is great for flexing my muscles on projects that I wouldn't normally have spent time on.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Not exactly a moment - but I love that real-time help on any problem I'm trying to solve.  A while back I had attempted to teach myself Vue.JS on the stream, and starting working on a "real project".  Every time I would ask a question to myself, someone in the stream would say "Oh, you want to do X" and we'd go down the rabbit hole of what "X" was.  It was a lot of fun and informative for everyone involved.

If you have any questions about this process, please contact [_LilyHazel on Twitter](https://twitter.com/captcalli)

**Comment by csharpfritz** [comment]
Looking for a little more regular streaming to consider. 

Will revisit this application in May

**Comment by 1kevgriff** [comment]
I'll work on it!  Thanks!

**Comment by csharpfritz** [comment]
There we go!  Happy to see you engaging the Twitch community.

Look for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.
