### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by aslotte** [livecoders/Home#128]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://www.twitch.tv/alexslotte

**What languages / frameworks / tools do you program in while streaming on Twitch?**
List briefly here
- Machine Learning in .NET using ML.NET
- Apache Spark in .NET
- C#/.NET
- Azure

**Why do you write code on stream?**
I enjoy streaming on Twitch as a means to help others. I also find it that teaching a topic is the best way for myself to learn something new. 

**What is your favorite moment from coding on stream?  Share a clip if one is available**
When something I expected to work didn't work, and the way to solve it was to actually google the problem to find a solution. I like that I was able to demonstrate my own thought process and that we don't know everything by heart, but just like anyone else, we have to search for our knowledge. 

If you have any questions about this process, please contact [_LilyHazel on Twitter](https://twitter.com/captcalli)

**Comment by csharpfritz** [comment]
We appreciate the interest, but Live Coders team members are Twitch affiliates or partners and stream on a regular basis while interacting with their chat room.

Please consider applying in the future as your channel grows
