### ISSUE TITLE
Application for Membership: grahamweldon

### ISSUE THREAD

**Issue by predominant** [livecoders/Home#13]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/grahamweldon

**What languages / frameworks / tools do you program in while streaming on Twitch?**
C# (Unity), Python, Golang, Ruby, Shell

**Why do you write code on stream?**
I want to teach viewers as much as possible, and learn myself along the way.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Getting one of my first flights in a realstic-physics plane simulation game, and having the airflow drag calculated backwards! https://www.twitch.tv/grahamweldon/clip/BelovedSpunkyStarAsianGlow This was a great moment where the community got together and had a laugh and cheered each other on. We had all put in work researching the right physics and after a week of streaming, the first successful takeoff was hilarious

**Comment by csharpfritz** [comment]
Looking at your recent history of streams on Twitch, I don't see any live coding streams in the last six months.  Are there events that I'm not seeing?

**Comment by predominant** [comment]
The [linked clip](https://www.twitch.tv/grahamweldon/clip/BelovedSpunkyStarAsianGlow) was in January. Thats within the last 6 months.

Here are some more clips within the last 6 months:

* https://www.twitch.tv/grahamweldon/clip/NastySmellyClipzUnSane
* https://www.twitch.tv/grahamweldon/clip/PiliableKnottyButterPanicVis
* https://www.twitch.tv/grahamweldon/clip/DreamySneakyHyenaBibleThump
* https://www.twitch.tv/grahamweldon/clip/CheerfulLongNewtJKanStyle
* https://www.twitch.tv/grahamweldon/clip/SneakyDelightfulGoshawkTakeNRG
* https://www.twitch.tv/grahamweldon/clip/CleverStormyMacaroniRalpherZ
* https://www.twitch.tv/grahamweldon/clip/PowerfulBloodyWebPicoMause

Because I am not a partner (only affiliate) my VoD storage is only for 14 days (except for those that were stored before that policy change).

Here is a screenshot of Twitch settings for reference:

![image](https://user-images.githubusercontent.com/24568/60258175-93846f80-990f-11e9-8fa6-be4f9febf419.png)

**Comment by csharpfritz** [comment]
Just reviewed content...  looks great to see 'Totally Normal Mini-Golf'  lol

Approved.  Please send me a whisper on Twitch and I will send along an invite to the team Discord
