### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by asottile** [livecoders/Home#130]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/anthonywritescode

**What languages / frameworks / tools do you program in while streaming on Twitch?**
- python mostly
- I maintain a bunch of python frameworks and tools: pre-commit, tox, pytest, flake8, etc. that I often work on
- recently I've been spending a lot of my stream working on my text editor ([babi](https://github.com/asottile/babi))

**Why do you write code on stream?**

it gives me a place to focus on building stuff, or at least that's why I started -- now I mostly code on stream **because it's fun** to interact with chat while I'm building stuff.

**What is your favorite moment from coding on stream?  Share a clip if one is available**

I really like clips, here's a few of my favorites -- I don't know if they're my favorite streaming moments but I think they're pretty funny:
- https://www.twitch.tv/anthonywritescode/clip/SuperShyDelicataPupper
- https://www.twitch.tv/anthonywritescode/clip/ObservantAlertHamsterCorgiDerp
- https://www.twitch.tv/anthonywritescode/clip/HeartlessHelpfulCougarImGlitch
- https://www.twitch.tv/anthonywritescode/clip/AgitatedAlluringMonkeyPJSalt
- https://www.twitch.tv/anthonywritescode/clip/DarkGoodCheeseJonCarnage

If you have any questions about this process, please contact [_LilyHazel on Twitter](https://twitter.com/captcalli)

**Comment by ofek** [comment]
I can confirm that Anthony's streams are very enjoyable and insightful 😄

**Comment by csharpfritz** [comment]
Look for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.
