### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by TeoCalvo** [livecoders/Home#132]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/teomewhy

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Python - pandas, numpy, scipy, scikit-learn, 
SQL

**Why do you write code on stream?**
Mostly for teach people. I love teach who want to learn programming and data science tool kit. Another point is share my knowledge in Data Science and help community in best practice.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
briefly describe
Teaching how mutable variables working in Python:
https://www.twitch.tv/videos/481491296

Making predictions after fit a machine learning model
https://www.twitch.tv/videos/552307628

If you have any questions about this process, please contact [_LilyHazel on Twitter](https://twitter.com/captcalli)

**Comment by csharpfritz** [comment]
Welcome to the Live Coders!  Look for a Twitch team invite in your email.  Click through to accept that invite and we'll get you on our team mailing list and Discord
