### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by krassenstein** [livecoders/Home#133]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/Krassenstein

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Unity3D / C# / Visual Studio Community 2019

**Why do you write code on stream?**
Being a social person, I'm significantly more productive when I have people to interact with while working. Also, I use it as a form of marketing / promotionals to interact with an audience that may have similar interests to the games that I make.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I always enjoy all moments while I'm making games, but when bugs or visual glitches occur that couldn't even seem possible, those are the ones that get me. https://clips.twitch.tv/LivelyMagnificentMonitorThisIsSparta

If you have any questions about this process, please contact [_LilyHazel on Twitter](https://twitter.com/captcalli)

**Comment by csharpfritz** [comment]
Look for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.
