### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by chances** [livecoders/Home#134]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/enigmaticeffigy

**What languages / frameworks / tools do you program in while streaming on Twitch?**
- JavaScript/TypeScript
- C#
- Dart/Flutter
- Deno
- Rust
- C/C++
- etc.

**Why do you write code on stream?**
To share my experience, educate, and it's a great way to advertise my products. I've been at it for a decade at this point and doing it on stream gets me out of a lonely silo.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I remember one of the first times I streamed back on LiveCoding.tv I was "frequented" by someone who asked great questions. It was really engaging being asked specific questions about what I was doing as I was doing it. That experience sold me on getting away from coding alone in a silo.

If you have any questions about this process, please contact [_LilyHazel on Twitter](https://twitter.com/captcalli)

**Comment by chances** [comment]
I don't think I'm an "Affiliate" or "Partner" on Twitch, tho I have experience live coding. Was this application appropriate at this step?

If not, what should I be doing to ready an application?

**Comment by garethhubball** [comment]
I would say stream more and stream regularly, then you can become an affiliate and become eligible to join.

**Comment by csharpfritz** [comment]
Please re-apply when you have reached affiliate status
