### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by evjand** [livecoders/Home#136]
**What is the URL for your Twitch channel?**
https://www.twitch.tv/codepurpl

**What languages / frameworks / tools do you program in while streaming on Twitch?**

- JavaScript
- TypeScript
- React
- Firebase
- Swift
- Xcode
- VS Code

**Why do you write code on stream?**
I write code on stream to challenge myself and to learn new stuff. I want to inspire others and share my knowledge.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I think my favorite so far is when I got invite mail for Twitch Affiliate live on stream and got my game logic working at [the same time](https://www.twitch.tv/videos/591050997).

**Comment by LuckyNoS7evin** [comment]
Past Broadcasts not saved
