### ISSUE TITLE
Membership Application: Sana Rinomi

### ISSUE THREAD

**Issue by SanaRinomi** [livecoders/Home#137]
```javascript
class Twitch {
    get TwitchURL() { return this.url; }
    get STools() { return this.tools.join(", "); }
    get SContent() { return `What I Generally do: "${this.content.general}", What I'm currently doing: "${this.content.current}", What I have planned afterwards: "${this.content.planned}"`; }
    get SBestMoments() { return `What it was: "${this.bestMoments.moment}", Context: "${this.bestMoments.context}"`; }

    constructor(url, tools, content, bestMoments) {
        this.url = url;
        this.tools = tools;
        this.content = content;
        this.bestMoments = bestMoments;
    }
}

let sanaTwitch = new Twitch("https://twitch.tv/sana_rinomi", ["JS", "WLS", "NodeJs", "VS Code"], {
    general: "Depends",
    current: "Discord Bot Framework",
    planned: "Discord Bots"
}, {
    moment: "Pls show more leg.",
    context: "Was at a GameJam and delirious me received a 50€ donation saying that, it became a meme and while the clip is not to be found, the quote lives on!"
});
```

**What is the URL for your Twitch channel?**
```console.log(`My Twitch URL: ${sanaTwitch.TwitchURL}`); // Output: My Twitch URL: https://twitch.tv/sana_rinomi```

**What languages / frameworks / tools do you program in while streaming on Twitch?**
```console.log(`Tools I use: ${sanaTwitch.STools}`); // Output: Tools I use: JS, WLS, NodeJs, VS Code```

**Why do you write code on stream?**
```console.log(sanaTwitch.SContent); // Output: What I Generally do: "Depends", What I'm currently doing: "Discord Bot Framework", What I have planned afterwards: "Discord Bots"```

**What is your favourite moment from coding on stream?  Share a clip if one is available**
```console.log(sanaTwitch.SBestMoments); // Output: What it was: "Pls show more leg.", Context: "Was at a GameJam and delirious me received a 50€ donation saying that, it became a meme and while the clip is not to be found, the quote lives on!"```

**Comment by csharpfritz** [comment]
Look for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.
