### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by bwheatley** [livecoders/Home#138]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/bwheatley

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Working with C# to develop a Unity Game. 

**Why do you write code on stream?**
I write code on stream at the bare minimum to have a rubber duck to keep me accountable.
I enjoy chat helping with the design of features, with helping debug. I enjoy connecting with others,
we've had a lot of good streams so far where we are trying to build a community of like minded folks.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I don't have a clip at the moment, I'm so busy between work, and streaming and then family to have a ton of time for the clip stuff.
But over this weekend I was working on getting a jobs system going where you'll loop through a job, a job can have multiple steps, and I was using bools for managing the state. 
ShadowTzu, someone whos created a game engine in VB.net!, was saying convert it to be enum based and then we worked together to refactor and got it 99% working. We're still trying to crack a bug 
that's happening occasionally. But that showed me that teamwork makes the dreamwork and together we are greater than the sum of our parts.

If you have any questions about this process, please contact [_LilyHazel on Twitter](https://twitter.com/captcalli)

**Comment by csharpfritz** [comment]
Look for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.
