### ISSUE TITLE
Application for Membership: lizelive

### ISSUE THREAD

**Issue by lizelive** [livecoders/Home#14]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/lizelive

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Unity, C#, Python, Tensorflow, Rust

**Why do you write code on stream?**
Coding gave me the ability to get out of a really toxic situation, and I want to help other people do that.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
briefly describe
1 day minecraft clone game was fun because a few viewers where able to follow along and make their own minecraft.
Also the entire BGI dev has been insane with people suggesting all kinds of crazy stuff. It's been amazing. https://youtu.be/VT-Il8Q09Rk

**Comment by csharpfritz** [comment]
Looks good!  Please accept the team invite in your email, and I will DM you on Twitch with a link to join our team Discord
