### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by JovanVladislav** [livecoders/Home#140]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://www.twitch.tv/succubusmistress

**What languages / frameworks / tools do you program in while streaming on Twitch?**
CLion/C++/ Java EE

**Why do you write code on stream?**
I recently started streaming, and coding again. I took a looong break, and i feel supper hyped about coding on stream. I'm not an expert programmer, but i'm planing on streaming at least 6-7 hours everyday and learning alongside my viewers.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I helped my friend to get over his mental block of not thinking his good enought to be a coder,my people just feel like they don't have the mental capacity to do someting like coding, and i'm here to prove them wrong.

If you have any questions about this process, please contact [_LilyHazel on Twitter](https://twitter.com/captcalli)

**Comment by LuckyNoS7evin** [comment]
No Past broadcasts saved
