### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by praeclarum** [livecoders/Home#141]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/FrankKrueger

**What languages / frameworks / tools do you program in while streaming on Twitch?**
I try to use every language out there. So far a large focus has been on F#. But I also use C#, C, Go, JavaScript. I love to use Visual Studio for MAC but also use VS Code for text editing.

**Why do you write code on stream?**

Well I talk to myself while coding, so I might as well have an audience. Also Gareth thought it would be a good idea. And I've come to really enjoy hanging out with the chat room on my Saturday mornings.

**What is your favorite moment from coding on stream?  Share a clip if one is available**

That time we went 8 hours and wrote a whole compiler. That was insane. I didn't think anyone would stick through to the end, but a lot of wonderful did.
If you have any questions about this process, please contact [_LilyHazel on Twitter](https://twitter.com/captcalli)

**Comment by csharpfritz** [comment]
Look for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.
