### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by razvan-flavius-panda** [livecoders/Home#142]
**What is the URL for your Twitch channel?**

https://www.twitch.tv/freeman42x

**What languages / frameworks / tools do you program in while streaming on Twitch?**

Haskell, Nix, Atom, NixOS LInux

**Why do you write code on stream?**

It helps me and others to become better at software development. It is also a great way to meet other developers and become friends.

**What is your favorite moment from coding on stream?  Share a clip if one is available**

I don't have a favorite moment yet, you can see some coding here: https://www.twitch.tv/videos/591331117?t=1h8m35s

And here I explain how to use mind mapping software such as Freeplane to do software development more efficiently: https://www.twitch.tv/videos/595366460?t=0h0m5s

**Comment by razvan-flavius-panda** [comment]
Here is another highlight about writing a blog post on the topic of why learn Haskell programming language: https://www.twitch.tv/videos/599087541

**Comment by LuckyNoS7evin** [comment]
Live Coder Intern - Nurturing Program - Acceptance

With The Live Coders growing rapidly the team introduced a minimum viewership and other criteria. 

- Interactivity
- Inclusivity
- Community
- Teaching
- Learning

You are invited to become a Live Coders Intern, not a part of the full Twitch team (some of the benefits are excluded) you will be invited to The Live Coders Discord server where you can learn from the rest of the team. (restricted access not all channels)

Please contact me to get your access

- @TheS7evin -> Twitter
- LuckyNoS7evin#0001 -> Discord
- LuckyNoS7evin -> Twitch

**Comment by razvan-flavius-panda** [comment]
@LuckyNoS7evin I've been off from streaming for about half a year and I restarted streaming at the beginning of this year so I do not know what happened to the nurturing program.

What are the current requirements needed to join the team?
