### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by Terraya** [livecoders/Home#144]
**What is the URL for your Twitch channel?**
https://www.twitch.tv/arturnachodude

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Most of the time i use Unity Engine as i am developing my own RPG since the past 7 Months, so C#
also doing sometimes streams on Java(Spring Boot) / JS (React) and different types of Databases

**Why do you write code on stream?**
God there are so many reasons .. , imagine creating something .. what is "Art" .. thats what we are doing in my eyes, we are artists .. , and its just incredible when people come around my stream, see me coding my game and ask "when can i play it" and so on ... , or different .. when other people with less experience come around and wonder when they can archieve the same and i can tell them .. just keep grinding .. you will get there soon!

**What is your favorite moment from coding on stream?  Share a clip if one is available**
So actualy as many people here i have less clips on explaining things , also my streams are most of the time in german but also in english , but what are my favorite moments from coding on stream? I think every day when i start streaming and someone new comes around and just keeps asking stuff or just write stuff so i can interact with the person .. just alot more fun to code with people who try to be a part of your art

PS: i speak 7 languages, so if my english is not that good, im sorry for that

**Comment by Terraya** [comment]
Hey there, actualy i had yesterday a nice moment where i remember my application to this great group, 

https://www.twitch.tv/videos/602363024 , 6h 23min 26sec, it goes a bit longer so i cant actualy make a clip out of that i think :)

**Comment by Terraya** [comment]
Hey there!

Im going on Vacation for the next 2 weeks,
i hope you dont count that into my current live Streaming

**Comment by csharpfritz** [comment]
Welcome to the Live Coders!  Look for a Twitch team invite in your email.  Click through to accept that invite and we'll get you on our team mailing list and Discord
