### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by proevilz** [livecoders/Home#147]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/proevilz

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Javascript/TS - NestJS, React/NextJS, Vue/NuxtJS, Nodejs, arbitary libraries and all the usual build tools etc
PHP - Wordpress, Laravel/Lumen (not done on stream yet)
HTML/CSS

**Why do you write code on stream?**
Currently building what is effectively another Streamlabs or Streamelements. Chatbot webapp with a user dashboard to control commands, music etc.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I tend to stream long hours so I can't find the exact clip but probably when I finally got some thing working I was stuck on for so many hours... we've all experienced that moment of magic, amiright??

If you have any questions about this process, please contact [_LilyHazel on Twitter](https://twitter.com/captcalli)

**Comment by seekaplayer** [comment]
@proevilz has helped me out so many times in my stream and is very knowledgeable.

**Comment by proevilz** [comment]
@seekaplayer Thanks man!

**Comment by LuckyNoS7evin** [comment]
Past Broadcasts not saved
