### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by mbifulco** [livecoders/Home#148]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/irreverentmike

**What languages / frameworks / tools do you program in while streaming on Twitch?**
I'm currently rebuilding a MOOC called thegymnasium.com with Gatsby / react + TakeShape CMS.  This occasionally also includes django/python work.

I'm writing a book in ASCIIdoc on stream as well.

Finally, in the next couple weeks I'm going to start doing some paired programming on stream with a person who I've just started mentoring.  It's another Gatsby project, and should be a great exemplar of the value of streaming and working on projects out in the open. 

**Why do you write code on stream?**
I've been tremendously lucky in my career - a steady stream of good luck and privilege led to me learning to code at a relatively early age, and to be working in software since I was in high school.  I feel a strong ethical and moral urge to give back to the community that's given me everything I have.  My streams are dedicated to showing people what it's like to work as a developer and a designer in the real world.  Most of my streams involve tackling a real world task completely unscripted.  I talk through what I'm thinking as I work so that the folks watching can benefit from my thought process.  Just as importantly, I think it's useful for people who are learning to code to see that not everything works on the first try! Research, trial and error, inquisitiveness, and knowing when, where, and how to ask for help are critical to all of our success.

Lastly, many of the projects I work on are OSS, including https://thegymnasium.com, https://protect.earth, and https://apisyouwonthate.com - and in the spirit of Open Source, I love the idea of working on the projects in the open!

**What is your favorite moment from coding on stream?  Share a clip if one is available**
My streams are starting to grow in viewer participation - my favorite moments are those where I get to help someone learn from what I'm doing, or to talk with them about what they're working on.  I should do a better job of making clips from these as I work in the future; I always forget to use that feature!

I recently discussed [what gymnasium is with @RyanWarnerCodes](https://clips.twitch.tv/PowerfulTenuousEggnogOMGScoots) on stream.  Very cool to see someone hop onto my stream and engage with the work I was doing 👍 

👋Thanks! 

If you have any questions about this process, please contact [_LilyHazel on Twitter](https://twitter.com/captcalli)

**Comment by mbifulco** [comment]
Had a great discussion with really nice guy in Bosnia last nigth about why he won't need a CS degree to find success as a developer - https://clips.twitch.tv/DeterminedPlausibleSquirrelPhilosoraptor

**Comment by LuckyNoS7evin** [comment]
Live Coder Intern - Nurturing Program - Acceptance

With The Live Coders growing rapidly the team introduced a minimum viewership and other criteria. 

- Interactivity
- Inclusivity
- Community
- Teaching
- Learning

You are invited to become a Live Coders Intern, not a part of the full Twitch team (some of the benefits are excluded) you will be invited to The Live Coders Discord server where you can learn from the rest of the team. (restricted access not all channels)

Please contact me to get your access

- @TheS7evin -> Twitter
- LuckyNoS7evin#0001 -> Discord
- LuckyNoS7evin -> Twitch
