### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by renodubois** [livecoders/Home#149]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/RenoInMO

**What languages / frameworks / tools do you program in while streaming on Twitch?**
React, React Native, JS/TS, GraphQL. Currently, I'm working on a React Native app that's a social media network focused around Board Games! It's my first foray into mobile dev, but it's been fun so far. I also have a few other random projects I'm working on, but currently trying to focus mostly on that.

**Why do you write code on stream?**
It keeps me accountable, I'm a big fan of learning in public, and I like being able to answer questions about the software industry in general!

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I don't have one in particular, but do really enjoy when I get to share info that I think I would have liked to hear when I was in college/just starting out!

**Comment by csharpfritz** [comment]
Welcome to the Live Coders!  Look for a Twitch team invite in your email.  Click through to accept that invite and we'll get you on our team mailing list and Discord
