### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by dakom** [livecoders/Home#15]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://www.twitch.tv/dakomz

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Rust
WebGL
WebAssembly
Typescript

**Why do you write code on stream?**
Honestly, mostly for selfish reasons - I can't yet justify doing Rust/WebGL at work so it's 100% spare time at the moment, and in order to motivate myself to get over the mountain it helps to have people watching me ;)

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Whenever someone actually interacts! Hasn't happened too often because my stuff is mostly live coding while *learning* - so it's less the kindof thing people will watch in order to gain new skills, more the kind of thing people will watch to support my struggle and/or learn with me at a beginner level

**Comment by dakom** [comment]
Just want to point out, since nuance gets lost in text, "selfish reasons" is tongue-in-cheek... I love teaching and thinking out loud and learning / getting feedback from other people. Very active on lots of forums, text channels, etc. but pretty new to Twitch

**Comment by csharpfritz** [comment]
We cannot accept your application at this time, as we look for team members to have Twitch Affiliate or Partner status.

Closing for now, but please re-open and apply when you reach Affiliate status
