### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by derrobin154** [livecoders/Home#151]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://www.twitch.tv/derrobin154/

**What languages / frameworks / tools do you program in while streaming on Twitch?**
- PHP
- little bit NodeJS
- Smarty Framework

**Why do you write code on stream?**
If I am already programming, others can at least take part, talk to me and help me with mistakes.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
If I have a mistake and a spectator can help me

If you have any questions about this process, please contact [_LilyHazel on Twitter](https://twitter.com/captcalli)

**Comment by LuckyNoS7evin** [comment]
No streams since April, seems to have stopped, can re-apply if they start streaming again
