### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by jongalloway** [livecoders/Home#152]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/jongalloway

**What languages / frameworks / tools do you program in while streaming on Twitch?**
ASP.NET Core
Blazor
Angular
Azure Functions

**Why do you write code on stream?**
I love learning together. I like to share what I know, but I've found it's even better to go a little beyond my comfort zone and work through a problem with my viewers. It's great to feel like we're all part of a team, and I'm just the facilitator.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I just happened to have the creator of RestSharp and Runscope watching my live stream, and they helped me debug a tricky typo in my request URL.

https://www.twitch.tv/videos/600066138

If you have any questions about this process, please contact [_LilyHazel on Twitter](https://twitter.com/captcalli)

**Comment by csharpfritz** [comment]
Look for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.
