### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by Bidthedog** [livecoders/Home#153]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/dnistream
https://www.dnistream.live

**What languages / frameworks / tools do you program in while streaming on Twitch?**
.Net Framework, .Net Core, Powershell, Docker, Docker-Compose, Git, HTML5, JavaScript, TypeScript, Angular, React, Vue.js, TDD, xUnit, Azure, Azure DevOps, GitHub, GitHub Actions, Github Packages, 

We (my co-host Josey and I) also do live vodcasts / podcasts with guests from the software industry.

**Why do you write code on stream?**
To teach people, build a community, catharsis and company. Both hosts work at home and like to learn new things :)

**What is your favorite moment from coding on stream?  Share a clip if one is available**
https://www.twitch.tv/videos/600071259

If you have any questions about this process, please contact [_LilyHazel on Twitter](https://twitter.com/captcalli)

Additional:

I am expecting to get back to regular daily coding streams again very shortly, but we stream regular, related content at least twice every week - and have done regularly for the past year. I've been holding off applying as I've not been able to turn affiliate on until yesterday (for a number of reasons!).

**Comment by LuckyNoS7evin** [comment]
Live Coder Intern - Nurturing Program - Acceptance

With The Live Coders growing rapidly the team introduced a minimum viewership and other criteria. 

- Interactivity
- Inclusivity
- Community
- Teaching
- Learning

You are invited to become a Live Coders Intern, not a part of the full Twitch team (some of the benefits are excluded) you will be invited to The Live Coders Discord server where you can learn from the rest of the team. (restricted access not all channels)

Please contact me to get your access

- @TheS7evin -> Twitter
- LuckyNoS7evin#0001 -> Discord
- LuckyNoS7evin -> Twitch
