### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by KobeLiesenborgs** [livecoders/Home#155]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/saintplaysthings

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Js, java, python, I also try to learn new frameworks/languages with the stream

**Why do you write code on stream?**
2 reasons: 
1. entertaining people and trying to teach them things left and right while at it
2. to improve myself and work on personal projects and things that interest me

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Any moments of appreciation from the chat, since I'm relatively new to streaming I don't have an absolute highlight clipped though.

If you have any questions about this process, please contact [_LilyHazel on Twitter](https://twitter.com/captcalli)

**Comment by csharpfritz** [comment]
Looks like you've got some fun projects and a great channel.  Welcome to the Live Coders!

You'll receive an email from Twitch with instructions to join the team, and then I'll whisper you a link to the team's private Discord for broadcasters on the team
