### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by ashleemboyer** [livecoders/Home#158]
**What is the URL for your Twitch channel?**
https://twitch.tv/ashleemboyer

**What languages / frameworks / tools do you program in while streaming on Twitch?**
I've used React so far, so a lot of HTML, CSS/SCSS, and JavaScript. I've also talked a little about Lighthouse, a tool for auditing accessibility.

**Why do you write code on stream?**
I've spent the last year writing and educating about web accessibility as a disabled developer. Live-streaming code has connected me to people in a totally different way than writing! I love that people can learn visually and ask questions live. Live coding is also something I've never done before and is helping me become a better coder.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I've only streamed code a couple of times, but during my first stream where I was walking through my "Build a React and Firebase Blog Site" series, a viewer chimed in with all sorts of suggestions and ideas. They really helped me improve the series and I loved the sense of community that came with a viewer engaging with my stream. Link to highlight [here](https://www.twitch.tv/videos/603613085).

**Comment by csharpfritz** [comment]
LOVE the accessibility work on stream!  We want to promote more inclusive experiences and communities.

Look for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.
