### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by Kruiser8** [livecoders/Home#159]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/kruiser8

**What languages / frameworks / tools do you program in while streaming on Twitch?**
(Iron)Python, HTML, CSS, JS

The main tool I've created is [Kruiz Control](https://github.com/Kruiser8/Kruiz-Control/).

**Why do you write code on stream?**
I love creating solutions to common streaming requests.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Discovering the reason some date code was broken: https://clips.twitch.tv/AmazingSpinelessCodFloof
Describing how some new code was setup: https://clips.twitch.tv/PricklyIcyLlamaShazBotstix
Showing off our channel point integration: https://clips.twitch.tv/SleepySlickAnaconda4Head

If you have any questions about this process, please contact [_LilyHazel on Twitter](https://twitter.com/captcalli)

**Comment by csharpfritz** [comment]
Welcome to the Live Coders!  Look for a Twitch team invite in your email.  Click through to accept that invite and we'll get you on our team mailing list and Discord
