### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by veronicageek** [livecoders/Home#160]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/veronicageek

**What languages / frameworks / tools do you program in while streaming on Twitch?**
- PowerShell
- WPF / XAML
- SharePoint
- Microsoft 365

**Why do you write code on stream?**
Share the How-To's when creating / building something, help others with their questions, and also get help from the viewers!  

**What is your favorite moment from coding on stream?  Share a clip if one is available**
When you get this interaction live with viewers, we all share a different experience or perspective on doing things.

If you have any questions about this process, please contact [_LilyHazel on Twitter](https://twitter.com/captcalli)

**Comment by csharpfritz** [comment]
So cool to see folks working with M365 and Sharepoint on stream!

Look for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.
