### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by cyberbarbie** [livecoders/Home#162]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/cyberbarbie

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Python! We'll also be covering Go and JavaScript in future streams :)
**Why do you write code on stream?**
The purpose of my channel is to make learning how to code accessible for everyone. So people see me struggle to understand certain coding challenges, make typos and errors often in my code and we've been collaborating on debugging and finding solutions to our bugs!

**What is your favorite moment from coding on stream?  Share a clip if one is available**
https://www.twitch.tv/cyberbarbie/clip/ColdbloodedTallGoblinFrankerZ

If you have any questions about this process, please contact [_LilyHazel on Twitter](https://twitter.com/captcalli)

**Comment by csharpfritz** [comment]
Good viewership, and keep up the streaming!  You've got a growing community.

Look for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.
