### ISSUE TITLE
Application For Membership

### ISSUE THREAD

**Issue by Simpathey** [livecoders/Home#164]
URL of my Twitch channel - Affiliate 
https://www.twitch.tv/simpathey

Languages and frameworks
I am using Visual Studio and Unity. My code is mostly C# although I know python as well. I also create game assets using Affinity Designer and Aseprite. I am doing game dev and releasing free to play games that are my own work. 

Why I write code on stream
I think that too many women and girls get the impression that they cant be computer scientists because they don't see them struggle. I have friends that hit a road block or bug while coding and figure they are not cut out for it. As a woman and an engineer I embrace the struggle and know that if your not struggling your probably not learning. I want to share that with other men and women who may be starting development. I am a very beginner level c# developer but I don't mind showing that I struggle. Also I am doing game development so I have been doing a challenge to spend at least 30 min a day dedicated to learning different game engines. 

My favorite Moment
I like my very first Sub as a game dev streamer. She subscribed and I was super surprised. I thanked her for supporting the game. She told me that there are not many women in game development and she was happy to know that we are out there. She is an aspiring game dev too, the moment just made me really happy!

**Comment by csharpfritz** [comment]
Great attitude towards streaming, and we feel the same way:  ANYONE can be a computer scientist, and we want to encourage women and underrepresented folks to have a great experience with technology.

Look for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.

**Comment by csharpfritz** [comment]
Checking in here...  I have sent an invite for you to join the team, and I hope you accept the invitation.  The invite arrives in your Twitch channel connected email account from Twitch with instructions to join the team
