### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by TTVHytheria** [livecoders/Home#165]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/hytheria

**What languages / frameworks / tools do you program in while streaming on Twitch?**
When I stream I mainly program with Python.

**Why do you write code on stream?**
I code on stream because I love when people come by and socialize with me and letting me know if I have any mistakes in my code or just to talk about it. When I receive feedback on my code, it helps me out because I want to become an outstanding programmer by the end of 2020.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
My favorite moment on stream was when people joined my stream and helped me with my code because there was a mistake in it, and then I received my very first donation with bits!

If you have any questions about this process, please contact [_LilyHazel on Twitter](https://twitter.com/captcalli)

**Comment by TTVHytheria** [comment]
I am a Twitch Affiliate

**Comment by TTVHytheria** [comment]
I have been streaming quite a bit. I recently turned on 'Store Past Broadcasts' so now it shows my recent broadcasts.

**Comment by LuckyNoS7evin** [comment]
Twitch channel no longer exists

**Comment by TTVHytheria** [comment]
New channel is CheckeredFlag or checkeredfiag. Sorry I made my application a while ago. I usually do racing and programming now. Vacation has been getting in the way of my streams but I’ll get back into streaming regularly fairly soon
