### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by SoWhoYou** [livecoders/Home#168]
**What is the URL for your Twitch channel?**  

[https://twitch.tv/sowhoyoudotcom](https://twitch.tv/SOWHOYOUdotCOM)

**What languages / frameworks / tools do you program in while streaming on Twitch?**  

**Languages:**  
PHP, JS, JAVA, Etc... What ever I feel like coding really, I use what I need when I need it.  
**Editors:**  
Visual Studio Code is probably the best editor ever, plugins are nice.  
**Tools:**  
OBS-Studio, with Custom Made Scripts to control things like my webcams.
[My Gaming/Coding Setup](https://www.sowhoyou.com/mypc/), because who codes on a laptop?

**Why do you write code on stream?**  

Because... Open Source is the way things should be, so why not stream the code.
Also because I made the first [Twitch Clip Command Script](https://www.sowhoyou.com/clipcommandscript/) while working at Streamlabs.
Which has since been discontinued, as I've turned that into the [Twitch Clip Command API](https://www.sowhoyou.com/clipcommand/).
Lastly... Because gaming is getting boring, coding is more fun and productive.

**What is your favorite moment from coding on stream?  Share a clip if one is available**  

One of my recent Drinking -n- Coding Streams, a [Twitch Staff member raided me with 16 viewers](https://www.twitch.tv/videos/608779730?t=03h58m54s).
LMFAO that was a funny stream. Drinking and Coding is rather fun, people enjoy my energy.
Though in reality, all my streams are my favorite moments, I just love talking to random people.

If you have any questions for me, please feel free to contact me via [clicking here](https://www.sowhoyou.com/contact/).

**Comment by SoWhoYou** [comment]
**NOTE:** I've been an affiliate for a long time, your bot just doesn't seem to wanna add that tag :(

**Comment by LuckyNoS7evin** [comment]
Unfortunately at this time did not meet the standard for becoming a live coder. Can discuss further privately if required
