### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by mastermndio** [livecoders/Home#169]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/mastermndio

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Python
Go
Rust
AWS
Docker
Terraform
BASH
K8s
JavaScript

**Why do you write code on stream?**
Tech can change lives so I want make sure everyone has access to it.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
One time I was streaming from my office, and I didn't know but there was another person streaming from there as well and someone notice. When he was done he did an in person raid on the channel

If you have any questions about this process, please contact [_LilyHazel on Twitter](https://twitter.com/captcalli)

**Comment by csharpfritz** [comment]
We've been watching your streams and were about to extend an invite....  HECK YES!

Keep an eye open for an invite email from Twitch.  Once accepted, I will whisper an invite to the team's private Discord server where we chat and collaborate.

Welcome to the team!
