### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by michael-hawker** [livecoders/Home#171]
**What is the URL for your Twitch channel?**
https://twitch.tv/XAMLLlama

**What languages / frameworks / tools do you program in while streaming on Twitch?**
C#/XAML, Windows Community Toolkit GitHub Management, Windows 10 Application Development

**Why do you write code on stream?**
I'm the maintainer for the [Windows Community Toolkit](https://aka.ms/wct). I work in the open on GitHub to help Windows 10 Developers; so I figured I might as well stream the work I'm doing there at the same time. 😊

It has been a great way to engage with our developer community and learn and grow together. It's been amazing doing some PR reviews on stream and having the developer who submitted the code right there!

I've always had an interest for technology, learning, and teaching! This has been a great way to explore all those passions at once.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Have a few:
- [Explaining a topic](https://www.twitch.tv/videos/576841402) this was a topic that came up and was able to take a quick break-out and explain it a high-level. [A different topic white-boarded later, on a more recent stream](https://www.twitch.tv/videos/609803158)
- [Engaging with PR Author](https://www.twitch.tv/videos/580302995?t=02h00m15s) from a PR review stream for the toolkit, the author was able to help me repro the issue to validate his PR. Fun moment 3 minutes in from the start when I realized the connection. 😊

I also come with a hat! 🦙❤

**Comment by csharpfritz** [comment]
Welcome to the Live Coders!  Look for a Twitch team invite in your email.  Click through to accept that invite and we'll get you on our team mailing list and Discord

**Comment by michael-hawker** [comment]
🎉🎉🎉 Awesome, thanks @csharpfritz! I look forward to being part of the team! 🦙❤

**Comment by csharpfritz** [comment]
Check your email, you should have a letter from Twitch with directions to join the team



Jeff
