### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by MarcusMann** [livecoders/Home#174]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/spacedevs

**What languages / frameworks / tools do you program in while streaming on Twitch?**
- Javascript
- Python
- Vuejs
- Reactjs
- SQL
- Mongo
- Docker

**Why do you write code on stream?**
In addition to learning from the public, I like to pass on all my knowledge.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
https://www.twitch.tv/videos/605741479

**Comment by csharpfritz** [comment]
Great channel!  Welcome to the Live Coders

You'll receive an email from Twitch with instructions to join the team.  Once you complete those steps, I will whisper you on Twitch with a link to join the team's private Discord.
