### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by victorialo** [livecoders/Home#181]
✓  Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
✓ Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/riallymundane
I also have a Twitter under the same name: http://twitter.com/riallymundane, as well as a Discord: https://discord.gg/U7xAfq8

**What languages / frameworks / tools do you program in while streaming on Twitch?**
JavaScript (maybe React as well in the future), HTML, CSS. Did Ruby once.
I was also considering learning Dart/Flutter at some point soon, maybe on stream!
Other languages I know but have not used on stream: Python, Go, Java, Perl, R.

**Why do you write code on stream?**
1) I LOVE interacting with viewers! Some of them are funny and I love hearing from people all over the world!
2) I honestly learn so much from my viewers + they also help me debug!
2) It motivates me to actually be productive and study for my coding interviews/make side projects!
3) I've found Twitch streaming to be super fun in general - the original premise for my channel was to do mundane (hence the "really mundane" username) things, but on stream, and I've found that anything and everything is way more fun when doing it while streaming!

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Here's one stream where I accomplished four coding interview questions in one stream: https://www.twitch.tv/videos/612642487
I loved the conversation people were having here about computation (Alan Turing) vs. informatics (Alonzo Church): full broadcast: https://www.twitch.tv/videos/618515380 - highlight: https://www.twitch.tv/videos/622377486
And clip from another stream where I got a HUGE RAID and 10 gifted subs and the raider was also super excited that I had a standing desk: https://www.twitch.tv/videos/622263757?collection=3GIM15RoDBauJA

Note 1: I was highly recommended to Livecoders by bWheatley, who is a current team member! I've also been praised by ShemicalX and KidQueb, who both raided me on a whim!
Note 2: I'd like to keep my real identity separate from Twitch and would like this application be hidden post-approval/rejection!

If you have any questions about this process, please email our Community Manager LilyHazel: lily@livecoders.dev

**Comment by csharpfritz** [comment]
Great content!  Welcome to the Live Coders!

You'll receive an email from Twitch with instructions to join the team and then I'll whisper you on Twitch with a link to the team's private Discord server for broadcasters.

I will hide this application after I close it
