### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by andremedeiros** [livecoders/Home#183]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/superdealloc

**What languages / frameworks / tools do you program in while streaming on Twitch?**
* Ruby / Ruby on Rails
* Golang
* Elm

**Why do you write code on stream?**
I enjoy the potential teaching aspect of it. I'm going to sit down and write the code anyway, but if I get to chat with people about it, answer questions, and make programming not seem like an unattainable thing.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I don't think I have a clip, but it was a moment where I was setting up a tree of things and was trying to calculate whether one of them was a root (not having an incoming connection from other elements.) Spent half an hour debugging until I realized that I was saving `root` as `false` and not `true` explicitly, in a vim split right in front of me.

If you have any questions about this process, please email our Community Manager LilyHazel: lily@livecoders.dev

**Comment by LuckyNoS7evin** [comment]
Live Coder Intern - Nurturing Program - Acceptance

With The Live Coders growing rapidly the team introduced a minimum viewership and other criteria. 

- Interactivity
- Inclusivity
- Community
- Teaching
- Learning

You are invited to become a Live Coders Intern, not a part of the full Twitch team (some of the benefits are excluded) you will be invited to The Live Coders Discord server where you can learn from the rest of the team. (restricted access not all channels)

Please contact me to get your access

- @TheS7evin -> Twitter
- LuckyNoS7evin#0001 -> Discord
- LuckyNoS7evin -> Twitch
