### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by pichangetheworld** [livecoders/Home#185]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

*Note that Paper Fan Games is composed of two people, piweyr and gengduck. piweyr is the developer and codes on stream every Thursday.

**What is the URL for your Twitch channel?**
https://twitch.tv/paperfangames

**What languages / frameworks / tools do you program in while streaming on Twitch?**
C# / Unity / Lucidchart (diagramming) / Paint.net

**Why do you write code on stream?**
It's fun! We get to interact with our viewers, show them what goes behind the scenes in gamedev, and we get tons of cool feedback for our game :)

**What is your favorite moment from coding on stream?  Share a clip if one is available**
It's difficult to just think of one... I've definitely had some moments where I was very stuck, and a clutch comment by our viewers saved me tons of headache. Here's us playtesting our game, and beautifully getting in each other's way 😂

https://clips.twitch.tv/SmokyCleanTurtleMingLee

If you have any questions about this process, please email our Community Manager LilyHazel: lily@livecoders.dev

**Comment by pichangetheworld** [comment]
The URL is correct (https://www.twitch.tv/paperfangames ) does it not work?

**Comment by LuckyNoS7evin** [comment]
Applications are currently not under review and will be back again in July.

Please bear with us at this time, the team are concentrating on The Live Coders Conference, Saturday 20th June. (yes this is a cheeky shoutout)

Thanks for your patience

**Comment by csharpfritz** [comment]
Welcome to the Live Coders!  Look for a Twitch team invite in your email.  Click through to accept that invite and we'll get you on our team mailing list and Discord
