### ISSUE TITLE
Application for Membership: Rosuav

### ISSUE THREAD

**Issue by Rosuav** [livecoders/Home#19]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/rosuav

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Python (incl Flask), Pike, JavaScript, SourcePawn, and whatever else comes up. I do game modding, Twitch tools (mainly my go-live tool "Mustard Mine" and my channel bot "StilleBot"), and various other things.

**Why do you write code on stream?**
Because I write code basically all the time, and it's fun to have people hanging out. Also, any time someone starts out with "oh, I don't understand any coding but that looks cool" and finishes up with "ahh, I get it now!!!", that's a gigantic win!

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Many MANY moments like this, where stuff works, then it doesn't, then it does again… and then we figure out why.
https://clips.twitch.tv/PoorSavageLorisHassaanChop
A lot of my VODs that list a game as their category are actually modding or game research streams. At least 2/3 of my streams will be coding related, with one per week guaranteed to be entirely programming.

Found this community via FierceKittenz, who is awesome.

**Comment by csharpfritz** [comment]
Looks great, and several recommendations.  Invite sent and look for a whisper from me on Twitch with an invite to the team Discord

**Comment by Rosuav** [comment]
Thank you!
