### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by aheil** [livecoders/Home#191]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/profaheil

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
yes (affiliate)

**What languages / frameworks / tools do you program in while streaming on Twitch?**
- .NET/.NET Core/C# mainly
- Docker, Ansible 
- Bash/Shell
- Others, if there they come in handy 
- Some tooling such as VS Code, GitLab, GitHub and so on

Streams are mainly in German, during winter term I will add software architecture streams in English as well.

**Why do you write code on stream?**
I am a professor for Software Engineering at Heilbronn University for Applied Sciences in Germany. I teach coding for a living for our Software Engineering Bachelors and Masters and I do this in my spare time online as well (well and right now due to Covid-19 of course). 

**What is your favorite moment from coding on stream?  Share a clip if one is available**
briefly describe
I have committed myself to a hardware project to build something online for my 3yo on stream (https://clips.twitch.tv/WealthyTastyPoxDxCat). 

If you have any questions about this process, please email our Community Manager LilyHazel: lily@livecoders.dev

**Comment by patrick-werner** [comment]
Great stream which i watch frequently. I am an alumni of the Heilbronn University and wish we had such high quality content back then.

**Comment by schrmh** [comment]
I support this application.

**Comment by Kirides** [comment]
very calm and charismatic german streamer.

**Comment by mmoch** [comment]
I consider this proposal to be worth supporting.

**Comment by tobiashoeft** [comment]
Support 100%! 

I've been watching him for refresh my skillz :-) Top! 

Thx Prof! :-)

**Comment by LuckyNoS7evin** [comment]
Applications are currently not under review and will be back again in July.

Please bear with us at this time, the team are concentrating on The Live Coders Conference, Saturday 20th June. (yes this is a cheeky shoutout)

Thanks for your patience

**Comment by csharpfritz** [comment]
Welcome to the Live Coders!  Look for a Twitch team invite in your email.  Click through to accept that invite and we'll get you on our team mailing list and Discord
