### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by jbnunn** [livecoders/Home#192]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/jbnunn

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Yes
**What languages / frameworks / tools do you program in while streaming on Twitch?**

## Languages
* Python, NodeJS, primarily. Sometimes I stream my dabbling in Wolfram Language, Go, and Swift.

## Frameworks/Tools
* VSCode is my go-to editor, but I do a lot via the terminal as well
* ML/DL Frameworks, like Tensroflow, Keras, MXNet, etc

**Why do you write code on stream?**
I write code for a living, and am passionate about showing that coders are NOT magical wizards that can effortlessly churn out perfect code: we get stumped, we make mistakes, we use StackOverflow, we use Google, and we might work hours just to push a few pixels around.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I have a lot of favorite moments! They're usually when I figure something out that's been stumping me. It's not the best example, but this one shows me trying to build a dashboard in Go (I'd really never used Go before) and getting somewhere: https://www.twitch.tv/videos/479176473?filter=highlights&sort=time

If you have any questions about this process, please email our Community Manager LilyHazel: lily@livecoders.dev

**Comment by LuckyNoS7evin** [comment]
Applications are currently not under review and will be back again in July.

Please bear with us at this time, the team are concentrating on The Live Coders Conference, Saturday 20th June. (yes this is a cheeky shoutout)

Thanks for your patience

**Comment by LuckyNoS7evin** [comment]
Live Coder Intern - Nurturing Program - Acceptance

With The Live Coders growing rapidly the team introduced a minimum viewership and other criteria. 

- Interactivity
- Inclusivity
- Community
- Teaching
- Learning

You are invited to become a Live Coders Intern, not a part of the full Twitch team (some of the benefits are excluded) you will be invited to The Live Coders Discord server where you can learn from the rest of the team. (restricted access not all channels)

Please contact me to get your access

- @TheS7evin -> Twitter
- LuckyNoS7evin#0001 -> Discord
- LuckyNoS7evin -> Twitch
