### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by Amokstakov** [livecoders/Home#194]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://www.twitch.tv/melkeydev

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Yes!

**What languages / frameworks / tools do you program in while streaming on Twitch?**
List briefly here
I currently develop in Javascript, using React. Creating a full stack NBA app using the MERN stack!
I am also a Data Scientist and plan to make future videos with Python

**Why do you write code on stream?**
I write code on stream to build and be apart of a community. Meeting people who smarter, and more talented than me and having them share their knowledge is a primary motivator for me to continue streaming and growing. 

**What is your favorite moment from coding on stream?  Share a clip if one is available**
briefly describe
Yeah, my twitch journey has been unbelievable so far. From getting raided by ThePrimeagen, to being gifted over 20 Tier 1 subs - I am incredibly grateful.
I still think its mind blowing when anyone subs to my channel. A clip can be seen of my exact reaction when someone subscribes to my channel haha
https://www.twitch.tv/melkeydev/clip/BrightTameTarsierSuperVinlin

If you have any questions about this process, please email our Community Manager LilyHazel: lily@livecoders.dev

**Comment by LuckyNoS7evin** [comment]
Applications are currently not under review and will be back again in July.

Please bear with us at this time, the team are concentrating on The Live Coders Conference, Saturday 20th June. (yes this is a cheeky shoutout)

Thanks for your patience

**Comment by csharpfritz** [comment]
Welcome to the Live Coders!  Look for a Twitch team invite in your email.  Click through to accept that invite and we'll get you on our team mailing list and Discord
