### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by ionixjunior** [livecoders/Home#195]
**What is the URL for your Twitch channel?**
https://twitch.tv/ionixjunior

**Are you a Twitch affiliate or partner?** 
Yes, I am an affiliate.

**What languages / frameworks / tools do you program in while streaming on Twitch?**
I currently develop mobile apps for Android and iOS using C# with Xamarin.

**Why do you write code on stream?**
I like to share knowledge. Write code during a live streaming is a good way to teach because the people can interact in the chat making questions or proposing some implementation. I very appreciate the engage of the audience and this motivates me to make more live streamings writing code.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
My favorite moment is when the audience is engaged during the live streaming and help each others and me during the development.

**Comment by LuckyNoS7evin** [comment]
Applications are currently not under review and will be back again in July.

Please bear with us at this time, the team are concentrating on The Live Coders Conference, Saturday 20th June. (yes this is a cheeky shoutout)

Thanks for your patience

**Comment by csharpfritz** [comment]
Welcome to the Live Coders!  Look for a Twitch team invite in your email.  Click through to accept that invite and we'll get you on our team mailing list and Discord
