### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by philnash** [livecoders/Home#198]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream. 👍
Also ensure that your vods are not sub only. 👍

**What is the URL for your Twitch channel?**
https://twitch.tv/phil_nash

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Yes, I am an affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
JavaScript and Ruby, sometimes (increasingly?) TypeScript.
I am happy working on both front-end and back-end, so have done some React on stream too. I have a project coming up that will likely be vanilla JS on the front-end.

**Why do you write code on stream?**
I initially started to write code on stream to give myself more of an opportunity to write code. Making time for it to happen with the camera on, where I can ignore my emails and social media, was a big draw. And getting to hang out with some people while I did it had an appeal too. But the community around my stream has grown (slowly) and it's become more than just writing code.

Throughout my career I've found I get as much enjoyment out of building projects as I have out of building community, teaching and sharing code. While a bunch of that has been writing or speaking, I've never quite felt as close as I have talking in person to the wonderful people who join my stream. It doesn't matter what the project is, we can just chat about what's going in development, in the world, or in our own lives. And sometimes someone chips in to help with the project or asks an interesting question. Overall we're making friends, learning together and sharing our experiences.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Having just written the above, I'm not sure I can pick one moment. Over the course of my live coding on stream there haven't been standout points, just an increasingly friendly set of people joining in to hang out. Sometimes it gets exciting when there's been a raid but when that calms down and a few more people stick around and come back to hang out another time that's when it really matters. Now I just look forward to the next moment I get to start a stream. As of writing this, it's 12 hours from now and I can't wait.

If you have any questions about this process, please email our Community Manager LilyHazel: lily@livecoders.dev

**Comment by GamesUKStudios** [comment]
how can i join the team Live Coders I use UE4

**Comment by philnash** [comment]
@GamesUKStudios I was going to point you to the page on applying, but it looks like you found it! Good luck in your application 😃

**Comment by csharpfritz** [comment]
We really like your content and would like to invite you to join the Live Coders!  Look for an invite from Twitch in your email.  Once that is received, I will send you a whisper on Twitch to join the team Discord where the team gathers to discuss tech and other streamer fun.

**Comment by philnash** [comment]
Thanks very much @csharpfritz and team!

**Comment by philnash** [comment]
Hey @csharpfritz, I don't think I got an invite to the Discord at all. Would love to join you all for a chat there! 🙂

**Comment by csharpfritz** [comment]
Sorry about that delay, I have whispered you the invite link on Twitch


Jeff

**Comment by philnash** [comment]
I'm in! 🎉 Thanks!
