### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by GamesUKStudios** [livecoders/Home#199]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/gamesukstudio

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
yes

**What languages / frameworks / tools do you program in while streaming on Twitch?**
use UE4 

**Why do you write code on stream?**
I sometimes do code online most of it is landscaping for my map and some is coding 

**What is your favorite moment from coding on stream?  Share a clip if one is available**
my favourite moment when coding online is then someone comes by and say's that is good code and they did not know that code 

If you have any questions about this process, please email our Community Manager LilyHazel: lily@livecoders.dev

**Comment by LuckyNoS7evin** [comment]
Applications are currently not under review and will be back again in July.

Please bear with us at this time, the team are concentrating on The Live Coders Conference, Saturday 20th June. (yes this is a cheeky shoutout)

Thanks for your patience

**Comment by LuckyNoS7evin** [comment]
channel supplied no longer exists

**Comment by GamesUKStudios** [comment]
hi sorry i changed my name https://www.twitch.tv/gamesukstudios

**Comment by LuckyNoS7evin** [comment]
@GamesUKStudios thanks for that, after further review, you're doing well just not quite on the minimum average viewer count. When you get to that point please feel free to reapply.
