### ISSUE TITLE
Application for Membership: ConnorwrightKappa

### ISSUE THREAD

**Issue by cxnky** [livecoders/Home#20]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/connorwrightkappa

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Java, Kotlin, Go, PHP and sometimes C#.

**Why do you write code on stream?**
For a project that I am working on in my free-time, which is a Discord bot

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Spending 20 mins debugging a PHP error only to realise that it was caused by a missing semi-colon

**Comment by csharpfritz** [comment]
I don't see much interacting with chat, and that's a key consideration for folks on our team - to encourage and help the technical community.

**Comment by cxnky** [comment]
That's mainly because most of my viewers lurk

**Comment by LuckyNoS7evin** [comment]
No past broadcasts

**Comment by cxnky** [comment]
I have past broadcasts... I don't store VODs as I play music.
