### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by ruby0x1** [livecoders/Home#200]
**What is the URL for your Twitch channel?**
https://twitch.tv/ruby0x1

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
yes

**What languages / frameworks / tools do you program in while streaming on Twitch?**
UE4, C++, Wren, luxe
https://wren.io (development on, and use of)
https://luxeengine.com (development on, and use of)

**Why do you write code on stream?**
I try to make tools to empower people, and sharing in their development aids that goal. Part of that is teaching others to make their own tools, as well!

**What is your favorite moment from coding on stream?  Share a clip if one is available**
People realizing there's no magic involved in making your own tools

**Comment by csharpfritz** [comment]
We really like your content and would like to invite you to join the Live Coders!  Look for an invite from Twitch in your email.  Once that is received, I will send you a whisper on Twitch to join the team Discord where the team gathers to discuss tech and other streamer fun.
