### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by thatonejason** [livecoders/Home#201]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/doctorargus

**Are you a Twitch affiliate or partner?** yes

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Unity C# - primarily focused on augmented and virtual reality

**Why do you write code on stream?**
I've always loved learning and I started coding (at 13) because I wanted to make video games. I put it off forever but do it now to scratch my own itch and to hopefully inspire folks to not dismiss their interests because they're too old/young, etc.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
My absolute favorite thing about streaming with Unity is the potential for unexpected, but interesting and fun things to happen. In this clip I'm working on creating a chat-powered overlay game in Unity, and chat had some fun. I was cracking up in this clip because of what happens.
https://www.twitch.tv/videos/535787508

If you have any questions about this process, please email our Community Manager LilyHazel: lily@livecoders.dev

**Comment by csharpfritz** [comment]
We really like your content and would like to invite you to join the Live Coders!  Look for an invite from Twitch in your email.  Once that is received, I will send you a whisper on Twitch to join the team Discord where the team gathers to discuss tech and other streamer fun.
