### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by IrishJohnGaming** [livecoders/Home#202]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/irishjohngaming

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Yes

**What languages / frameworks / tools do you program in while streaming on Twitch?**
C# / Unity3d mostly

**Why do you write code on stream?**
Yes - I share all code + game development on twitch.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
https://www.twitch.tv/irishjohngaming/clip/InventiveMoralCockroachUWot?filter=clips&range=7d&sort=time

If you have any questions about this process, please email our Community Manager LilyHazel: lily@livecoders.dev

**Comment by LuckyNoS7evin** [comment]
Applications are currently not under review and will be back again in July.

Please bear with us at this time, the team are concentrating on The Live Coders Conference, Saturday 20th June. (yes this is a cheeky shoutout)

Thanks for your patience

**Comment by mariusurbelis** [comment]
+1 for this man

**Comment by csharpfritz** [comment]
Welcome to the Live Coders!  Look for a Twitch team invite in your email.  Click through to accept that invite and we'll get you on our team mailing list and Discord
