### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by meldeleon** [livecoders/Home#203]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/juiceboxhero

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Yes, affiliate.

**What languages / frameworks / tools do you program in while streaming on Twitch?**
JS/React/Node

**Why do you write code on stream?**
I am a senior product manager who works at Twitch. In an effort to gain empathy for both the developers and streamers who use my platform, I have begun streaming my journey to learn react and interact with the Twitch API and dev tools provided by our company. It is my hope that building both Twitch-interfacing tools and a stream community will help me become a better product manager and able to create better experiences for our users.

I also do not profit from my stream, and donate an equal amount of money I would get from bits/subs to charity. I also run a tiltify campaign for charity every month in lieu of my donation button. I am the co-founder of a stream team that has made a pledge to not profit from their content and instead, give all their proceeds away to charity and the community: https://selflessstreaming.org/

**What is your favorite moment from coding on stream?  Share a clip if one is available**
That time I accidentally deleted my .gitignore file and a viewer stole my bot's OAuth key: https://clips.twitch.tv/PleasantElatedSashimiOSsloth

If you have any questions about this process, please email our Community Manager LilyHazel: lily@livecoders.dev

**Comment by csharpfritz** [comment]
We really like your content and would like to invite you to join the Live Coders!  Look for an invite from Twitch in your email.  Once that is received, I will send you a whisper on Twitch to join the team Discord where the team gathers to discuss tech and other streamer fun.
