### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by aahdee** [livecoders/Home#205]
**What is the URL for your Twitch channel?**
https://twitch.tv/cozycoding

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Yes, affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
p5.js (javascript) and Processing (java)

**Why do you write code on stream?**
I'm a Processing Foundation Fellow who's using streams to spread the word of p5.js and aiding beginners with the library. Thus I usually do simple/intermediate generative art on stream.  I like doing this a lot, so I plan to keep streaming after my fellowship is done. 

**What is your favorite moment from coding on stream?  Share a clip if one is available**
The time when I choked on a small sip of water (https://www.twitch.tv/cozycoding/clip/HungryBusyPlumGivePLZ) and when I get confused about the small differences between Processing and p5.js.

**Comment by csharpfritz** [comment]
We really like your content and would like to invite you to join the Live Coders!  Look for an invite from Twitch in your email.  Once that is received, I will send you a whisper on Twitch to join the team Discord where the team gathers to discuss tech and other streamer fun.
