### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by alexandrearc** [livecoders/Home#206]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/KempsAlex

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
C# with .Net Framework
Entity Framework
React Native
React
Angular

Tools:
Flipper
Visual Studio Code
Visual Studio 2019 for Mac
Insomnia 

**Why do you write code on stream?**
My main motivation to start coding on stream was to help developers to find motivation in coding and to motivate myself to code more often and learn new technologies. Also help Brazilian developers which suffers from lack of resources and up to date technical documentation.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
briefly describe
I do streams after putting my son to bed and i play some music for him to sleep. One night i forgot to change the music after start the stream and i won't figured out after 1 hour and 30 minutes of stream that was playing kids songs LOL (i did setup the music to be only for the stream..)
https://clips.twitch.tv/MushyDependableHerdGingerPower?tt_content=url&tt_medium=clips_api

If you have any questions about this process, please email our Community Manager LilyHazel: lily@livecoders.dev

**Comment by alexandrearc** [comment]
The url looks correct to me. Let me know if this is actually an issue. Thanks

**Comment by tiagombarbosa** [comment]
I support this application!

**Comment by paulosmlins** [comment]
I support this application!

**Comment by LuckyNoS7evin** [comment]
Applications are currently not under review and will be back again in July.

Please bear with us at this time, the team are concentrating on The Live Coders Conference, Saturday 20th June. (yes this is a cheeky shoutout)

Thanks for your patience

**Comment by alexandrearc** [comment]
Thanks for the update! I will be waiting.. 

Regards,
KempsAlex

**Comment by csharpfritz** [comment]
Welcome to the Live Coders!  Look for a Twitch team invite in your email.  Click through to accept that invite and we'll get you on our team mailing list and Discord
