### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by sthewissen** [livecoders/Home#207]
**What is the URL for your Twitch channel?**
https://twitch.tv/steventhewissen

**Are you a Twitch affiliate or partner?**
Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
.NET, mostly Xamarin but also venture on expeditions into the wonderful world of Azure. Tooling is mainly VS for Mac as that's the machine I'm on.

**Why do you write code on stream?**
The interaction with people on a live stream is where the added value is for me. I already build a lot of pet projects (build, not finish 😂), and streaming some of those efforts and learning new things along the way from people in chat help both me and the viewers to develop our skills further. The social skills gained from streaming also help me on a personal growth level. Streaming was one of the goals I set myself to get started with this year as a stepping stone to public speaking.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I don't have a specific interaction or moment in mind for this, as it's an assortment of things that I particularly enjoy. Whether it's being pointed towards better solutions for a problem I'm working on or just discovering something new that I didn't even know existed. It's that journey of exploration with my little community that's fascinating to go on each stream.

If you have any questions about this process, please email our Community Manager LilyHazel: lily@livecoders.dev

**Comment by csharpfritz** [comment]
We appreciate your interest, and are excited after seeing your first 6 streams.

We'd like to see your community grow over the next month before proceeding

**Comment by sthewissen** [comment]
I give it my best dear sir!

**Comment by csharpfritz** [comment]
Welcome to the Live Coders!  Look for a Twitch team invite in your email.  Click through to accept that invite and we'll get you on our team mailing list and Discord
