### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by Layla-P** [livecoders/Home#208]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/laylacodesit

**Are you a Twitch affiliate or partner?** yes

**What languages / frameworks / tools do you program in while streaming on Twitch?**
.NET
C#
Azure Functions
ASP.NET Core
C# for beginners

**Why do you write code on stream?**
I love teaching and streaming enables me to reach more people.
I used to run a meetup specialising in teaching C# to absolute beginners but we lost our venue. Twitch enables me to help people and reach a wider audience.
I also love to make code accessible to as many people as possible.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I like being silly. I waffle a lot - which is a very British thing to do! Here is an example of me having a chair party: https://www.twitch.tv/laylacodesit/clip/TriumphantPoliteFriseeEleGiggle?filter=clips&range=7d&sort=time
Just a taste of my silliness!
I enjoy a lot of my streams and would struggle to pull something in particular out :-)

If you have any questions about this process, please email our Community Manager LilyHazel: lily@livecoders.dev

**Comment by csharpfritz** [comment]
We really like your content and would like to invite you to join the Live Coders!  Look for an invite from Twitch in your email.  Once that is received, I will send you a whisper on Twitch to join the team Discord where the team gathers to discuss tech and other streamer fun.
