### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by Almantask** [livecoders/Home#209]
**What is the URL for your Twitch channel?**  
https://www.twitch.tv/kaisinnel

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)  
Yes, affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**  
C#, Visual Studio, xUnit, Kahoot, Google Slides, Draw.io (UML)

**Why do you write code on stream?**
I am passionate about Clean Code and best practices. I think I have a talent for explaining things in a simple way, therefore I spend a lot of time teaching. I like helping in the following ways:  
1) Teaching in C# Boot Camp: https://github.com/csinn/CSharp-From-Zero-To-Hero  
2) Doing mock job interviews  
3) Doing code reviews with my peers  
4) Having a small documentary experience for working on a charity project  (https://github.com/csinn/Painted-Prosthetics)  

**What is your favorite moment from coding on stream?  Share a clip if one is available**  
Unfortunately I don't have a Twitch clip, however I do have a YouTube video: https://youtu.be/wwnDtE6Z-ic?t=6389  
This was the first time I hosted a live kahoot to a C# classroom and people were quite happy about it :)

**Comment by csharpfritz** [comment]
We really like your content and would like to invite you to join the Live Coders!  Look for an invite from Twitch in your email.  Once that is received, I will send you a whisper on Twitch to join the team Discord where the team gathers to discuss tech and other streamer fun.
