### ISSUE TITLE
Application for Membership: andyonthewings

### ISSUE THREAD

**Issue by andyli** [livecoders/Home#21]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://www.twitch.tv/andyonthewings

**What languages / frameworks / tools do you program in while streaming on Twitch?**
I use Haxe. I mostly build Giffon.io with Haxe and Node (Express) during the stream. Sometimes also work on the CI for the Haxe Foundation repositories.

**Why do you write code on stream?**
I've just recently blogged about the reason :)
https://dev.to/andyli/how-i-stay-focused-when-working-at-home-live-streaming-myself-2dhi

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Answering career/programming questions from the viewers. I didn't clip anything, but maybe I should dig my recordings...

**Comment by csharpfritz** [comment]
We require team members to have affiliate or partner status. 

I like where you're going with the stream, and will re-evaluate once you have reached Affiliate status

**Comment by csharpfritz** [comment]
Still not affiliate status.  Closing and you can re-apply another time
