### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by PirateSoftware** [livecoders/Home#210]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/GoPirateSoftware

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Partner

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Game Maker: Studio
Been a professional programmer for 16 years so I have many other languages in my toolbelt.

**Why do you write code on stream?**
I work on all of my indie games live on stream to show viewers that making games is difficult yet accessible.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
This changes on a weekly basis honestly. I have a pretty massive community and they are constantly generating wacky content out of clips, absurd moments, or just pictures of my face. However, I think my favorite moment after going indie was the first fan cosplaying one of my characters.

If you have any questions about this process, please email our Community Manager LilyHazel: lily@livecoders.dev

**Comment by csharpfritz** [comment]
We really like your content and would like to invite you to join the Live Coders!  Look for an invite from Twitch in your email.  Once that is received, I will send you a whisper on Twitch to join the team Discord where the team gathers to discuss tech and other streamer fun.
