### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by jdotw** [livecoders/Home#211]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/jdotw

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Swift
Objective-C
Node.JS
React
And good ol' C for embedded / microprocessor work

**Why do you write code on stream?**
I've been writing software for 20 years and worked at Apple and AWS for 10 years. Now I want to give a whole lot back and help people gain confidence and capabilities. 

**What is your favorite moment from coding on stream?  Share a clip if one is available**
briefly describe
I think it was PixelogicDev and I geeking out about how there's something special about streaming and how it breaks down the 'perfect coder' myth that you can accidentally inherit from YouTube. Watching someone live helps you connect with them, as a real human, and you realize that there's no imposters -- least of all you -- and just a bunch of people making cool things. 

If you have any questions about this process, please email our Community Manager LilyHazel: lily@livecoders.dev

**Comment by LuckyNoS7evin** [comment]
Applications are currently not under review and will be back again in July.

Please bear with us at this time, the team are concentrating on The Live Coders Conference, Saturday 20th June. (yes this is a cheeky shoutout)

Thanks for your patience

**Comment by csharpfritz** [comment]
Welcome to the Live Coders!  Look for a Twitch team invite in your email.  Click through to accept that invite and we'll get you on our team mailing list and Discord
