### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by MattTheDev** [livecoders/Home#214]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/MattTheDev

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
.NET Core
C#
MVC
Javascript
Visual Studio / Visual Studio Code

**Why do you write code on stream?**
I've been a developer professionally for a decade now - and when I'm not mentoring/creating at the day job, I love to teach, code, and tinker at home. Nothing makes me happier than creating code, crushing bugs, and building an amazing community.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Any time that someone is able to teach me, help me through a piece of code, or suggest a different path of doing something is so super rewarding. For example - Tuples. These things are something I've known about .. but never used. Someone walked me through incorporating them into CouchBot, a product I often work on while streaming - and it helped cut down on some of the repeated code I knowingly and shamingly let sit in my code for WAY too long.

If you have any questions about this process, please email our Community Manager LilyHazel: lily@livecoders.dev

**Comment by LuckyNoS7evin** [comment]
Applications are currently not under review and will be back again in July.

Please bear with us at this time, the team are concentrating on The Live Coders Conference, Saturday 20th June. (yes this is a cheeky shoutout)

Thanks for your patience

**Comment by MattTheDev** [comment]
No worries! I'm not going anywhere :)
