### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by aslotte** [livecoders/Home#216]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://www.twitch.tv/alexslotte

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Yes - Twitch Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
- Machine Learning in .NET, specifically ML.NET
- C#/NET working on an open-source MLOps tool for ML.NET

**Why do you write code on stream?**
I love doing my part in building a vibrant developer community, and writing code while streaming is an excellent way to connect with others with the same interest and learn together. I'm specializing in a fairly niche field of Machine Learning in .NET using ML.NET, and prior to streaming I spoke a lot about the library and conferences, but wasn't able to connect with others with the same interest, or others that were interested but didn't know where to get started. After having started streaming I've discovered pockets of very dedicated people all around the world and together we've started forming the community we didn't have, which is an awesome feeling! 

It culminated in The Virtual ML.NET Community Conference we arranged at the end of May which was live-streamed on Twitch and viewed by 500 unique viewers: twitch.tv/virtualmlnet

**What is your favorite moment from coding on stream?  Share a clip if one is available**
My favorite moment is always when I get a great dialog going where people chime in with ideas and solution on a problem I'm trying to solve. 

**What do you want to accomplish with the Live Coders?**
Be part of an awesome team of like-minded people that all share the common interest of writing code on a stream that is accessible for people from all around the world from different demographics. 

**What do you want the Live Coders team to help you with?**
Act as a platform to raise awareness of Machine Learning in .NET using ML.NET to further build the community

If you have any questions about this process, please email: info@livecoders.dev

**Comment by LuckyNoS7evin** [comment]
Applications are currently not under review and will be back again in July.

Please bear with us at this time, the team are concentrating on The Live Coders Conference, Saturday 20th June. (yes this is a cheeky shoutout)

Thanks for your patience

**Comment by LuckyNoS7evin** [comment]
Live Coder Intern - Nurturing Program - Acceptance

With The Live Coders growing rapidly the team introduced a minimum viewership and other criteria. 

- Interactivity
- Inclusivity
- Community
- Teaching
- Learning

You are invited to become a Live Coders Intern, not a part of the full Twitch team (some of the benefits are excluded) you will be invited to The Live Coders Discord server where you can learn from the rest of the team. (restricted access not all channels)

Please contact me to get your access

- @TheS7evin -> Twitter
- LuckyNoS7evin#0001 -> Discord
- LuckyNoS7evin -> Twitch
