### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by accateo** [livecoders/Home#217]
**What is the URL for your Twitch channel?**
https://twitch.tv/accateo

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
At the moment PHP and NodeJS, but I'd like to stream also C,C++,HTML,CSS, jQuery,Java,JavaScript,Ajax,Python, C#,SQL,XML

**Why do you write code on stream?**
I have been streaming for a few months and, in addition to occasionally bringing some video games, I enjoy showing what I do at work. I am a computer engineer working in a robotics company. I mainly deal with coding and I love to deepen the languages I know and also to learn new ones!
Even my spare time is often occupied by extra activities that concern the world of coding (drones). Bringing my work / passion to Twitch also allows me to compare myself with other programmers and thus always learn something new. Just for information, in my github I've some little projects.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I do not have a particular time, but I like when I see that people still surprise of what I do with today's software. Some people who watch my live do not know anything about programming and seeing that they are starting to get passionate also makes me happy.

**What do you want to accomplish with the Live Coders?**
I think your community is made up of really passionate and competent people. You can see that what you do you like and can easily transmit it. For me, being part of it would be beautiful and very supportive.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by LuckyNoS7evin** [comment]
Applications are currently not under review and will be back again in July.

Please bear with us at this time, the team are concentrating on The Live Coders Conference, Saturday 20th June. (yes this is a cheeky shoutout)

Thanks for your patience

**Comment by LuckyNoS7evin** [comment]
We notice your content is mainly gaming content, please feel free to re-apply when you do more on the S&T side of things
