### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by bdougie** [livecoders/Home#218]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/bdougieYO

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
List briefly here
JavaScript/React
GitHub Actions

**Why do you write code on stream?**
briefly describe
I use streaming to work on open source projects.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I am new to clipping things so I don't have a ton, but on a recent stream, my viewers help me create a 404 page. 

https://clips.twitch.tv/SmallSpoopyHerdSquadGoals

To answer the question, my favorite moment was answering career questions for a couple of new University grads. It was nice to empathize with future junior devs.

**What do you want to accomplish with the Live Coders?**
briefly describe
Humanize open source contributions. Grow a community of devs that want to contribute to projects and support each other.

**What do you want the Live Coders team to help you with?**
briefly describe
Information about set up.
Tips on doing things like bots, emotes, moderation, etc.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by MichaelJolley** [comment]
@bdougie is an affiliate now.  +1 from me.

**Comment by LuckyNoS7evin** [comment]
Applications are currently not under review and will be back again in July.

Please bear with us at this time, the team are concentrating on The Live Coders Conference, Saturday 20th June. (yes this is a cheeky shoutout)

Thanks for your patience

**Comment by csharpfritz** [comment]
Welcome to the Live Coders!  Look for a Twitch team invite in your email.  Click through to accept that invite and we'll get you on our team mailing list and Discord
