### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by Zer0Lexaros** [livecoders/Home#219]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/Zer0Xeon

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
I am an Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Mostly HTML & CSS (With bootstrap)
VSCode
Bash(Zsh)
Learning various languages. Currently PHP, and JS (Node)

**Why do you write code on stream?**
Because I enjoy talking with others as I write and hearing suggestions from others about different ways of doing things.

**What is your favourite moment from coding on stream?  Share a clip if one is available**
When I have finished and everything works perfectly (or as close to perfect as i can get with my knowledge)

**What do you want to accomplish with the Live Coders?**
Become more skilled and more confident as well as make friends with other like minded people.

**What do you want the Live Coders team to help you with?**
Learning more skills to do with software and web development as I would like to become a freelancer for this one day, as well as helping me build my confidence as I still struggle to be myself on stream.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by LuckyNoS7evin** [comment]
Applications are currently not under review and will be back again in July.

Please bear with us at this time, the team are concentrating on The Live Coders Conference, Saturday 20th June. (yes this is a cheeky shoutout)

Thanks for your patience

**Comment by Zer0Lexaros** [comment]
Perfectly fine. Take as much time as is needed. I appreciate being informed.

**Comment by LuckyNoS7evin** [comment]
Live Coder Intern - Nurturing Program - Acceptance

With The Live Coders growing rapidly the team introduced a minimum viewership and other criteria. 

- Interactivity
- Inclusivity
- Community
- Teaching
- Learning

You are invited to become a Live Coders Intern, not a part of the full Twitch team (some of the benefits are excluded) you will be invited to The Live Coders Discord server where you can learn from the rest of the team. (restricted access not all channels)

Please contact me to get your access

- @TheS7evin -> Twitter
- LuckyNoS7evin#0001 -> Discord
- LuckyNoS7evin -> Twitch
