### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by krtschmr** [livecoders/Home#22]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/timvanmonero

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Ruby on Rails (exclusively)

**Why do you write code on stream?**
It keeps me focused. If i won't stream, i would probably do 5% coding and 95% pretending to code while playing games or reddit

**What is your favorite moment from coding on stream?  Share a clip if one is available**
maybe when i figure out to click the loginbutton when writing a testt for login? https://www.twitch.tv/timvanmonero/clip/GlutenFreePleasantAppleDatSheffy

**Comment by csharpfritz** [comment]
Great looking stream, invite extended!

Look for a Twitch whisper from me once you've joined the team and I'll invite you to the team Discord
