### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by ProfoundRice** [livecoders/Home#220]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/profoundrice

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
At the moment, working with C#/Unity and Javascript/Typescript/Node JS to build a Twitch integrated game. 

**Why do you write code on stream?**
To improve my confidence in coding, as well as to build a supportive community. I'm not the best coder, and I understand that. I also enjoy that improving my skills is another benefit to coding on stream. However, the main reason is to force myself to not feel like I have to be perfect, or I have to live up to everyone else's expectations of what I should be, or my skills should be, or my code should look like. Having my supportive community has helped with that, and I am slowly learning how to deal with negative criticism (i.e. not constructive at all, comments with only "your code is ugly") in a positive way for myself and my community. I hope to continue to stream coding, until I am able to confidently code and not feel anxious. 

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Twitch seems to have deleted it with the recent music mass deletion... But my favourite moment was when I got _super_ excited when the Unity game got the profile pictures of the people in chat, and displayed it in the game! Hopefully, the next exciting moment won't get lost >.< I love sharing those moments when things just _work_ with my community. Those moments, when the code does what I want it to, are my favourite coding moments ever 😄 

**What do you want to accomplish with the Live Coders?**
To be part of a support network and community. 

**What do you want the Live Coders team to help you with?**
To help support each other, and as a side benefit, hopefully feel more confident in myself, whether it's with streaming or with coding. 

If you have any questions about this process, please email: info@livecoders.dev

**Comment by LuckyNoS7evin** [comment]
Applications are currently not under review and will be back again in July.

Please bear with us at this time, the team are concentrating on The Live Coders Conference, Saturday 20th June. (yes this is a cheeky shoutout)

Thanks for your patience

**Comment by LuckyNoS7evin** [comment]
Live Coder Intern - Nurturing Program - Acceptance

With The Live Coders growing rapidly the team introduced a minimum viewership and other criteria. 

- Interactivity
- Inclusivity
- Community
- Teaching
- Learning

You are invited to become a Live Coders Intern, not a part of the full Twitch team (some of the benefits are excluded) you will be invited to The Live Coders Discord server where you can learn from the rest of the team. (restricted access not all channels)

Please contact me to get your access

- @TheS7evin -> Twitter
- LuckyNoS7evin#0001 -> Discord
- LuckyNoS7evin -> Twitch
