### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by florinpop17** [livecoders/Home#222]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/florinpop17

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Yes. I am a Twitch affiliate.

Note: I rejoined Twitch recently after streaming on YouTube for 5-6 months, so most of my content is there as of now. I’m planning to stream at least 2-3 times a week on Twitch (although I currently have my schedule for 5 times 😄).

**What languages / frameworks / tools do you program in while streaming on Twitch?**
HTML, CSS, JavaScript, React, TailwindCSS, NodeJS, Socket.io

**Why do you write code on stream?**
I like the engagement part. Being part of a community while building something is very enjoyable for me and I also get to help others learn how to code which is a huge plus.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I don’t recall one favorite moment but rather a collection of moments where we (me and the chat) managed to solve different coding problems and then having that feeling of “YES! We did it! 🤩”.

**What do you want to accomplish with the Live Coders?**
I’ve seen and heard good things about the community and I’d love to be a part of it to meet new people and have the chance to grow together the live coding industry.
I hope that one day live coding can be as big as gaming streams are now.

**What do you want the Live Coders team to help you with?**
My goal is to reach and help as many people as possible. If that could happen I’ll be very happy! 😃

If you have any questions about this process, please email: info@livecoders.dev

**Comment by LuckyNoS7evin** [comment]
Applications are currently not under review and will be back again in July.

Please bear with us at this time, the team are concentrating on The Live Coders Conference, Saturday 20th June. (yes this is a cheeky shoutout)

Thanks for your patience

**Comment by csharpfritz** [comment]
Welcome to the Live Coders!  Look for a Twitch team invite in your email.  Click through to accept that invite and we'll get you on our team mailing list and Discord

**Comment by florinpop17** [comment]
Thank you @csharpfritz! I'm looking forward to the links! (Not sure if I got any yet)
