### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by jh3y** [livecoders/Home#223]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/jh3yy

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Yes. Affiliate.

**What languages / frameworks / tools do you program in while streaming on Twitch?**
JavaScript, CSS, HTML, GreenSock, React, Figma, Inkscape, Vue, SVG, Animation, etc.

**Why do you write code on stream?**
I create a fair few demos online for CodePen, Twitter, etc. I always wanted to try streaming and then people started asking if I'd start to stream. I started and I really enjoy it. I like the interactive aspect of it. I also let users choose the direction of what I create in my scheduled stream. I put out a poll on the Monday and then start creating the winner on Friday. It's a great way for me to share the process as I turn up with an idea on Friday and there's little prep so viewers see the whole process from start to finish including brainstorming, design, etc. I also like to walk people through concepts when there are questions asked in chat.

In addition, I do spontaneous streams where I create interesting smaller demos.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I have many even in the short time I've started. Whether it be people helping me towards a solution or those breakthrough moments where I get something working. I tend to make things that aren't very common and push me so it can be a real challenge sometimes and viewers get to witness that breakthrough. With streaming it's a case of I'd be creating this and challenging myself anyway so I'm letting others see that process.

Most recent favorite moments I've clipped from this week's stream. One was getting my interactive chat commands working. People can fire air horns, animated corgis, and launch rockets from the chat: https://www.twitch.tv/videos/650843544. The other example from the stream is where I had a breakthrough in working out a way to animate an SVG mask over a live video: https://clips.twitch.tv/CourteousPlayfulClamCurseLit.

**What do you want to accomplish with the Live Coders?**

I imagine the main things are to network with the team and expand my audience. I want to make a success of my streaming and to do that I need a larger audience. My audience is growing and I love creating content for people and helping them.

But to be a member will help me with meeting new people that are very knowledgeable in broadcasting and how to make a success of it. I have plenty of content ideas and the feedback I have is that people enjoy seeing the things I make as it's a little different.

But, I think I can do better when it comes to streaming the process. Whether that's a case of doing more smaller streams, production quality changes, etc.

**What do you want the Live Coders team to help you with?**
In general, tips for improving my stream to expand my audience. Likewise, in the other direction, if there are things I can help other members/the team with, that would be awesome.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by LuckyNoS7evin** [comment]
Applications are currently not under review and will be back again in July.

Please bear with us at this time, the team are concentrating on The Live Coders Conference, Saturday 20th June. (yes this is a cheeky shoutout)

Thanks for your patience

**Comment by LuckyNoS7evin** [comment]
Live Coder Intern - Nurturing Program - Acceptance

With The Live Coders growing rapidly the team introduced a minimum viewership and other criteria. 

- Interactivity
- Inclusivity
- Community
- Teaching
- Learning

You are invited to become a Live Coders Intern, not a part of the full Twitch team (some of the benefits are excluded) you will be invited to The Live Coders Discord server where you can learn from the rest of the team. (restricted access not all channels)

Please contact me to get your access

- @TheS7evin -> Twitter
- LuckyNoS7evin#0001 -> Discord
- LuckyNoS7evin -> Twitch
