### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by tnarla** [livecoders/Home#225]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/mewtru

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no) 
Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Typescript/ React/ Sockets/ Python

**Why do you write code on stream?**
One of my friends started and he said it was really fun and the couple of viewers he had helped him debug. I've been streaming before on and off but mostly games so I wanted to try out programming and so far it's been a blast :D! 

**What is your favorite moment from coding on stream?  Share a clip if one is available**
When we raised over $3000 for Color of Change :)! It was super fun, a bunch of us streamers were doing a code in the dark challenge where we write html/css but don't look at the site until the end of the 30 minutes. It was such a good stream and I'm so glad we raised money for a good cause :)! VOD: https://www.twitch.tv/videos/641530777

**What do you want to accomplish with the Live Coders?**
I've met a bunch of the people in Live Coders through raids, etc. I would love to continue to grow my channel and get more involved in this awesome community :)! Everyone's been so kind and it's been incredibly fun so far this past month!

**What do you want the Live Coders team to help you with?**
Honestly, I've just recently started and my setup and Twitch knowledge is lacking haha. I just recently learned about Pog and Monkas... I'd love to just make friends who are doing similar things and learn from them :)! 

If you have any questions about this process, please email: info@livecoders.dev

**Comment by LuckyNoS7evin** [comment]
Applications are currently not under review and will be back again in July.

Please bear with us at this time, the team are concentrating on The Live Coders Conference, Saturday 20th June. (yes this is a cheeky shoutout)

Thanks for your patience

**Comment by csharpfritz** [comment]
Welcome to the Live Coders!  Look for a Twitch team invite in your email.  Click through to accept that invite and we'll get you on our team mailing list and Discord
