### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by jaysonjphillips** [livecoders/Home#226]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream. Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/its_jay_phillz

**Are you a Twitch affiliate or partner?** YES  [Affiliate]

**What languages / frameworks / tools do you program in while streaming on Twitch?**  Typescript, Javascript, Go (soon), React, PostgreSQL, MongoDB (soon), Python. 

**Why do you write code on stream?**
I'm a Director of Engineering by day, and an online (and offline) bootcamp instructor at UC Berkeley & U Denver by evening (Fullstack Web Development and Data Visualizations/Intro to ML). I don't have a CS degree (or degree at all). My goal for streaming is to empower career switchers, early learners and Junior to Mid level engineers to grow. I also want to humanize the other elements of programming: making errors, bugfixes, problem solving, having fun and not having to be some sort of 5 year old kid prodigy at programming to be successful. 

**What is your favorite moment from coding on stream?  
Share a clip if one is available**
Refactoring our channel bot program and having the chat be able to control my lights via commands was a great moment, because of all the errors and challenges I had in scaling up my familiarity with Typescript (which I learned live on stream as we have been building our bot).

**What do you want to accomplish with the Live Coders?**
I want to further establish community and link the communities I've been able to join and build: bootcamp alumni, non-traditional career path engineers, career switchers and more. I also want to establish a different branch of growth and expertise within my career path by adopting live streaming, which appeals to me more than the other approaches (e.g. creating blog posts). 

**What do you want the Live Coders team to help you with?**
Community, outreach and becoming a better _live streamer_. I've been able to make acquaintance with a few Live Coder team members and I've really enjoyed the approach of team members to build inclusive, educational, experimental communities with moments of levity built in. I'd love to expand on my existing skill set by doing so. 

If you have any questions about this process, please email: info@livecoders.dev

**Comment by LuckyNoS7evin** [comment]
Applications are currently not under review and will be back again in July.

Please bear with us at this time, the team are concentrating on The Live Coders Conference, Saturday 20th June. (yes this is a cheeky shoutout)

Thanks for your patience

**Comment by csharpfritz** [comment]
Welcome to the Live Coders!  Look for a Twitch team invite in your email.  Click through to accept that invite and we'll get you on our team mailing list and Discord
