### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by spajus** [livecoders/Home#227]
**What is the URL for your Twitch channel?**
https://twitch.tv/dev_spajus

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)

Yes (affiliate)

**What languages / frameworks / tools do you program in while streaming on Twitch?**

Mostly C# (Unity)

**Why do you write code on stream?**

Doing live indie game development

**What is your favorite moment from coding on stream?  Share a clip if one is available**

Getting unexpected things to happen, like a [lightning strike nearby](https://www.twitch.tv/videos/647820380)

**What do you want to accomplish with the Live Coders?**

Share the knowledge and get more people to visit my "virtual office"

**What do you want the Live Coders team to help you with?**

Growth on Twitch

**Comment by LuckyNoS7evin** [comment]
Applications are currently not under review and will be back again in July.

Please bear with us at this time, the team are concentrating on The Live Coders Conference, Saturday 20th June. (yes this is a cheeky shoutout)

Thanks for your patience

**Comment by LuckyNoS7evin** [comment]
Live Coder Intern - Nurturing Program - Acceptance

With The Live Coders growing rapidly the team introduced a minimum viewership and other criteria. 

- Interactivity
- Inclusivity
- Community
- Teaching
- Learning

You are invited to become a Live Coders Intern, not a part of the full Twitch team (some of the benefits are excluded) you will be invited to The Live Coders Discord server where you can learn from the rest of the team. (restricted access not all channels)

Please contact me to get your access

- @TheS7evin -> Twitter
- LuckyNoS7evin#0001 -> Discord
- LuckyNoS7evin -> Twitch
