### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by SuavePirate** [livecoders/Home#228]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/suave_pirate
all past vods are also automatically exported to my YT channel: https://www.youtube.com/playlist?list=PLIyXOPxAPnYuCv-yUffZb4L9olMRzB1OV

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)

Yes - affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
- .NET
- Azure
- AWS
- TypeScript
- Kotlin
- Xamarin
- Alexa
- Bixby
- Google Assistant
- Arduino
- React

Definitely tinkering with just about everything though.

**Why do you write code on stream?**
I've always loved building and teaching. My bio for the last 6 or so years has been "Building cool stuff and teaching people along the way". I hadn't started live streaming until recently simply because I didn't have the time, but then I did some guest work on a few other streams and did some virtual conferences and just fell in love with it.

The main focus of what I build on stream is also why I do it. My focus is on building really cool and innovative technology that helps others and makes lives easier while trying to have fun along the way. I think that is the best part about technology in general.

As an example, we've built two projects so far on stream in the last couple weeks:

- **Find My Rep** - virtual assistant to let people get in touch with their elected officials from any channel they can including Alexa, Google Assistant, Bixby, web chat, slack, teams, and more.
- **Warzone Voice Controller** - an initial prototype for a much larger project to build a more accessible keyboard/mouse/controller that can be accessed and used via Voice, or distributed chat. For now, we built it specifically for Call of Duty to let me use Alexa or Google assistant to control the character and even let twitch chat send commands to control my operator all at once.

**What is your favorite moment from coding on stream?  Share a clip if one is available**

The biggest moment for me was seeing the final output of our Warzone Voice Controller and using it in-game. We used Alexa to actually play the game and chat had a great time trying to mess me up. The whole thing is this beautiful system combining:

- Alexa Skill in ASP.NET on Azure
- SignalR sending info from the skill to a UWP client running on my desktop
- UWP Client sending commands over Serial connection to an Arduino Leonardo
- The arduino sending keyboard commands back to the desktop which actually performs actions in the game
- AND a twitch bot running locally over IRC connection to the chat and sending commands up to the ASP.NET API and back down to UWP->Arduino->Keyboard commands as well

Here's the full vod, and a highlight of the output. **Warning: Video game violence**

Full vod - https://www.youtube.com/watch?v=x8eteSh4_DM
Output highlight - https://www.youtube.com/watch?v=-zNTulqSmsM&t=335s

**What do you want to accomplish with the Live Coders?**
In joining a team like Live Coders, my main goals are to:

- Reach and inspire more people to do good with technology
- Teach more people how to build great software with craftsmanship in mind
- Learn how to do a better job at reaching and participating in the community

**What do you want the Live Coders team to help you with?**

- More collaborations with other streamers
- Help with understanding how to build a stronger community around the stream

If you have any questions about this process, please email: info@livecoders.dev

**Comment by dansiegel** [comment]
this is a great channel and would make an excellent addition to the team

**Comment by SuavePirate** [comment]
Thank you Dan!

**Comment by LuckyNoS7evin** [comment]
Applications are currently not under review and will be back again in July.

Please bear with us at this time, the team are concentrating on The Live Coders Conference, Saturday 20th June. (yes this is a cheeky shoutout)

Thanks for your patience

**Comment by SuavePirate** [comment]
No worries at all! The conference was awesome by the way! (yes this is is a cheeky suck-up <3)

**Comment by LuckyNoS7evin** [comment]
Live Coder Intern - Nurturing Program - Acceptance

With The Live Coders growing rapidly the team introduced a minimum viewership and other criteria. 

- Interactivity
- Inclusivity
- Community
- Teaching
- Learning

You are invited to become a Live Coders Intern, not a part of the full Twitch team (some of the benefits are excluded) you will be invited to The Live Coders Discord server where you can learn from the rest of the team. (restricted access not all channels)

Please contact me to get your access

- @TheS7evin -> Twitter
- LuckyNoS7evin#0001 -> Discord
- LuckyNoS7evin -> Twitch
