### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by crazy4pi314** [livecoders/Home#229]
**What is the URL for your Twitch channel?**
https://twitch.tv/crazy4pi314

**Are you a Twitch affiliate or partner?** 
Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
 Q#, Python, C#, GitHub, VS Code, Jupyter Notebooks

**Why do you write code on stream?**
My goal in livestreaming working on open source quantum software is to show the community what that looks like. There is a lot of stigma and gatekeeping around quantum technologies so I want to be able to show people that they _can_ be a quantum developer with many of the skills they already have! Also, I am working on learning new languages myself so I enjoy the experience of pair programming with chat 😄 

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I always enjoy (and so does my dog) when viewers spend bits to give my pup a treat, but I also really enjoy when interactions with chat help us all learn.  I get most excited when because of my stream folks try out writing quantum programs themselves like this: https://www.twitch.tv/videos/653918562

**What do you want to accomplish with the Live Coders?**
I want to help represent a new and growing developer community for quantum technologies. I can help both teach folks about quantum computing technologies and work together with the viewers to develop quantum programs and applications!

**What do you want the Live Coders team to help you with?**
I want to learn how to better leverage the twitch platform,  and what are best livecoding practices :)

If you have any questions about this process, please email: info@livecoders.dev

**Comment by LuckyNoS7evin** [comment]
Applications are currently not under review and will be back again in July.

Please bear with us at this time, the team are concentrating on The Live Coders Conference, Saturday 20th June. (yes this is a cheeky shoutout)

Thanks for your patience

**Comment by crazy4pi314** [comment]
It was a great event, hope y'all have a nice break after 💕

**Comment by csharpfritz** [comment]
Welcome to the Live Coders!  Look for a Twitch team invite in your email.  Click through to accept that invite and we'll get you on our team mailing list and Discord
