### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by RelevantJesse** [livecoders/Home#23]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/RelevantJesse

**What languages / frameworks / tools do you program in while streaming on Twitch?**
During the day, I do C#/WinForms/SQL. In the evenings, I'm working on a project for beginners using C# MVC .NET Core with Entity Framework.

**Why do you write code on stream?**
I love helping others get into programming. It inspires me seeing others accomplish their goals and make their dreams come true.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Not sure if I have one specific moment. I love interacting with my viewers, so when I see someone return back to the stream, ask how my surgery went or anything like that that shows they enjoy my content, that motivates me to keep going.

**Comment by krtschmr** [comment]
i watch him sometimes. he's relevant! ;)

**Comment by csharpfritz** [comment]
Great looking stream!  Invite extended. 

Look for a Twitch whisper from me with an invite to the team Discord
