### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by Static-Flow** [livecoders/Home#230]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/codingwithstaticflow

**Are you a Twitch affiliate or partner?** yes

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Golang / Goland
Python / Pycharm
Java / Intellij
Html - Javascript / Webstorm

**Why do you write code on stream?**
I build tooling for the cyber security space and there seemed to be a lacking in the live coding space around that type of development. I was already building these tools for the community so I figured why not stream the process to demystify how these tools are built!

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I sadly don't have a clip of it but I built a new feature that allowed for viewing streaming output and everyone in the stream was really pumped to see it working!

**What do you want to accomplish with the Live Coders?**
I'd like to bring a new type of development to the community and showcase a niche of tools and software that might not get as much attention. It's a highly consumed type of software but not often shown in development.

**What do you want the Live Coders team to help you with?**
I would love to get feedback on the stream as a whole, along with learning from the great streamers in this community on how to build up the stream and take it to the next level!

**Comment by LuckyNoS7evin** [comment]
Applications are currently not under review and will be back again in July.

Please bear with us at this time, the team are concentrating on The Live Coders Conference, Saturday 20th June. (yes this is a cheeky shoutout)

Thanks for your patience

**Comment by LuckyNoS7evin** [comment]
Live Coder Intern - Nurturing Program - Acceptance

With The Live Coders growing rapidly the team introduced a minimum viewership and other criteria. 

- Interactivity
- Inclusivity
- Community
- Teaching
- Learning

You are invited to become a Live Coders Intern, not a part of the full Twitch team (some of the benefits are excluded) you will be invited to The Live Coders Discord server where you can learn from the rest of the team. (restricted access not all channels)

Please contact me to get your access

- @TheS7evin -> Twitter
- LuckyNoS7evin#0001 -> Discord
- LuckyNoS7evin -> Twitch
