### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by grsoares21** [livecoders/Home#231]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://www.twitch.tv/grsoares

**Are you a Twitch affiliate or partner?** Yes

**What languages / frameworks / tools do you program in while streaming on Twitch?**
- TypeScript
- React.js
- Next.js
- Node.js
- D3.js

**Why do you write code on stream?**
I started once I learned about the #LearnInPublic trend and decided to give it a try. Since then I've been hooked. I'm way more productive than before, I'm finally dedicating time to the projects I've always wanted to do, I'm acquiring huge amounts of knowledge and I love interacting with the chat while doing all of this. I'm also very glad to be a part of the amazing Brazilian community of live-coders, one of the most welcoming communities I've ever encountered.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
When I got raided by marcobrunodev for the first time. He's a reference on the Brazilian community of live coders and when this happened I felt as if I had officially become a part of the community. I've created a clip for this moment https://www.twitch.tv/videos/655212779

**What do you want to accomplish with the Live Coders?**
I want to help however I can to grow the community of coders on Twitch, especially the portuguese-speaking community. I believe Twitch can become one of the main hubs for developers and aspiring developers to teach, learn, network, and just have a good time.

**What do you want the Live Coders team to help you with?**
I'm still a beginner on streaming and I would love to learn from people that are more experienced than me. Both on technical subjects such as how to set-up a stream as well as on soft-skills such as how to make an audience feel welcome and interact.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by LuckyNoS7evin** [comment]
Applications are currently not under review and will be back again in July.

Please bear with us at this time, the team are concentrating on The Live Coders Conference, Saturday 20th June. (yes this is a cheeky shoutout)

Thanks for your patience

**Comment by csharpfritz** [comment]
Welcome to the Live Coders!  Look for a Twitch team invite in your email.  Click through to accept that invite and we'll get you on our team mailing list and Discord
