### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by erikstmartin** [livecoders/Home#232]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vids are not sub only.

**What is the URL for your Twitch channel?**
https://www.twitch.tv/erikdotdev

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
yes

**What languages / frameworks / tools do you program in while streaming on Twitch?**
List briefly here
Go, Rust, Docker, Kubernetes, JavaScript

**Why do you write code on stream?**
briefly describe
I enjoy interacting with the community. I also enjoy teaching as well as learning from others. I have been a Developer Advocate for the past 3 years.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
briefly describe

I surprisingly enjoy when errors come up. It usually creates embarrassing but also amusing moments and fun dialog with viewers.

**What do you want to accomplish with the Live Coders?**
briefly describe

I would like to connect and network with other live coders and learn from their experiences. I'd also like to reach a broader audience. This will help make the content I create more engaging, as well as more relevant to the interest of viewers.

**What do you want the Live Coders team to help you with?**
briefly describe

It seems discoverability via organic traffic on Twitch is hard for developers, with the primary audience being gamers. Most of the people I watch live code are from the Live Coders team.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by LuckyNoS7evin** [comment]
Applications are currently not under review and will be back again in July.

Please bear with us at this time, the team are concentrating on The Live Coders Conference, Saturday 20th June. (yes this is a cheeky shoutout)

Thanks for your patience

**Comment by csharpfritz** [comment]
Welcome to the Live Coders!  Look for a Twitch team invite in your email.  Click through to accept that invite and we'll get you on our team mailing list and Discord
