### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by DRSchlaubi** [livecoders/Home#233]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also, ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/schlauhibi

**Are you a Twitch affiliate or partner?**
Yes

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Languages:
- Dart
- Kotlin
- Java
Frameworks:
- Flutter
- Ktor
Tools:
- IntelliJ IDEA
- VS Code
- Gitkraken

**Why do you write code on stream?**
I was always watching Coding streams because it was very entertaining for me. But recently some friends (Shoutout to @NiggelGame) told me to start making programming streams myself and it was a lot of fun for me, also I can motivate and help other people or get help from other people. Most people in the Twitch community are very helpful, that makes me have a good feeling while doing streams

**What is your favorite moment from coding on stream?**
When someone in the chat tells me something I didn't know. It's always great to learn something new

**What do you want to accomplish with the Live Coders?**
They're not that many people in Germany which stream in that category, so it's always hard to start, so hopefully being part of a Network of coders will help me to get better at what I do

**What do you want the Live Coders team to help you with?**
I only started streaming regularly recently so the members of Live coders probably have some tips for me how I can make my streams better

If you have any questions about this process, please email: info@livecoders.dev

**Comment by LuckyNoS7evin** [comment]
Applications are currently not under review and will be back again in July.

Please bear with us at this time, the team are concentrating on The Live Coders Conference, Saturday 20th June. (yes this is a cheeky shoutout)

Thanks for your patience

**Comment by LuckyNoS7evin** [comment]
Live Coder Intern - Nurturing Program - Acceptance

With The Live Coders growing rapidly the team introduced a minimum viewership and other criteria. 

- Interactivity
- Inclusivity
- Community
- Teaching
- Learning

You are invited to become a Live Coders Intern, not a part of the full Twitch team (some of the benefits are excluded) you will be invited to The Live Coders Discord server where you can learn from the rest of the team. (restricted access not all channels)

Please contact me to get your access

- @TheS7evin -> Twitter
- LuckyNoS7evin#0001 -> Discord
- LuckyNoS7evin -> Twitch
