### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by timClicks** [livecoders/Home#234]
**What is the URL for your Twitch channel?**
https://twitch.tv/timClicks

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Yes

**What languages / frameworks / tools do you program in while streaming on Twitch?**

- Rust
- Creative coding 
- VS Code
- Linux, esp. Ubuntu

Over time, I'll add WebAssembly, Python and machine learning/AI to the mix.

**Why do you write code on stream?**
I really love to share. It's a great way to teach (while learning!). It's also technically challenging and is a great way for me to extend my own skills.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
- https://www.twitch.tv/timclicks/clip/OddDaintyAirGuitarKreygasm
- Really enjoyed getting a Mandelbrot set up on screen!  https://www.youtube.com/watch?v=xDrAncijBq4

**What do you want to accomplish with the Live Coders?**
Join a community of streamers of technical content (rather than gaming) to strengthen my presence and improve the experience for the audience.

**What do you want the Live Coders team to help you with?**
Sharpening things up, mostly. Curious to learn more about what the perks of membership might be.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by LuckyNoS7evin** [comment]
Live Coder Intern - Nurturing Program - Acceptance

With The Live Coders growing rapidly the team introduced a minimum viewership and other criteria. 

- Interactivity
- Inclusivity
- Community
- Teaching
- Learning

You are invited to become a Live Coders Intern, not a part of the full Twitch team (some of the benefits are excluded) you will be invited to The Live Coders Discord server where you can learn from the rest of the team. (restricted access not all channels)

Please contact me to get your access

- @TheS7evin -> Twitter
- LuckyNoS7evin#0001 -> Discord
- LuckyNoS7evin -> Twitch
