### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by FrankFlamme** [livecoders/Home#237]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://www.twitch.tv/jeanvaljean80

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Yes, I'm a Twitch affiliate.

**What languages / frameworks / tools do you program in while streaming on Twitch?**
C#, Blazor, ASP. NET Core MVC, Razor Pages, Unity

**Why do you write code on stream?**
I've been developing software since 25 years and I think it's awesome to learn from others, exchange ideas or teach other people about software development. I'm always glad to answer questions of the audience during live coding and I think Twitch is a great platform for this.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I have no clip actually but favourite moments of my stream are, if the community is interested in what I'm doing and if I can help other people with questions to software development.

**What do you want to accomplish with the Live Coders?**
Get more in touch with other Live Coders, do some cool networking stuff and learn from other Live Coders experiences.

**What do you want the Live Coders team to help you with?**
Reaching a broader audience, getting feedback from the professionals of the Live Coders team and do great coding work together. :-)

If you have any questions about this process, please email: info@livecoders.dev

**Comment by LuckyNoS7evin** [comment]
Live Coder Intern - Nurturing Program - Acceptance

With The Live Coders growing rapidly the team introduced a minimum viewership and other criteria. 

- Interactivity
- Inclusivity
- Community
- Teaching
- Learning

You are invited to become a Live Coders Intern, not a part of the full Twitch team (some of the benefits are excluded) you will be invited to The Live Coders Discord server where you can learn from the rest of the team. (restricted access not all channels)

Please contact me to get your access

- @TheS7evin -> Twitter
- LuckyNoS7evin#0001 -> Discord
- LuckyNoS7evin -> Twitch
