### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by JosephDanielBartley** [livecoders/Home#238]
**What is the URL for your Twitch channel?**
https://twitch.tv/jodaba

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
- Node
- TypeScript
- Angular
- C#
- Unity

Hoping to add React, .NET Core, Arduino stuff, and more 

**Why do you write code on stream?**
I am currently unemployed and revamping my online presence and portfolio so I figured I might as well stream it and meet new people. The S&T category on Twitch is an amazing community so I want to immerse myself in it more. It's the best way to learn more 

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I can't choose because these moments happen all of the time. Any time someone comes in and asks for help and I can answer a question or help someone reach the next step in their development journey is what makes me feel great. 

**What do you want to accomplish with the Live Coders?**
I want to immerse myself into the team and share all of my knowledge with others as much as possible. 

**What do you want the Live Coders team to help you with?**
I want to meet more people, share knowledge, collaborate and try new things.

**Comment by LuckyNoS7evin** [comment]
Live Coder Intern - Nurturing Program - Acceptance

With The Live Coders growing rapidly the team introduced a minimum viewership and other criteria. 

- Interactivity
- Inclusivity
- Community
- Teaching
- Learning

You are invited to become a Live Coders Intern, not a part of the full Twitch team (some of the benefits are excluded) you will be invited to The Live Coders Discord server where you can learn from the rest of the team. (restricted access not all channels)

Please contact me to get your access

- @TheS7evin -> Twitter
- LuckyNoS7evin#0001 -> Discord
- LuckyNoS7evin -> Twitch
