### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by whitep4nth3r** [livecoders/Home#239]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

What is the URL for your Twitch channel?
https://twitch.tv/whitep4nth3r

Are you a Twitch affiliate or partner? Affiliate as of Friday 3rd July.

What languages / frameworks / tools do you program in while streaming on Twitch?
I’m an FE specialist, currently working with Angular on an interactive guitar theory website. Mainly JS, TS and all FE things. I have some fun projects planned to see how far we can stretch accessibility and design on the FE. (The most recent idea is a Geocities style website that is 100% accessible...!)

Why do you write code on stream?
It helps me talk through problems as I would with pair programming. I want to make coding accessible to people who might have otherwise been scared away by overly technical language, strongly opinionated technical people - I want to encourage questions and engage in productive discussions about learning and approaches to learning.

What is your favorite moment from coding on stream? Share a clip if one is available
My streams are about working through problems as a team, I like it when people get involved. A viewer suggested I use the JS ‘Set’ and it was a perfect solution to the problem I was solving and it felt like a true team effort, real pair programming. Also this weekend I released a new feature and the viewers helped with the QA process - another true team effort! (Don't know why this vod isn't processed yet - but it was stream number 2 on Sunday 5th July.)

What do you want to accomplish with the Live Coders?
I’d like to be part of a team that can work together to make coding accessible to whomever wants to access it and learn. As a qualified teacher, teaching and learning is incredibly important to me - to be able to give anyone access to high quality teaching and learning resources and content to enable them to achieve their goals and potential in life.

What do you want the Live Coders team to help you with?
Just being part of a shared platform to increase accessibility to science and tech is all that will suffice. It would be great to be able to share experiences, build things together, and promote the discussion that tech education should be accessible for all.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Not sure what happened here, we're in the midst of reviewing applications
and were interested in your stream.


Jeff

**Comment by whitep4nth3r** [comment]
Apologies, I kind of panicked and thought 'no way would my application be approved because I've only been streaming a week...' - especially as the description stated that you weren't reviewing applications just now.

If you insist, I can reapply?

**Comment by csharpfritz** [comment]
Even easier than re-applying... let's just re-open the GitHub issue!


Jeff

**Comment by whitep4nth3r** [comment]
Oh yeah, you have the comment history! Oh go on then ;)

**Comment by csharpfritz** [comment]
Welcome to the Live Coders!  Look for a Twitch team invite in your email.  Click through to accept that invite and we'll get you on our team mailing list and Discord

**Comment by whitep4nth3r** [comment]
Thank you! I'm honoured!
