### ISSUE TITLE
Application for Membership - Benjamin Lannon

### ISSUE THREAD

**Issue by lannonbr** [livecoders/Home#24]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/lannonbr

**What languages / frameworks / tools do you program in while streaming on Twitch?**
JS, GatsbyJS, React, Docker, GitHub Actions

**Why do you write code on stream?**
I want to be able to provide my insights about the various tools to others and be able to show building tools and sites live and showing the struggles and successes of actual development compared to just the successes you may find in other video formats.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
In one of my earlier streams I was developing a project and I had a carefree moment where I was working on a site and when I tried spinning it up. In the end it was a silly error that I forgot to save all of the files and I laughed it off.

It started around this timestamp on this VOD: https://www.twitch.tv/videos/447835544?t=1h41m0s

**Comment by mtheoryx** [comment]
A legend in the stream community, amazing moderator in many channels for a long time, and really supportive of streamers learning Gatsby.

I support this :)

**Comment by csharpfritz** [comment]
Approved!
