### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by m-henderson** [livecoders/Home#241]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/RobedCoder

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
.net core
ruby
c#
TypeScript
Vue
Angular
React
Sql
Docker
Jinja
Python
Flask
Django
Tensorflow
Karas

**Why do you write code on stream?**
To entertain and inform through the art of coding.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I fell asleep building an IdentityServer. I was almost late for work! 
https://www.twitch.tv/robedcoder/clip/ElegantRepleteWatercressOhMyDog

**What do you want to accomplish with the Live Coders?**
To get more involved with the coding community. 

**What do you want the Live Coders team to help you with?**
Exposure

If you have any questions about this process, please email: info@livecoders.dev

**Comment by Enjoy2Live** [comment]
Michael definitely belongs there I learned so much from him and can't find a better web dev content honestly.
wish him all the best!

**Comment by m-henderson** [comment]
@Enjoy2Live thank you for the love! I am glad you enjoy watching and learning!

**Comment by LuckyNoS7evin** [comment]
The Live Coders - Nurturing Program - Acceptance

With The Live Coders growing rapidly the team introduced a minimum viewership and other criteria.

Interactivity
Inclusivity
Community
Teaching
Learning
You are invited to become a Live Coders Nurture Member, not a part of the full Twitch team (some of the benefits are excluded) you will be invited to The Live Coders Discord server where you can learn from the rest of the team. (restricted access not all channels)

Please contact me to get your access

@TheS7evin -> Twitter
LuckyNoS7evin#0001 -> Discord
LuckyNoS7evin -> Twitch
