### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by negue** [livecoders/Home#244]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.
✅ 

**What is the URL for your Twitch channel?**
https://twitch.tv/thatn00b__

To Click on Markdown: [https://twitch.tv/thatn00b__](https://twitch.tv/thatn00b__)

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
- JS, TypeScript, C#
- Angular, Svelte
- depending on the project maybe even other languages / frameworks

Tools: mostly WebStorm (for the Web-Languages), Visual Studio

**Why do you write code on stream?**
I've been coding on many of my own projects since I started software development years ago, quite often I thought I could try out streaming this progress & discuss ways / directions on how to try X to fix/improve Y, but due to my stutter I never really thought about it more than that.
Lately thanks to twitch and the people on it (e.g. @cmgriffing @mtheoryx @cyberbarbie and many more) encouraged me to start streaming and here I am :)

**What is your favorite moment from coding on stream?  Share a clip if one is available**
No clip yet, but it's quite often a rollercoaster with finding a bug, trying to fix and then see that a simple character broke everything. 

**What do you want to accomplish with the Live Coders?**
Be able to build up / collaborate on community projects, show / discuss or learn easy to complex data structures and to show that anyone can stream. 

**What do you want the Live Coders team to help you with?**
To help me improve my streaming and other soft skills. As a developer, we never stop learning, so I want to learn as much as I can from others.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by negue** [comment]
Oh, I had to change to the markdown link syntax because markdown didn't like the underscores. Should I change back to the normal string syntax?

**Comment by LuckyNoS7evin** [comment]
The Live Coders - Nurturing Program - Acceptance

With The Live Coders growing rapidly the team introduced a minimum viewership and other criteria.

Interactivity
Inclusivity
Community
Teaching
Learning
You are invited to become a Live Coders Nurture Member, not a part of the full Twitch team (some of the benefits are excluded) you will be invited to The Live Coders Discord server where you can learn from the rest of the team. (restricted access not all channels)

Please contact me to get your access

@TheS7evin -> Twitter
LuckyNoS7evin#0001 -> Discord
LuckyNoS7evin -> Twitch
