### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by bellesamways** [livecoders/Home#245]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/bellesamways

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
yes

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Ruby
Rails
HTML/CSS

**Why do you write code on stream?**
I believe that education can change lives and I want participate of that.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I like of chatting with people in little intervals and I love so much that my followers chat with so respectful.
https://www.twitch.tv/videos/670906921

**What do you want to accomplish with the Live Coders?**
I want more visibility for girls in tech and RoR.

**What do you want the Live Coders team to help you with?**
I really believe that a team can helps me to become my stream more professional.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Welcome to the Live Coders!  Look for an email from Twitch with an invite to join the team.  We will follow-up with a whisper on Twitch to join the team Discord server
