### ISSUE TITLE
Application for Membership - Noam Shemi

### ISSUE THREAD

**Issue by Shemicalx** [livecoders/Home#247]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://www.twitch.tv/shemicalx

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Yes, I am a Twitch affiliate.

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Im learning web-development using FreeCodeCamp. So far I've been mostly working with JavaScript, React, HTML and CSS

**Why do you write code on stream?**
Im all about learning. I find myself learning extremely effectively on stream, and so I abuse that a much as I can!

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Strictly coding related - probably learning React. I am in love with React at the moment and the learning process has been nothing but amazing. In general, thats my favorite moment - 
Raid recursion: https://www.twitch.tv/shemicalx/clip/GeniusSpineyCormorantDBstyle

**What do you want to accomplish with the Live Coders?**
I am so passionate about learning, streaming and programming right now and nothing would make me happier than having a community of such people to share my passion with. 

**What do you want the Live Coders team to help you with?**
Theres nothing specific I can think of at the moment.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Welcome to the Live Coders!  Look for an email from Twitch with an invite to join the team.  We will follow-up with a whisper on Twitch to join the team Discord server
