### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by mariusurbelis** [livecoders/Home#248]
**What is the URL for your Twitch channel?**
https://twitch.tv/MariusUrbelis

**Are you a Twitch affiliate or partner?**
Yes. An affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Usually Unity C# development, sometimes web development or working on my own twitch bot in JavaScript

**Why do you write code on stream?**
Coding is something I enjoy doing and am planning to have a career in tech/software engineering. On stream I want to share ideas and have other people stop by to give their input.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
One of the recent funny moments happened when someone broke the TTS notifications of my channel.. This is it: [clip](https://www.twitch.tv/mariusurbelis/clip/BovineSavoryFalconWOOP)

**What do you want to accomplish with the Live Coders?**
I really like what the Live Coders mission is. Spreading knowledge and positivity is something I would like to contribute to. I have already done some explaining of concepts to people on my stream and I loved it. Thus I would like to be a part of this team.

**What do you want the Live Coders team to help you with?**
I would like to get to know more of the Science & Tech category streamers and get more involved.

**Comment by LuckyNoS7evin** [comment]
no worries just no https://

**Comment by mariusurbelis** [comment]
@LuckyNoS7evin I created the markdown style link. My apologies did not realize the bot was scraping for it :o

**Comment by mariusurbelis** [comment]
Application withdrawn.
