### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by b1lly** [livecoders/Home#249]
**What is the URL for your Twitch channel?**
https://twitch.tv/rubadubtv

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
1. Primary streaming languages/tech: Javascript, HTML, CSS, MySQL, Node
2. Frameworks: Custom built game & rendering engine, no dependencies. 
3. Tooling: Gulp, Bazel, Jest, Node, etc.

**Why do you write code on stream?**
I enjoy teaching and engaging with others. I also appreciate the networking aspects, the fresh perspectives and the support you can get from others. Having people to collaborate with and talk to while working is a huge plus!

**What is your favorite moment from coding on stream?  Share a clip if one is available**
There's so many, but one of my proudest moments was finally getting my game to a state that looked great and being able to share the progress with others live: https://www.twitch.tv/videos/404926761?collection=iKnRKpqSkRVoHA

**What do you want to accomplish with the Live Coders?**
I'm looking to be part of a community of like-minded individuals to share, learn and grow with in both my career as an engineer and twitch streamer! 

**What do you want the Live Coders team to help you with?**
Community & Friendship! Looking for a team to be able to collaborate with for streaming and development, and build mutual relationships of support.

**Comment by b1lly** [comment]
bump @csharpfritz how does one go about getting reviewed?

**Comment by csharpfritz** [comment]
Welcome to the Live Coders!  Look for an email from Twitch with an invite to join the team.  We will follow-up with a whisper on Twitch to join the team Discord server
