### ISSUE TITLE
Application for Membership: JoshKupka

### ISSUE THREAD

**Issue by JoshKupka** [livecoders/Home#25]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/JoshKupka

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Java, Javascript, C#, JavaFX, Electron, FIRST Robotics Java Code

**Why do you write code on stream?**
I write code because i want to inspire the next generation i want to be able to document progress made on my project, and i want to have resources to show to the kids i mentor

**What is your favorite moment from coding on stream?  Share a clip if one is available**

**Comment by csharpfritz** [comment]
While light on coding, we like how you talk through your process with the viewers.  Approved!

Looks for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.
