### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by stphnnnn** [livecoders/Home#250]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/stphnnnnn

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Yes, I'm a Twich Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Mostly JavaScript. Node.js, React, Three.js, Next.js, MongoDB.

**Why do you write code on stream?**
I love teaching and learning with other people. 

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Building a synth controlled by Twitch chat was so much fun! https://www.twitch.tv/videos/676890413

**What do you want to accomplish with the Live Coders?**
I want to inspire and encourage developers. Show that it's okay to not know everything and make mistakes.

**What do you want the Live Coders team to help you with?**
Help and advice on ways to improve my stream and hopefully some other live coders who'd like to collaborate on some projects.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Welcome to the Live Coders!  Look for an email from Twitch with an invite to join the team.  We will follow-up with a whisper on Twitch to join the team Discord server
