### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by madgen-content** [livecoders/Home#251]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://www.twitch.tv/madgen_content

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
yes. I'm an affiliate.

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Python. I'll eventually do some electrical engineering and low-level programming onstream as well
I solve algorithm problems (think leetcode, hackerrank) for now. 

**Why do you write code on stream?**
I started streaming as a way to keep myself on a schedule for studying for job interviews.
The side project was a fun creative thing to do in tandem. 
I've been really happy with the results though. I've met some really cool people and found some great communities.
I plan to keep doing it. 

**What is your favorite moment from coding on stream?  Share a clip if one is available**
briefly describe
https://clips.twitch.tv/TallStrangeMoonPeteZarollTie
^ I got a really big raid while running a stream to support protesters. It pushed me into affiliate. 
also, i don't normally curse much onstream. I just normally expected 3-8 viewers at this point and my viewers went up to 120. 

**What do you want to accomplish with the Live Coders?**
The more we can connect members of the dev community the better. 
I'd just like to meet some people. find some decent streams to hang out in and extend my reach

**What do you want the Live Coders team to help you with?**
i don't really _want_ anything per se; it just seems like a decent community

If you have any questions about this process, please email: info@livecoders.dev

**Comment by madgen-content** [comment]
not sure what's going on here. I can click the link and it goes to my profile

**Comment by LuckyNoS7evin** [comment]
The Live Coders - Nurturing Program - Acceptance

With The Live Coders growing rapidly the team introduced a minimum viewership and other criteria.

Interactivity
Inclusivity
Community
Teaching
Learning
You are invited to become a Live Coders Nurture Member, not a part of the full Twitch team (some of the benefits are excluded) you will be invited to The Live Coders Discord server where you can learn from the rest of the team. (restricted access not all channels)

Please contact me to get your access

@TheS7evin -> Twitter
LuckyNoS7evin#0001 -> Discord
LuckyNoS7evin -> Twitch
