### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by chadgreen** [livecoders/Home#254]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/TaleLearnCode

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Yes - Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
C#, Azure (mostly Cosmos DB and Functions, but others also), graph databases (Gremlin)

**Why do you write code on stream?**
It provides another outlet for me to share my love for the community and give back.  Live coding is a great way to share knowledge and experience because those watching are learning as I learn.  I generally take time to explain what I'm doing and this has been a great way for me to do what I would normally do at conference sessions but even better.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I do not have a clip as its a bit long; but one day I was just thrashing on some code not making progress.  Someone in chat (whom I know outside of Twitch) had some good ideas.  I brought him on the stream via Skype and we fired up Visual Studio Live Share and worked out the issue together.  This is what live coding is about - learning from each other.

Adding a second favorite moment, because it was a fun moment - I was interviewing G. Andrew Duthie and my new follower alert fired off and I was completely startled.  https://www.twitch.tv/talelearncode/clip/RichLovelyHamPJSalt

**What do you want to accomplish with the Live Coders?**
Being able to reach out to even more people.  I am not worried about number of viewers, followers, or subscribers as this is something I do for fun; but I do like being able to help more people.  Being a member of Live Coders would help me spread my love of technology.

**What do you want the Live Coders team to help you with?**
Probably provide help on improving my streaming.  I have been doing this since May, but know there is always more I can do to make things better.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Welcome to the Live Coders!  Look for an email from Twitch with an invite to join the team.  We will follow-up with a whisper on Twitch to join the team Discord server
