### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by reisdev** [livecoders/Home#257]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://www.twitch.tv/reisdev

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)

Yes. I'm affiliate.

**What languages / frameworks / tools do you program in while streaming on Twitch?**

Javascript, Typescript, Python, CSS, SQL, Node, React.js, Scrapy, Vue.js

**Why do you write code on stream?**

 Because I love to share knowledge, answer questions and meet new developers. I started doing inspired by one of the Live Coding Team member, marcobrunodev.

**What is your favorite moment from coding on stream? Share a clip if one is available**

https://clips.twitch.tv/ImpossibleGiftedRaisinWutFace

On Jun 6, Gaules, one of the world biggest streamers, sent a raid to me. I was raising funds to help a developer with her cancer treatment and he donated R$1000 to help her. This changed completely changed my perspective of live streaming. I want to help people just like he does, and I want to do it specially with coding.

**What do you want to accomplish with the Live Coders?**

I want to be part of the community, meet new people and share my knowledge as much as I can.

**What do you want the Live Coders team to help you with?**
 
I expect more people being able to find my content and learn from the codes that I write.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Welcome to the Live Coders!  Look for an email from Twitch with an invite to join the team.  We will follow-up with a whisper on Twitch to join the team Discord server
