### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by SashaCloud** [livecoders/Home#258]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only. [done]

**What is the URL for your Twitch channel?**
https://twitch.tv/tauons

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
I use the learning resources provided as part of my degree program (textbooks and such, which I never upload to YouTube to avoid potential legal conflicts), as well as MOOCs (fine to upload to YT, though I haven't yet- haven't learned much about editing videos yet!). 
So far the languages I've streamed in have included HTML5/CSS3, SQL (different versions, mostly mySQL), C++, and Python3. I've used Microsoft VS and PyCharm.
I stream using SLOBS.

**Why do you write code on stream?**
I'm learning to code for my BS CS degree. I wanted to share that learning process with others. I like to learn and to teach.
In short, to share knowledge.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
My favorite moment so far was when naysayer88 raided me with over 300 viewers (my largest raid so far).
https://www.twitch.tv/videos/688941815  [highlight]

**What do you want to accomplish with the Live Coders?**
I want to learn from you, and to grow with you! I want to be part of a community, and I already love the streamers I've found from this team! I find that I often raid your members because they're streams I think my viewers would enjoy. The content is similar to (though not exactly the same as) mine. If accepted, I am interested in finding ways (other than raiding) to give back to and participate with this team, including development of bots. I already have enjoyed learning some JS to customize nightbot.

**What do you want the Live Coders team to help you with?**
I suppose I could use tips for video editing, viewer engagement, and probably also getting my personality across. I also want to transition into a more professional stream style. I started off streaming as a way to help myself stay awake (I have narcolepsy) while I study, but now it's more than that. I want to help people learn with me, and want to figure out how to do that while keeping people engaged. I suppose I could use help figuring out monetization, but I don't want to do that if it becomes intrusive or disruptive for my streams. I don't even know if you guys are comfortable helping with that!
_Basically, any constructive criticism or advice would be welcome, but I don't expect my hand to be held. I just want to ensure I am doing a good job of representing the team, and to make sure I grow with you._

If you have any questions about this process, please email: info@livecoders.dev

**Comment by SashaCloud** [comment]
I'm moving to a new apartment today, so my location/setup is about to change for the better! I'll have space to incorporate a lot more interactivity with my viewers through things like whiteboards. I'm so excited!

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... looks like you are no longer streaming.  If you resume streaming and are interested in joining, please re-open this ticket
