### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by michaelbpaulson** [livecoders/Home#26]
**What is the URL for your Twitch channel?**
https://twitch.tv/ThePrimeagen

**What languages / frameworks / tools do you program in while streaming on Twitch?**
I code mostly the JavaScriptCore Engine and JavaScript related to Memory Analysis.  React or bare bones javascript sometimes.  Google Chrome Debugger hacking from time to time.  

**Why do you write code on stream?**
Well I code for teh Netflix and I really enjoy talking to people.  So its rare that you can code and talk to people at the same time until streaming came along.  Netflix has generously allowed me to code some portion of my work so I stream that whenever possible.

I also code some fun side projects (see links below).

**What is your favorite moment from coding on stream?  Share a clip if one is available**
// This one is just absurd...
https://www.twitch.tv/theprimeagen/clip/SmallBreakableScorpionCharlietheUnicorn?filter=clips&range=all&sort=time

// Best intro since coding
https://clips.twitch.tv/RelatedShinyCocoaWOOP

// Favorite gaming clip from like 1 year ago :7 (before I knew I could even stream coding).
https://www.twitch.tv/theprimeagen/clip/ElatedProductiveSkirretKappaRoss?filter=clips&range=all&sort=time

**Comment by krtschmr** [comment]
i watch him sometimes. should be on!

**Comment by DynamicDonkey** [comment]
He should totally be on the livecoders team, this guy knows what he's talking about!

**Comment by godoppl** [comment]
This guy is a wizard in vim, and has awesome energy!

**Comment by Daggersoath** [comment]
Just started watching recently but very interactive and seems to have a good knowledge base to draw from.

**Comment by arsavard** [comment]
I watch live or VODs every day. Really fantastic stream. Learned so much about memory issues while watching him. Let him join!

**Comment by godoppl** [comment]
I'm just gonna leave this here...
https://www.twitch.tv/products/theprimeagen

**Comment by cmckee-dev** [comment]
I generally listen to coding podcasts in the mornings.
I stumbled upon his stream and its a good energy and quality mixture of code, music, giveaways and Interaction with chat.
I never watch coding streams but ended up sticking around all morning! Quality stuff!

**Comment by michaelbpaulson** [comment]
I may have asked for some stream participation... :)

**Comment by csharpfritz** [comment]
Great content, and lots of fun to see the encouragement on this issue.

Approved!  You'll see a whisper from me and an email invite to join the team.  Once accepted, I'll send over the team Discord.
