### ISSUE TITLE
Improve website to show tooltip with more information about stream

### ISSUE THREAD

**Issue by Martialis39** [livecoders/Home#262]
Hi!

This is _probably not the right place_ for this, but I wanted to suggest an improvement to the site. I love it, but often times I go to Twitch because they have this handy little tooltip thingy that allows me to see what the stream is about and helps me decide if I want to watch it. 
![image](https://user-images.githubusercontent.com/17801528/89117825-9bff9000-d4a9-11ea-8955-4eb1ff5348cd.png)

If your website is an open repository, I would love to take this issue on myself, if you think it would be an improvement.

**Comment by Martialis39** [comment]
Sorry guys, I got confused. I now realize the `team` site is Twitch's territory

**Comment by csharpfritz** [comment]
@Martialis39 I like this idea, and a number of folks on the Live Coders are interested in contributing feedback and UI suggestions to Twitch.

I think the right place you're looking for is https://twitch.uservoice.com/

It would be REALLY cool if we could submit code fixes / improvements to them in an open-source community manner.  Let us know if you open a feedback item, and I'm sure a you'll get some of our teammate's support
