### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by IsaiahByDayah** [livecoders/Home#265]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/IsaiahByDayah

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Yes

**What languages / frameworks / tools do you program in while streaming on Twitch?**
TypeScript / JavaScript, React, Firebase, GatsbyJS

**Why do you write code on stream?**
I really enjoy the community aspects of live-streaming coding. Being able to talk tech with others while doing the thing I find really fun and enjoyable is great. I've also had a few viewers help me with issues I've run into and that doesn't hurt either ha

**What is your favorite moment from coding on stream?  Share a clip if one is available**
My community came together and formed a "competing" service to the app I build which constantly brings up funny jokes and references on stream. It even spurred the creation of our Discord which I'm really thankful for.

**What do you want to accomplish with the Live Coders?**
Continue to build my community, find more friendly dev streamers to watch & chat with, and help make dev streams more fun and inviting.

**What do you want the Live Coders team to help you with?**
Advice on streaming stuff (I'm happy with the progress of things I've made so far but can always learn more about streaming / managing a channel / etc), and continuing to build the Dev community on Twitch, both through my channel and through others (even those not affiliated with Live Coders).

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... looks like you are no longer streaming.  If you resume streaming and are interested in joining, please re-open this ticket
