### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by bradgarropy** [livecoders/Home#266]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/bradgarropy

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Yes, affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
[JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript)
[Node.js](https://nodejs.org/)
[React](https://reactjs.org/)
[Svelte](https://svelte.dev/)
[styled-components](https://styled-components.com/)
[Tailwind CSS](https://tailwindcss.com/)
[Netlify](https://www.netlify.com/)
[Gatsby](https://www.gatsbyjs.org/)

**Why do you write code on stream?**
1. To let others know that coding is hard, and struggling is okay.
2. To create an open environment for viewers to ask questions and learn as a supplement to their tutorials.
3. To meet other developers.
4. To learn and take ideas from chat.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
- Launching a [big side project](https://dailytexascountry.com) [live on stream](https://clips.twitch.tv/DoubtfulSarcasticLionAsianGlow)!
- My [first raid](https://clips.twitch.tv/SuaveExquisiteCrabsM4xHeh), when `chrisoncode` brought over 32 people!

**What do you want to accomplish with the Live Coders?**
I'd like to meet other developer streamers, learn from them, find ways to collaborate, and help each other grow!

**What do you want the Live Coders team to help you with?**
I have a lot to learn about Twitch and OBS, while my stream is high quality it's not very engaging. So I'd like to understand those aspects better. And initially I could use any help I can get to increase my reach as a streamer.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... looks like you are no longer streaming.  If you resume streaming and are interested in joining, please re-open this ticket
