### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by jjessel** [livecoders/Home#267]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/jcubedapps

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
I am a Twitch Affiliate. I currently have a 7.4 viewer average. 

**What languages / frameworks / tools do you program in while streaming on Twitch?**
I am a Senior iOS Engineer and am currently doing a series on learning React and Node, I am learning from scratch. Shortly after I am going to do a series on SwiftUI for iOS. 

**Why do you write code on stream?**
I do gaming streams and coding streams and I plan on increasing the live coding content. I have always been driven to give back to the community, to help others avoid pitfalls that I myself fell into. There are a lot of people who want to learn how to code or to just get better. I think seeing someone go through the thinking process is invaluable. It is important for new learners to understand that even experienced devs need to look things up or have bugs. 

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I only have 3 streams of coding under my belt so far, others were all gaming. I love how people come in and love helping. I can't wait to start the SwiftUI stream!

**What do you want to accomplish with the Live Coders?**
 I want to join a team of other developers to reach people who have questions and want to learn. 

**What do you want the Live Coders team to help you with?**
Reaching new people.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... looks like you are no longer streaming.  If you resume streaming and are interested in joining, please re-open this ticket
