### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by NadzeyaD** [livecoders/Home#268]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://www.twitch.tv/pearly_owl

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
yes

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Swift (for iOS development, ML), occasionally JS (node.js for APIs), python (for ML), dart (for flutter). 

**Why do you write code on stream?**
I enjoy sharing my experience with viewers. Also it's fun just to chat with others during development :)

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Wasn't really a moment, but some part of stream. Once I was working on tinder like feature for my app (social network for dog owners). During this we were filling test data together with viewers (they suggested name, fun pictures for dogs) and then simulated matching together with chat. So chat was voting how I should swipe :) Kinda enjoyed it a lot

**What do you want to accomplish with the Live Coders?**
It's always nice to grow and be part of something bigger than just small twitch streamer :) Also if i become part of the team it will probably give me motivation to improve my streams quality.

**What do you want the Live Coders team to help you with?**
Hm, don't really need any help :) But I might be helpful for you

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... looks like you are no longer streaming.  If you resume streaming and are interested in joining, please re-open this ticket
