### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by gwenf** [livecoders/Home#269]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/faradayacademy

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Javascript and Python; mostly Vue.js and Django

**Why do you write code on stream?**
I love solving things with a community. It helps me to rubber duck and get new ideas; people also message me and say how much my streams help them.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I love when I get stuck and then end up figuring something out with the people in the chat. I can't pick out a specific moment, but it happens most streams.

**What do you want to accomplish with the Live Coders?**
I would like to get more viewers and also be a part of the small, but growing community of livecoders on Twitch.

**What do you want the Live Coders team to help you with?**
Getting new ideas for how I can make my streams more interactive and fun to watch.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... looks like you are no longer streaming.  If you resume streaming and are interested in joining, please re-open this ticket
