### ISSUE TITLE
Application for Membership: Sch3lpsc2

### ISSUE THREAD

**Issue by Sch3lp** [livecoders/Home#27]
I don't have the _store forever_ feature on Twitch, but I archive to YouTube.

[Here's a playlist](https://www.youtube.com/playlist?list=PLb9Sf9ImdCXLLEoTTFFH9SrwEXJiwNd-C) of my project I've been working on since April this year.

**What is the URL for your Twitch channel?**
https://twitch.tv/sch3lpsc2

**What languages / frameworks / tools do you program in while streaming on Twitch?**
* Kotlin
* VueJS
* TypeScript
* Java
* IntelliJ
* Visual Studio Code

**Why do you write code on stream?**
I'm currently working on a hobby project where I hope to learn new stuff (about Kotlin, Vue, other testing frameworks maybe, ...).
And more importantly hope to prove to myself that I can incrementally architect from a monolith to hexagonal (because I have the tendency to over design architectures); and/or move from an anemic domain model to a proper domain model with CQRS.

The reason I'm sticking to it is because livecoding works for me like pair programming with someone that doesn't know the project. And this is helpful to me because there's a **lot** of introspection which helps me become a better programmer.

At the same time I hope to share the knowledge I have and help people out with that.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Probably [the one where I got raided](https://www.twitch.tv/videos/408528405) by PixelogicDev. 😁

[Or maybe this one](https://www.twitch.tv/videos/459964482) where I'm amazed by Vue's productivity.

Or [this one](https://www.twitch.tv/videos/459960435) where I didn't tune my sound very well and hilarity ensues.

**Comment by csharpfritz** [comment]
Looks great!  Invite extended.  Look for a whisper from me with an invite to the team Discord
