### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by perkinsjr** [livecoders/Home#270]
**What is the URL for your Twitch channel?**
https://twitch.tv/jamesperkins

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**

NodeJS / React/ NextJS / HTML CSS + Javascript and Go

**Why do you write code on stream?**
I love to teach, and I find showing the authenticate approach to development versus videos on Youtube where I can edit it all out. I wrote an article about it recently (https://jamesperkins.io/post/why-i-love-streaming-over-youtube-videos) 

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I'd say recently it would be making my Twitch interactive lights using Philips Hue, here is the first working both lights clip:

https://www.twitch.tv/jamesperkins/clip/DoubtfulIntelligentElephantBudBlast?filter=clips&range=all&sort=time 

**What do you want to accomplish with the Live Coders?**

I want to show how coding can be fun versus reading from a book or watching a tutorial, lets build interactive content as well as explaining it as we go. I also want to see Live Coders grow as a community. 

**What do you want the Live Coders team to help you with?**

Improve my streaming content, find out other people in the team have seen success with.

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... looks like you are no longer streaming.  If you resume streaming and are interested in joining, please re-open this ticket
