### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by phanxgames** [livecoders/Home#272]
**What is the URL for your Twitch channel?**
https://twitch.tv/phanxgames

**Are you a Twitch affiliate or partner?** 
Yes Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Languages: TypeScript, JavaScript, PHP, Haxe, ActionScript3
Projects: MMORPG Server in Node.js, MMORPG Client, and Game Tools and Editors

**Why do you write code on stream?**
I am developing a retro mmorpg, every step of the way, on twitch for the past 5 years.  I do programming of the client, engine, tools, and server, plus pixel art, level design and mapping. All while engaging my audience.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Being able to meet and engage my audience has been a blessing. Turning an ordinary solo programming session into a group activity with my viewers- many of which I find now my friends!

**What do you want to accomplish with the Live Coders?**
Have a list of like minded streamers to raid and host after my streams and to have means to grow together!

**What do you want the Live Coders team to help you with?**
Together we can all grow and help each other with growing our audiences and making an awesome meta community.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... we would like to invite you to join the team!  Look for an invite email from Twitch with a link to join the Live Coders.  Once you have accepted the Team invite, I will send a whisper on Twitch with a link to join the team Discord.

Congratulations!
