### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by roxworks** [livecoders/Home#273]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/roxkstar74

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Yes! Affiliate :)

**What languages / frameworks / tools do you program in while streaming on Twitch?**
So far just Backend Javascript & Node

**Why do you write code on stream?**
Honestly, I just started doing it tokeep myself productive. But one day I got raided and I found a community of extremely kind and helpful people. Now I do it because it makes me happy - it feels like I'm hanging out with a bunch of friends :) 

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I was coding by myself about a week ago. I had one viewer I was chatting with. ThePrimeagen raided me with ~100 people, and I was so taken aback I literally started crying on stream. After about ten minutes I finally got myself back together enough to start explaining to people what I was doing, and a bunch of them hung around and helped me out and followed, and some have kept coming by since. It's a day I'll never forget :)

**What do you want to accomplish with the Live Coders?**
I really believe in community. If there's a community of people like me I can support or who can teach me, I can't see a single reason I shouldn't pursue it. At a minimum, it would be great to just meet you all!

**What do you want the Live Coders team to help you with?**
I'm still not very sure of how to "run a stream" - I can code, I can talk, I can explain what I'm doing, but I'm pretty worried I'm being a bit...unproffessional? Or really that I'm just a noob. I want to be sure I'm doing everything I can to give people a fun experience watching me, and any tips would be extremely meaningful.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... we would like to invite you to join the team!  

If you are still interested, we will extend an invite.

**Comment by csharpfritz** [comment]
Closing with no response from @roxworks
