### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by solenberg** [livecoders/Home#274]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/phrakberg

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
I made affiliate on 8/17/2020

**What languages / frameworks / tools do you program in while streaming on Twitch?**
I'm currently learning on FreeCodeCamp.  Eventually, I'd like to venture into serverless development on AWS with JS/Python.

**Why do you write code on stream?**
I'm using my stream as dedicated time to learn. 

**What is your favorite moment from coding on stream?  Share a clip if one is available**
For me, its seeing people I've formed friendships with on twitch show up and support me.  I've really enjoyed getting to know several streamers.  Having them come support me (and a little good-natured trolling I definitely deserve) really makes me enjoy my time streaming.

**What do you want to accomplish with the Live Coders?**
I want to be part of the community.   I think the team needs some more AWS people.

**What do you want the Live Coders team to help you with?**
I'd like to spend more time learning.  Learning with friends is always a good experience. 

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... we would like to invite you to join the team!  Look for an invite email from Twitch with a link to join the Live Coders.  Once you have accepted the Team invite, I will send a whisper on Twitch with a link to join the team Discord.

Congratulations!
