### ISSUE TITLE
User335's Application for Membership

### ISSUE THREAD

**Issue by user335** [livecoders/Home#277]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/user335

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Yes

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Unity in C#, Visual Studio, occasional Zbrush

**Why do you write code on stream?**
Game dev! I've been making a first-person RTS since 2016 and more than 60% of my streams are feature work / debugging code

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Gotta be the time a brand new viewer (Grrenix) tipped over $100 to force me to attempt to sing Eye of the Tiger on stream: https://www.twitch.tv/user335/clip/BeautifulLitigiousWoodcockNinjaGrumpy

**What do you want to accomplish with the Live Coders?**
I plan to keep streaming for a long time and most of my favorite people to raid all belong to this same group! Honestly I have no idea why I haven't applied much, much sooner than this

**What do you want the Live Coders team to help you with?**
I'm always open to more feedback / advice about anything related to my game or game development in general

If you have any questions about this process, please email: info@livecoders.dev

**Comment by user335** [comment]
Hi! I'd still really like to join the Live Coders! Talk2meGooseman was telling me my application might have gotten missed during some administrative reshuffling you guys were doing last year, though, and that I should leave a nudge here just in case...

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... we would like to invite you to join the team!  Look for an invite email from Twitch with a link to join the Live Coders.  Once you have accepted the Team invite, I will send a whisper on Twitch with a link to join the team Discord.

Congratulations!
