### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by Flyken271** [livecoders/Home#278]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/Flyken

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
I am an Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
I do a wide wide range of things but mostly node.js and fullstack stuff.

**Why do you write code on stream?**
I want to share my knowledge and collaborate with others on what I'm doing and learn from it as well!

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I don't have a clip of it however my favorite time was when I was stuck on a piece of code for 3 days before the stream and
someone had come in and helped me through the bugs and errors.

**What do you want to accomplish with the Live Coders?**
I've watched many members from the Live Coders team and I'd love to join the big family that is provided by this team.

**What do you want the Live Coders team to help you with?**
I actually don't expect anything from the team, if I had to chose what I'd like help with it'd have to be help with programming and making sure people are learning :)

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... looks like you are no longer streaming.  If you resume streaming and are interested in joining, please re-open this ticket
