### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by elliott-troop** [livecoders/Home#279]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/elliott_troop

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Yes; affiliate!

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Kotlin & Android Studio

**Why do you write code on stream?**
To research topics that are required for my personal Android application and to basically encourage myself to finish out a project

**What is your favorite moment from coding on stream?  Share a clip if one is available**
When things finally work as intended after many failed attempts or hours researching

**What do you want to accomplish with the Live Coders?**
To network with other streamers that love to code and are deep-thinkers

**What do you want the Live Coders team to help you with?**
Would honestly love some feedback on my app, but just good vibes and pointers for a coding streamer

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... looks like you are no longer streaming.  If you resume streaming and are interested in joining, please re-open this ticket
