### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by ShemJM** [livecoders/Home#28]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://www.twitch.tv/shemiroth

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Mostly HTML/CSS and JavaScript. I am keen to learn new languages in the future

**Why do you write code on stream?**
I am writing the code anyway, so I might as well stream it. Hopefully people can learn something and also I can learn from my viewers

**What is your favorite moment from coding on stream?  Share a clip if one is available**
briefly describe
When people use JSfiddle or something to edit the code I am working on.

**Comment by csharpfritz** [comment]
The Live Coders talk to their viewers, even when no one is viewing live.  We'd like to see more of that in your videos.

Holding for further review.

**Comment by ShemJM** [comment]
Thanks for the feedback, can you offer any more advice on how I could improve my stream?
