### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by stijnelskens** [livecoders/Home#280]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://www.twitch.tv/Laks_1

**Are you a Twitch affiliate or partner?**
Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**

HTML5
CSS3 | Sass | TailwindCSS
Javascript | jQuery
Craft CMS | Twig
Webpack | Parcel | Babel | ESLint
VSCode | Sublime
MAMP Pro

**Why do you write code on stream?**
I love to do some projects in my free time, working with Craft CMS.
There are not to much **frontend** development streamers and certainly not with Craft CMS,
So I like to share my knowledge about Craft CMS to show how easy it is to work with it.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Do not have a clip but, getting satisfied when learning and trying out some code and get it finally work.
Also the raid from adam13531 with more than 2.5k viewers!

**What do you want to accomplish with the Live Coders?**
Become a better developer, get to know other developers and share knowledge.

**What do you want the Live Coders team to help you with?**
Become a better and bigger streamer. Reach new people and get to know new people and developers.
Just become a better developer in general.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... looks like you are no longer streaming.  If you resume streaming and are interested in joining, please re-open this ticket
