### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by itsaeji** [livecoders/Home#282]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/triippers

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
I'm mostly using Unreal Engine 4, which includes blueprint scripting, C++ programming, level design, 3d modeling, 2d drawing, animating and other facets of game development.

**Why do you write code on stream?**
I've decided that educational streams are the best way for me to enjoy streaming and grow.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Funny bugs from small mistakes. For example, I set a forward vector as a teleport location instead of a launch velocity and ended up making my character launch to the far reaches of the map. It was pretty funny.

**What do you want to accomplish with the Live Coders?**
Be a part of like minded people that want to grow and learn from each other.

**What do you want the Live Coders team to help you with?**
Nothing really, I just want to make friends in the community.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... looks like you are no longer streaming.  If you resume streaming and are interested in joining, please re-open this ticket
