### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by donthedeveloper** [livecoders/Home#283]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/donthedeveloper

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Yes

**What languages / frameworks / tools do you program in while streaming on Twitch?**
JavaScript - (NodeJS, ExpressJS, Mongoose/Mongo, Sequelize/Postgres, ReactJS)

**Why do you write code on stream?**
Since before I even became a professional developer, I loved connecting with other developers and helping other aspiring developers out with their career goals. I have a web development mentorship Meetup with 1000+ members that aims to do just that.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
https://www.twitch.tv/donthedeveloper/clip/ColdbloodedEnchantingCroissant4Head?filter=clips&range=all&sort=time

I usually code, but sometimes I drink and code/play games, and it surprises me how much viewers still stick around for minority content or silly moments. It reminds me how great the Twitch community really is. Youtube has been much more finicky for me and doesn't really seem like much of a community in comparison.

**What do you want to accomplish with the Live Coders?**
I'd honestly like to get to know some other streamers in this community. I actually do live web development podcasts - collaboration might be an option. I'd say relationship building would be my primary focus.

**What do you want the Live Coders team to help you with?**
Honestly, just providing a network to build relationships, collaborate, and share raids would be great.

If you have any questions about this process, please email: info@livecoders.dev 

Thank you!

**Comment by seekaplayer** [comment]
@csharpfritz I can say @donthedeveloper is a very awesome person and would be a great asset for the Live Coders Team :)

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... looks like you are no longer streaming.  If you resume streaming and are interested in joining, please re-open this ticket

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... we would like to invite you to join the team!  Look for an invite email from Twitch with a link to join the Live Coders.  Once you have accepted the Team invite, I will send a whisper on Twitch with a link to join the team Discord.

Congratulations!
