### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by seanw122** [livecoders/Home#284]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/CodeWithSean

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Yes, affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
C#, Azure, Infrastructure as Code (ARM templates, Pulumi, et al)

**Why do you write code on stream?**
It's a great opportunity to share what (little) I know with others. And, learn at the same time. I really enjoy teaching and sharing what lessons I have learned from others.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
briefly describe

**What do you want to accomplish with the Live Coders?**
Knowledge is nearly useless if we don't share. Streaming to anyone that wants to learn more is a win-win. They learn more about the subject. And, I also learn more about the subject I'm streaming about. I know I grow most when I have to prepare something to teach.

**What do you want the Live Coders team to help you with?**
Nothing that I know of. I already have all streaming equipment.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by seanw122** [comment]
Note: I have had to delete a couple of VODs due to doxing. I'm working with people at Microsoft about ways to prevent showing IDs, etc. I already have the Azure-Mask addon and it doesn't work 100% of the time. Also, I'll be setting a schedule as soon as I can. Right now, I can only stream once a week until I get a personal project completed. If that means this application is "on hold" I'm ok with that and I understand.

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... looks like you are no longer streaming.  If you resume streaming and are interested in joining, please re-open this ticket

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... we would like to invite you to join the team!  Look for an invite email from Twitch with a link to join the Live Coders.  Once you have accepted the Team invite, I will send a whisper on Twitch with a link to join the team Discord.

Congratulations!
