### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by GeeH** [livecoders/Home#285]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/spabby

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Yes

**What languages / frameworks / tools do you program in while streaming on Twitch?**
PHP (Laravel, Bref, Laminas)
Java (IntelliJ Plugin)
JavaScript (React mainly)

**Why do you write code on stream?**
Community building and collaboration on OS work. Also, its SO MUCH FUN.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
When I got my IntelliJ plugin working so that chat could "help" me code - https://www.twitch.tv/spabby/clip/TransparentDrabCookieBudStar

**What do you want to accomplish with the Live Coders?**
I'd like to collaborate on improving my stream and community and share ideas with a team on how to improve interaction between me and the stream.

**What do you want the Live Coders team to help you with?**
Networking, ideas and collaboration. I'd like to get more guests on stream from diffrent languages and communities.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... looks like you are no longer streaming.  If you resume streaming and are interested in joining, please re-open this ticket
