### ISSUE TITLE
 Application for Membership

### ISSUE THREAD

**Issue by FitzyCodesThings** [livecoders/Home#287]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/fitzycodesthings

**Are you a Twitch affiliate or partner?** Yes (affiliate)

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Primarily C#/DotNet Core, occasionally JS/Node.js, will be doing a bit more Python, too (learning basic ML). Primary tools are VS and VS Code, occasional CLI work. Mainly work on web applications and blockchain projects (specific to Dragonchain technology for now).

**Why do you write code on stream?**
Still figuring this out. :) The schedule/expectation of producing something interesting motivates me to show up and code. The interaction with my (still very small) community, though, is quickly becoming my favorite part. I get tons of help and ideas from viewers (TheGrumpyGameDev saves my bacon once a week or so). The laughs, learning to deal with not getting it right, etc. It's a whole lot of awesome.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
LaylaCodesIt raid with 89 viewers? 😁 No, I've had several in the category of "getting to share my dinosaur wisdom." One very short example from a fellow just in college to learn code who was shocked, I think, that I was picking up basic Python syntax after 25 years developing (15 years professionally): https://clips.twitch.tv/SucculentSnappyGoblinNomNom (not a meaty clip) 

**What do you want to accomplish with the Live Coders?**
A lot! I can't really separate the top two things I hope to achieve through working with Live Coders. The first is getting better as a developer in general (a big theme for me is talking about not "getting stuck into your own code," especially as a solo developer, and forgetting to learn/keep up with trends/etc.).

The second, 100%, is getting better as a content producer and contributor to the developer community. 

**What do you want the Live Coders team to help you with?**
I've been messing with "the tech" of AV production for years (don't have the best setup, but it works), so not hugely concerned there. I mainly want help/coaching/etc. on viewer engagement, audience building, and generally building a better and more useful stream and community. 

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... looks like you are no longer streaming.  If you resume streaming and are interested in joining, please re-open this ticket
