### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by madebygps** [livecoders/Home#288]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/madebygps

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Yes, I am a Twitch affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
I mainly explore services in Azure, when I code, I use dotnet core. 

**Why do you write code on stream?**
I enjoy learning in public and making mistakes. I feel like it gives me a way to learn with others and encourages others to get into tech. I started on [YouTube](https://youtube.com/madebygps) and really enjoyed the feedback from there, am now looking to expand to a live platform like twitch. 

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Figuring out errors is definitely the best feeling I've encountered, I don't have many clips, [here is one](https://www.twitch.tv/videos/743770848)

**What do you want to accomplish with the Live Coders?**
Be part of a community that makes code and tech open, available, accessible, and more interactive for others.

**What do you want the Live Coders team to help you with?**
I'd like to learn how to become a better educator and resource for the community. The people I watch on twitch from the Live Coders teams are fantastic at teaching in a way that doesn't feel like a school lecture. 

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... we would like to invite you to join the team!  Look for an invite email from Twitch with a link to join the Live Coders.  Once you have accepted the Team invite, I will send a whisper on Twitch with a link to join the team Discord.

Congratulations!
