### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by swolemaz** [livecoders/Home#289]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/swolemaz

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Kotlin, IntelliJ, Android Studio

**Why do you write code on stream?**
 I write code on stream to share my Kotlin learning process, to connect with coders and like-minded, passionate individuals.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Building off of what I learned from Android Basics in Kotlin, I created a [DnD dice roller app](https://clips.twitch.tv/HappySpineyDeerPJSugar), 

**What do you want to accomplish with the Live Coders?**
Connecting with folks that are also passionate about coding, collectively sharing our knowledge with one another. I also understand how representation matters and would like to show womxn at any age you can get started learning how to code. 

**What do you want the Live Coders team to help you with?**
Collaborating together on projects like LudumDare, best practices for capturing browser, IDE and simulator to be displayed altogether. Currently I have second monitor captured where browser is 1/4 of screen and IDE is 3/4th, and tap on simulator to be visible over IDE when rebuilding app to observe code changes.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Closing with no response from @swolemaz
