### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by douglascorrea** [livecoders/Home#29]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/douglascorrea_

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Currently I'm streaming Rust, I'm building a gameboy emulator live from scratch with support from the viewers of the channel. 
But I also plan to stream some hardware stuff like trying to compile that GB emulator in a SAMD51 microcontroller and those type of things

**Why do you write code on stream?**
I'm still learning Rust, and I would like to make a complete project from scratch to feel that I'm able to do something real with the language.
Then, to avoid losing the focus and stopping the project in the middle, I decided to expose myself in the stream, and that was the best choice I would make.
Now I not only keep working for me but also for those who follow my streams. I really feel like I own them to finish the project.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
When I go the Nintendo logo into the emulator screen:
https://clips.twitch.tv/FurryQuaintSnakeAMPEnergyCherry

**Comment by csharpfritz** [comment]
I don't see any recorded videos, and we are only accepting Affiliate or Partner streamers.  

We look forward to you re-applying once those qualifications are met.

**Comment by douglascorrea** [comment]
@csharpfritz github somehow printed the wrong URL, my twitch is: [https://twitch.tv/douglascorrea_](https://twitch.tv/douglascorrea_) with an "underscore" at end.

All my videos are there, and I'm also an Affiliates already.
