### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by lilybugged** [livecoders/Home#291]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://www.twitch.tv/pachi_dev

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Yes; affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Godot/Unity/blender/etc - GDScript, C#, python, lua, others. I do game dev, 3d modelling and sometimes I write bots.

**Why do you write code on stream?**
I work on projects for long periods of time, so doubling that time as social time is a healthier option for me. Plus, since I VStream with a virtual avatar, it's a creative outlet too!

**What is your favorite moment from coding on stream?  Share a clip if one is available**
https://www.twitch.tv/videos/661978814 (I don't have many recent vods/clips from my code streams; I had to take a break to finish a bunch of commissions)

**What do you want to accomplish with the Live Coders?**
I want to reach a wider audience so that I can make use of the skills I've built thus far, primarily in indie game development. I want to influence people and especially female aspiring developers so that they may feel inspired to start/complete their own projects. I wish I had someone to influence me that way when I was younger.

**What do you want the Live Coders team to help you with?**
I would like to participate in activities, collaborations or any other sort of events that Live Coders hosts.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... looks like you are no longer streaming.  If you resume streaming and are interested in joining, please re-open this ticket
