### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by saphirako** [livecoders/Home#292]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/saphirako

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Python, C#, Javascript (more-or-less exclusively React), Docker

**Why do you write code on stream?**
I started my stream to get better at explaining my work to people outside of my team at the office. I've stuck around with it because I've enjoyed the community and people I've met through Twitch!

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Honestly, my favorite moment was the first time I saw some ask the classic "how do I get started in coding" question. I've answered in other people's chats with links and whatnot but I never thought I would be the person/stream that someone asks. It felt really cool!

**What do you want to accomplish with the Live Coders?**
I would like to foster a community of people with common goals and interests while also getting to know the other LiveCoders streamers more.

**What do you want the Live Coders team to help you with?**
I would love to have some help with community building and with areas in development that I haven't yet learned.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by michaelpmiddleton** [comment]
If you guys do look at source code, I mainly use [GitLab](https://www.gitlab.com/michaelpmiddleton). 🙂

**Comment by saphirako** [comment]
SInce this application, I've split my personal work (GitLab) and strream work (GitHub). Still excited at the prospect of joining you all :)

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... we would like to invite you to join the team!  Look for an invite email from Twitch with a link to join the Live Coders.  Once you have accepted the Team invite, I will send a whisper on Twitch with a link to join the team Discord.

Congratulations!
