### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by Rel904** [livecoders/Home#293]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/Rel904

**Are you a Twitch affiliate or partner?** Yes, Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
PHP, Laravel, VueJS, PHPStorm, Docker

**Why do you write code on stream?**
I code on stream as programming is my strongest skillset that I can offer and I try to educate myself along with anyone willing to stop by. A major point of coding on stream though is to work with different tools and technologies as I'm not just trying to code exactly how I do during my day job, but to get out of my comfort zone and become vulnerable by not having experience with whatever I am trying to apply.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Favorite moment for me is when chat and I have problem-solved an issue that was hard to solve. There are many moments like this, but an instance that sticks out is when I was trying to learn how to setup Docker for Windows (I normally use WAMP). I really enjoy when I can ping questions off chat and come to a solution.

**What do you want to accomplish with the Live Coders?**
With Live Coders, I am looking to network better and become more intrenched in the coding community as Twitch has made it somewhat difficult to find like minded coders. I want to learn to be a better programmer while also trying my best to teachers others what I know.

**What do you want the Live Coders team to help you with?**
I don't think I need much, just better networking. I've streamed on twitch for over a year and a half, just not on a set schedule. Up until the last 2 months, I was streaming bad gameplay, but switching to something that I am good at, I've seen better viewership and interaction.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by austenc** [comment]
@Rel904 is awesome! 

Not only has he been a helpful viewer on my stream, but his stream is welcoming and fun too! 👍

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... looks like you are no longer streaming.  If you resume streaming and are interested in joining, please re-open this ticket
