### ISSUE TITLE
Application for Membership - @austencam

### ISSUE THREAD

**Issue by austenc** [livecoders/Home#296]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream. 
Also ensure that your vods are not sub only.

_Done and done!_ 👍

**What is the URL for your Twitch channel?**
https://twitch.tv/austencam

**Are you a Twitch affiliate or partner?** 
Indeed, I'm an affiliate.

**What languages / frameworks / tools do you program in while streaming on Twitch?**
PHP, Laravel, AlpineJS, Livewire, Javascript

Also occasionally do some design with Figma. Think of it as a "full stack variety stream."

**Why do you write code on stream?**
Three reasons. To help other folks learn stuff, to learn things myself, and to grow my audience across platforms. 
There's another reason too -- I really enjoy communicating with chat and collaborating with them. I find that sharing what I'm doing is incredibly fun and addicting!

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Hmm, not sure I have a specific clip. However, my favorite moments are when chat contributes to a hard problem, or I'm able to answer a question for someone and help them further their learning!

**What do you want to accomplish with the Live Coders?**
Become part of a community, improve the quality of my stream, and meet some new people!

**What do you want the Live Coders team to help you with?**
Networking with people and improving my stream's interactivity for viewers. I would love to improve the overall quality of the stream, but have no expectations of receiving help, especially before giving it. :) 

Finally, I'd like to say thank you for the consideration! Feel free to reach out via DM on Twitter: https://twitter.com/austencam

Have a nice day!

**Comment by Rel904** [comment]
I would highly recommend Austen for the LiveCoders program as he demonstrates everything that other programmers who are trying to learn want in the streamer they watch, including knowledge of the multiple subjects he brings on-stream and fantastic chat interaction... along with being one of the few of us PHP/Laravel devs!

**Comment by austenc** [comment]
Wow, thanks @Rel904 for the recommendation.

Naturally, my recent streams have been design-based, but I plan to hop back to the coding side of things this week. 🤗

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... looks like you are no longer streaming.  If you resume streaming and are interested in joining, please re-open this ticket
