### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by ryantupo** [livecoders/Home#298]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/ryantupo

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
List briefly here
python
java
typescript
will be starting some PHP sadly soon XD haha

**Why do you write code on stream?**
briefly describe
chat keeps me going , i wouldnt study without their inspiration and nagging XD

**What is your favorite moment from coding on stream?  Share a clip if one is available**
briefly describe
https://www.twitch.tv/ryantupo/clip/IntelligentOriginalPandaMoreCowbell?filter=clips&range=all&sort=time
i basically ctrl Z too many times and re screwed up a solved error XD

**What do you want to accomplish with the Live Coders?**
briefly describe
continue to learn and grow an amazing diverse and supporting community

**What do you want the Live Coders team to help you with?**
briefly describe
help me expand my knowledge and platform as much as i can. aswell as making friends 👍 :)

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... looks like you are no longer streaming.  If you resume streaming and are interested in joining, please re-open this ticket
