### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by Stuyk** [livecoders/Home#30]
**What is the URL for your Twitch channel?**
https://twitch.tv/stuykgaming

**What languages / frameworks / tools do you program in while streaming on Twitch?**
C#, C++, JavaScript, LUA, Typescript, etc.

It depends on the project; and no project is ever the same. NodeJS is the most commonly used however. You can review what gets used on my GitHub.

**Why do you write code on stream?**
I come from a base of users who are primarily developers who are interested in programming for Grand Theft Auto V. A lot of my user base writes code for clients like alt:V, FiveM, RAGE:MP, etc. We're basically a bunch of modding enthusiasts who write more code than anything. I started streaming more often because the medium allows users to learn off of what I'm writing currently and ask questions while I'm present and using the code. Its much easier to digest and provide examples than talk about it in a YouTube comment.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
On one of my past Sunday streams we went down a wild rabbit hole where despawning a single door in an interior in GTA:V caused crazy side effects. Walls disappearing, world completely glitched out, and other really interesting things.

**Comment by csharpfritz** [comment]
Looks great!  Really enjoyed seeing your work with GTA.

An email will be sent from Twitch with an invite to the team, and once accepted I'll send an invite to the team Discord.
