### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by daanbreur** [livecoders/Home#300]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/PortaalGaming

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
yes

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Javascript, NodeJS, Vscode, Terminal

**Why do you write code on stream?**
I write code on stream to share my knowledge and learn things togheter

**What is your favorite moment from coding on stream?  Share a clip if one is available**
When something finally works! And we have learned from my faults

**What do you want to accomplish with the Live Coders?**
meet AWESOME streamers and grow my channel

**What do you want the Live Coders team to help you with?**
?

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... we would like to invite you to join the team!  Look for an invite email from Twitch with a link to join the Live Coders.  Once you have accepted the Team invite, I will send a whisper on Twitch with a link to join the team Discord.

Congratulations!

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... looks like you are no longer streaming.  If you resume streaming and are interested in joining, please re-open this ticket

**Comment by daanbreur** [comment]
Hello! I do still stream however not a lot lately. I will re-open if I'm more active
