### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by Dmidecode** [livecoders/Home#304]
**What is the URL for your Twitch channel?**
https://www.twitch.tv/dmidecode

**Are you a Twitch affiliate or partner?** Yes

**What languages / frameworks / tools do you program in while streaming on Twitch?**
I use Visual studio.
I develop in C# / Angular

**Why do you write code on stream?**
I am really passionate by programming, it's my job. I love to teach other people who want to learn about development.
Unfortunately I need to teach myself how to be more pedagogue. 
I am trying to start some new project but to be honest, I am new to streaming and I don't have a lot of people who are interested by the subject.
I have the feeling that streaming code will teach me how to be more pedagogue and I will try to discover some new framework / tools.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I don't have a favorite moment for now, but I will love if someone come just to speak about coding and tips about angular or C#.
I have a recent stream where I do a "shifumi" in C# and an old video on youtube (it's expired on twitch).
https://www.youtube.com/watch?v=p8n31BIDUOo&t=754s&ab_channel=Dmidecode (learn the basic c#)
https://www.twitch.tv/videos/760433706 (the "shifumi")

**What do you want to accomplish with the Live Coders?**
I would like to be part of a community of people who love coding !
I am still a novice in streaming but I can only develop myself to be more entertaining.
If I can try to transmit my love to other people it will be wonderful.

**What do you want the Live Coders team to help you with?**
For now, not much, but if someone wants to tell me some advices to touch more people I will be happy.

I will be more that happy to discuss of that with you :)

See you soon.

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... we would like to invite you to join the team!  Look for an invite email from Twitch with a link to join the Live Coders.  Once you have accepted the Team invite, I will send a whisper on Twitch with a link to join the team Discord.

Congratulations!
