### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by CuriousDrive** [livecoders/Home#305]
**What is the URL for your Twitch channel?**
https://www.twitch.tv/curiousdrive

**Are you a Twitch affiliate or partner?**
Yes

**What languages / frameworks / tools do you program in while streaming on Twitch?**
I use Visual studio/VS Code.
I develop in C#
I mostly play coding games to help viewers get ready for coding interviews

**Why do you write code on stream?**
I love the community on Twitch. There are so many smart people in chat who guide me to write better code. It makes me better.
They also help/encourage the new developers in chat to write code or get started with it. I want to part of that community which helps people write better code.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
There are so many. I like to make people laugh and not be stressed about writing/learning to code. 
The best moments are when I run out of time while playing coding games and not solve the problem. Currently I do not have any clips 

**What do you want to accomplish with the Live Coders?**
I want to be friends with all the coders on Twitch. And hopefully one day I would like to present a demo project in one of your live conferences. That would be fun.

**What do you want the Live Coders team to help you with?**
Help me help new developers :)
Programming is not easy and it could get frustrating and stressful for new developers. Let's help them.

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... looks like you are no longer streaming.  If you resume streaming and are interested in joining, please re-open this ticket
