### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by martinisoft** [livecoders/Home#306]
**What is the URL for your Twitch channel?**
https://twitch.tv/martinisoft

**Are you a Twitch affiliate or partner?**
Yes, Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
* Ruby
* Kubernetes & HELM
* Python
* NeoVIM & Visual Studio Code

**Why do you write code on stream?**
Given the current situation with COVID I wanted to try working out in the open on a stream and invite others to join me and collaborate. I miss pair programming in person and this is a good outlet to get interactive work done in programming. I'm also a very big believer and contributor to Open Source and live streaming while you work feels like the ultimate level of open with programming.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Recently a new developer learning Python was working on a project that authenticates with a web page then submits a form. Throughout the stream I helped them with a code review and gave them several tips on how to accomplish what they were wanting to do and near the end of my stream they came back to let me know they were successful. There are several clips from that interaction since it happened at various parts of the stream. Here is one: https://clips.twitch.tv/GiantQuaintSkirretKippa

**What do you want to accomplish with the Live Coders?**
I'd like to get a wider reach to mentor more developers as I work on more projects out in the open. Being part of a community of developers dedicated to sharing knowledge and teaching is a personal goal of mine.

**What do you want the Live Coders team to help you with?**
Guidance on engaging and growing my audience to foster a community of developers dedicated to learning and sharing knowledge. Having promotional help would be a great bonus as well.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... looks like you are no longer streaming.  If you resume streaming and are interested in joining, please re-open this ticket
