### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by vic10us** [livecoders/Home#307]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/vic10usx

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
yes

**What languages / frameworks / tools do you program in while streaming on Twitch?**
C#, dotnet, Angular, lit-html, web components

**Why do you write code on stream?**
to learn and teach code with as many people as possible.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
That's a real hard one. Probably when I got my first raid.

**What do you want to accomplish with the Live Coders?**
show that technology is accessible and help as many people understand that everyone has value regardless of their skill level.

**What do you want the Live Coders team to help you with?**
exposure and guidance on how to improve my content

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... looks like you are no longer streaming.  If you resume streaming and are interested in joining, please re-open this ticket
