### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by smilesandtea** [livecoders/Home#31]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/smilesandtea

**What languages / frameworks / tools do you program in while streaming on Twitch?**
I work with front end languages in VS Code to build interactive web pages. I also use Photoshop to design websites in full before moving on to building them during stream, and lastly of course, GIT to navigate, create files and push to github. I'm looking to build in more languages because i am currently learning Ruby and in the framework scope will be diving into React soon.

**Why do you write code on stream?**
I write code on stream because i love interacting with people and getting to build fun projects at the same time. As a coder, I'm also still a learner, so it works as a way to document my journey but improve and learn as i stream.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
There's been a lot of funny moments, one of my favorite is the clip linked below where the code did not react how i thought it would: https://clips.twitch.tv/TalentedSpoopyParrotKappaPride

**Comment by csharpfritz** [comment]
Really enjoy your honest approach and the way you talk to chat.  Approved!

Look for an invite from Twitch to join the team.  I'll start a whisper conversation with you and once you click through the invite from Twitch, I'll send a link to join the team Discord

Welcome to the Live Coders!
