### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by p4rZ** [livecoders/Home#311]
##twitch.tv/parzival_forever
------
**What is the URL for your Twitch channel?**
https://twitch.tv/parzival_forever

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Yup. Twitch affliate. Tho, currently it went down 4 avg viewers this week. (wrt 30 days)

**What languages / frameworks / tools do you program in while streaming on Twitch?**

C, C++, Java, Python.
I use dev C++ for Competitive programming practices.
For projects, it is either VS Studio or Intellig IDEA.
I haven't started working with python or used any framework, coz I am caught up with practising CP.
Update my repos using gitkraken.

**Why do you write code on stream?**
I am learning new stuff and love computer science, undergrad in CSE, also, an avid innovator with robotics and creating solutions. I feel, there is a lack of motivation somewhere among many people who take computer science just because of better job opportunities, so, It helps me motivate on my stream and maybe guide in few things that I have learnt over the years.
Planing to keep my motivation up too, starting with working with one of the opensource projects online for my GSOC coming next year.

**What is your favourite moment from coding on stream?  Share a clip if one is available**
I was raided by one of the biggest competitive coders on the planet, Errichto on twitch who runs a twitch stream/Youtube Channel. That made me motivated even more and work towards making streaming with more content and quality!
https://www.twitch.tv/videos/771950346 ( not a clip but a highlight )

**What do you want to accomplish with the Live Coders?**
Be part of the community and get some help to grow a little more. 
I am happy to help, but, I am not really an expert of many things, but only programming languages, algorithms, studying tips, robotics a little. I am more into the research focused work. 

**What do you want the Live Coders team to help you with?**
I just want to be a part of the community and help me with how to improve my streams maybe. 

-------------

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... looks like you are no longer streaming.  If you resume streaming and are interested in joining, please re-open this ticket
