### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by adelsonguimaraes** [livecoders/Home#312]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/cafecodes

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
AFILIADO

**What languages / frameworks / tools do you program in while streaming on Twitch?**
PHP, JAVASCRIPT, ANGULARJS, REACTJS, MYSQ, atualmente criando um chat bot para a twitch em php com sistema de RPG.

**Why do you write code on stream?**
Sou programador web a 7 anos, e então resolvi fazer lives para contribuir com a comunidade com um pouco do conhecimento que aprendi nesses anos.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Quando existem pessoas conversando comigo e inspiradas em aprender com o trabalho que desenvolvo.
https://www.twitch.tv/cafecodes/clip/ColdbloodedHardNoodleVoteYea?filter=clips&range=30d&sort=time

**What do you want to accomplish with the Live Coders?**
Alcançar mais pessoas da comunidade que desejem entender e aprender mais sobre o universo de desenvolvimento.

**What do you want the Live Coders team to help you with?**
No envolvimento com a comunidade.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... looks like you are no longer streaming.  If you resume streaming and are interested in joining, please re-open this ticket
