### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by witlock** [livecoders/Home#314]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/witlock

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Yes

**What languages / frameworks / tools do you program in while streaming on Twitch?**
C#, Blazor, Monogame (With Nez), Visual Studio, 

**Why do you write code on stream?**
For company and to keep myself in check.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
There's no one favorite moment, but It's probably when I finally realize what's causing the issue after trying to solve it for hours.
https://clips.twitch.tv/InventiveHumbleStarPeteZarollTie

**What do you want to accomplish with the Live Coders?**
I want the doorbell to ring.

**What do you want the Live Coders team to help you with?**
Be my friends.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... looks like you are no longer streaming.  If you resume streaming and are interested in joining, please re-open this ticket
