### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by ovation22** [livecoders/Home#315]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/6figuredev

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Yes

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Podcast
Blazor
C#/.NET
React
Docker
Kubernetes
Unit Testing
Clean Code

**Why do you write code on stream?**
Learning
Sharing
Growing

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Statiq Sites with Dave Glick, after the podcast, hanging out on stream going through file-new with the man himself.

During last night's stream we tried (and failed) to get the React site for SpeakerMeet into a Docker container. Chat had great ideas, but we were nearing the end of our scheduled time (and getting tired, as it was getting late). I felt it was important that others see and share in our short term failure to accomplish a task, and plan to step away and regroup at a later date. We all fail. We all struggle. We regroup and try again another day.

Also, any and all times communicating with viewers in chat!

**What do you want to accomplish with the Live Coders?**
Reach more viewers, get more feedback, share with more people. We have a lot of fun on stream, we learn, and we grow. 

**What do you want the Live Coders team to help you with?**
Perhaps some ideas on how to improve our stream, make it better, etc. Open to any and all ideas.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... looks like you are no longer streaming.  If you resume streaming and are interested in joining, please re-open this ticket
