### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by Peregons** [livecoders/Home#317]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://www.twitch.tv/peregonstream

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
yes

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Unity. C#

**Why do you write code on stream?**
It brings some fun to talk with viewers while i'm coding 

**What is your favorite moment from coding on stream?  Share a clip if one is available**
moment when written feature starts working as it should work
https://clips.twitch.tv/OpenOnerousLettuceArgieB8

**What do you want to accomplish with the Live Coders?**
Show my game to new viewers and get their reaction

**What do you want the Live Coders team to help you with?**
Become more famous on twitch

If you have any questions about this process, please email: info@livecoders.dev

**Comment by Peregons** [comment]
I'm sure that my URL is correct. it works.

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... we would like to invite you to join the team!  Look for an invite email from Twitch with a link to join the Live Coders.  Once you have accepted the Team invite, I will send a whisper on Twitch with a link to join the team Discord.

Congratulations!

**Comment by Peregons** [comment]
Hi there! accepted an invite. Waiting for your whisper now

  
>Пятница, 17 июня 2022, 20:16 +06:00 от Jeffrey T. Fritz ***@***.***>:
> 
> 
>Apologies for the delay in reviewing... we would like to invite you to join the team! Look for an invite email from Twitch with a link to join the Live Coders. Once you have accepted the Team invite, I will send a whisper on Twitch with a link to join the team Discord.
>Congratulations!
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <livecoders/Home/issues/317/1158916691 @ github . com> 
 
 
--
Людвиг Витовский
Отправлено из Почты  Mail.ru
