### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by Aenorya** [livecoders/Home#318]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/aenorya

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Twitch affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
C#, Unity, Visual Studio Community, 

**Why do you write code on stream?**
I love the connection with the viewers and I am a programming teacher so totally onboard with explaining what I do and why. I did some programmation webinars where I presentied a specific subject and did a bit of live coding and I loved it. Plus, viewers are like my rubber ducks, when I'm stuck, I explain to them the problem and we solve it. I like when viewers are non-devs because they have such creative ideas!

**What is your favorite moment from coding on stream?  Share a clip if one is available**
briefly describe
Getting unstuck. When we spent an hour on a problem and we finally make it work, everyone cheers in the chat and we celebrate together the little victories. 

**What do you want to accomplish with the Live Coders?**
I mostly do 2 to 3 hours streams on the evenings and when I'm done, I would like to direct my viewers on relevant game dev content. 

**What do you want the Live Coders team to help you with?**
I would like to promote more inclusivity and diversity in the game industry and especially in the technical parts and one part of doing that as a woman is going forward and show how cool is my job. But I want to be able to recommand a diverse community, not just individual women but a diverse and mixed gender team following the same guidelines as I do.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... we would like to invite you to join the team!  Look for an invite email from Twitch with a link to join the Live Coders.  Once you have accepted the Team invite, I will send a whisper on Twitch with a link to join the team Discord.

Congratulations!
