### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by skarab42** [livecoders/Home#319]
# Hello World 🐱‍🏍🌍
Skarab here! A French-speaking streamer who lives in Switzerland.

**What is the URL for your Twitch channel?**
https://twitch.tv/skarab42

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
> Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
> JavaScript/TypeScript | Svelte | NodeJS | Electron | Golang | C# | Python | ...

**Why do you write code on stream?**
> I have been producing open source code for over 10 years and being able to share what I do live is pure joy.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
> The best times are when someone (including me) learns/shares something new. But I also like to experiment with unnecessary things. [The uncanny valley](https://www.twitch.tv/skarab42/clip/RepleteDreamyPistachioNinjaGrumpy?filter=clips&range=all&sort=time)

**What do you want to accomplish with the Live Coders?**
> Share my love for code!

**What do you want the Live Coders team to help you with?**
> Promote the French-speaking science and technology category.

`Sorry for the short sentences, I'm not comfortable writing in English.`

**Comment by skarab42** [comment]
Hello, is the team still active?

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... looks like you are no longer streaming.  If you resume streaming and are interested in joining, please re-open this ticket
