### ISSUE TITLE
Application for Membership: Seekaplayer

### ISSUE THREAD

**Issue by seekaplayer** [livecoders/Home#32]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/seekaplayer

**What languages / frameworks / tools do you program in while streaming on Twitch?**
List briefly here

So right now I'm still learning but my primary is HTML, CSS, PHP, JavaScript, React, WordPress. I use mostly my MacBook Pro and VS Code. 

**Why do you write code on stream?**
briefly describe

I love being able to interact with the community. I'm still learning and I found reading/watching videos was not my learning style. I found actually doing something was the best way for me to learn. The best part is having some amazing help from the community. They have really helped me learn so much. I love being able to do things because of the awesome help I get from my viewers. 

**What is your favorite moment from coding on stream?  Share a clip if one is available**
briefly describe

Yes! This is when I was just getting started with JavaScript it the form actually worked! https://clips.twitch.tv/AliveHeartlessBearBIRB Such excitement! :D

**Comment by trezy** [comment]
I'd like to add here that @seekaplayer is a fantastic part of the programmer community on Twitch. He's still learning, and his journey is great for other new devs to follow. He's fantastic at taking feedback and engaging with the audience, and he's an all-around engaging presenter. ❤️

**Comment by csharpfritz** [comment]
I see... tag-team effort with @trezy 	

Enjoyed your videos where you're learning JavaScript and React.  The celebration in your clip was great!   Approved.

Looks for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.

**Comment by seekaplayer** [comment]
Thank you @csharpfritz I look forward to this :)
