### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by nikolovlazar** [livecoders/Home#320]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/nikolovlazar

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
I'm a Twitch Affiliate.

**What languages / frameworks / tools do you program in while streaming on Twitch?**
JavaScript, TypeScript, BlitzJS, NextJS, Chakra UI, Tailwind CSS, React

**Why do you write code on stream?**
I like showing people how to code, or how I code. It gives me a sense of accomplishment when someone's engaged in my streams and actually learns from me. Also it's fun!

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Chatting with people and fixing annoying bugs.

**What do you want to accomplish with the Live Coders?**
Just be part of the team. The Live Coders team is consisted of solid and renowned engineers, and I'd be very happy if I could be part of it. Also I hope it will help me grow my channel and bring me viewers.

**What do you want the Live Coders team to help you with?**
Review my streams and help me make them better, both from a technical perspective and "human" perspective.

**Comment by lazarnikolov94** [comment]
If you want to see my streaming archive, visit my YouTube channel here: https://www.youtube.com/channel/UCTexaJMnN_Pv6TVueQ61-oQ/videos

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... looks like you are no longer streaming.  If you resume streaming and are interested in joining, please re-open this ticket

**Comment by nikolovlazar** [comment]
Hello @csharpfritz! I'm becoming active again on Twitch, so I'd like to reopen this issue 🙂

**Comment by nikolovlazar** [comment]
I'd like to reopen this ticket.

**Comment by nikolovlazar** [comment]
Hey @csharpfritz. I actually experimented streaming on YouTube, but I'm actually back on Twitch now. I'd like to be considered for the Live Coders team 😁
