### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by spooksie** [livecoders/Home#321]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/bitvalentine
website: https://bitvalentine.com

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Laravel & Vue. PHPstorm

**Why do you write code on stream?**
I'm a growth hacker and build software to help with the process. I'm building a community as we speak and about to build a new project from scratch, which I want to stream.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Not coded yet on stream, but it will happen very very soon. You can see my past streams get a lot of viewers.

**What do you want to accomplish with the Live Coders?**
Teach and learn from other developers.

**What do you want the Live Coders team to help you with?**
To be a part of something. 

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... looks like you are no longer streaming.  If you resume streaming and are interested in joining, please re-open this ticket
