### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by MatthewEdge** [livecoders/Home#324]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/medgelabs

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Golang, Javascript, Bash, Terraform

**Why do you write code on stream?**
Pair programming opportunity, sharing what my day-to-day as a professional developer looks like, and expanding my craft with other passionate devs!

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Reaching MVP with the Twitch Bot thanks to the help of my amazing chat!

**What do you want to accomplish with the Live Coders?**
Expand the community, meet new passionate people, and learn from the vast community of live coders!

**What do you want the Live Coders team to help you with?**
No help expected! Merely looking to expand my live coding experience and learn from others!

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... looks like you are no longer streaming.  If you resume streaming and are interested in joining, please re-open this ticket
