### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by KlassyKat** [livecoders/Home#325]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/klassykat

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Javascript
Node.js
Vue
Electron

**Why do you write code on stream?**
I like to build things as a community and interact with chat.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I don't know if I could find a moment but we've started making a programming meme at the end of everyday and I've
been thoroughly enjoying it.
https://clips.twitch.tv/ViscousGloriousWatercressPoooound
https://clips.twitch.tv/FilthySteamyLyrebirdBudStar

**What do you want to accomplish with the Live Coders?**
I mean I'd love to be more closely involved in the code streaming community I feel like I'm starting to get to know
a lot of faces here and I'd like to continue that. 

**What do you want the Live Coders team to help you with?**
I mean most of what I do with my stream is an attempt to grow my stream. 

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... looks like you are no longer streaming.  If you resume streaming and are interested in joining, please re-open this ticket
