### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by razvan-flavius-panda** [livecoders/Home#329]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**

https://www.twitch.tv/freeman42x

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)

I am a twitch affiliate.

**What languages / frameworks / tools do you program in while streaming on Twitch?**
List briefly here

I program mainly using Haskell, sometimes Rust, C#, and related languages.

**Why do you write code on stream?**

I think streaming is very useful for both the viewers and myself. It's a great way for people to connect and learn from each other.

**What is your favorite moment from coding on stream?  Share a clip if one is available**

Someone meme-ing with a luck-based solution when playing Clash of Code with us:

https://www.twitch.tv/freeman42x/clip/MoralKindWallabyRitzMitz

Here's an example of going through the Natural Numbers Game using the LEAN theorem prover: https://www.twitch.tv/videos/899015912

**What do you want to accomplish with the Live Coders?**

Make more connections, teach, and learn.

**What do you want the Live Coders team to help you with?**

Maybe some streaming tips.

**Comment by razvan-flavius-panda** [comment]
Another VOD for something I streamed recently:

https://www.twitch.tv/videos/914702164

All the questions and answers (sumarised) from the VOD:

https://github.com/fairy-tale-agi-solutions/fairy-tale-artificial-general-intelligence-solutions/blob/master/AMA%20about%20Human-Level%20Artificial%20Intelligence%20dangers%2C%20implementation%20and%20our%20Future%20of%20Life%20startup.md#ama-about-human-level-artificial-intelligence-dangers-implementation-and-our-future-of-life-startup

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... looks like you are no longer streaming.  If you resume streaming and are interested in joining, please re-open this ticket
