### ISSUE TITLE
Application for Membership: Edson6

### ISSUE THREAD

**Issue by edsonayllon** [livecoders/Home#33]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/edson6

**What languages / frameworks / tools do you program in while streaming on Twitch?**

Javascript, React, React-Native, Typescript, MongoDB, Solidity, EOSIO, Node, Java.

**Why do you write code on stream?**

I do live programming related to Decentralized Finance, also known as Blockchain, usually commissions and sometimes hackathons. My goal is to inspire others to pick up new languages and frameworks, regardless of how difficult they seem, as well as educate people about the infrastructure of cryptocurrencies and the development that happens behind the scenes. 

**What is your favorite moment from coding on stream?  Share a clip if one is available**

I'm a relatively new at streaming (started regularly streaming in July, currently affiliate), so I don't have too much to pull from. Any moment a feature I've been working on for a while gets to work is a fun time for me. 

Here's one clip: https://clips.twitch.tv/UgliestWrongBadgerOSsloth

**Comment by csharpfritz** [comment]
Engagement with the viewers and chatroom is important to the Live Coders.  We don't see much engagement from you on video, and will check back later to see how your stream develops.

**Comment by edsonayllon** [comment]
Ok, reach out to me if you want to offer an invitation.
