### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by zanzertuchi** [livecoders/Home#330]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/zanzersworld

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Affiliate :) 

**What languages / frameworks / tools do you program in while streaming on Twitch?**
List briefly here
Unity3d/C#/Javascript

**Why do you write code on stream?**
I have a Twitch Interactive game called Stream Arenas!  I now work on it on stream a lot <3 

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Finished an entire feature on a very long stream for the game, while getting some feedback from the community.  I think that's my favorite part is talking through what I'm working on, why I'm doing it, and getting live feedback iteration.

**What do you want to accomplish with the Live Coders?**
Hoping to meet, learn, and grow with people with very similar interests on twitch/life.

**What do you want the Live Coders team to help you with?**
Hoping to learn how to improve the way I stream coding, development. Better ways to talk about what I'm doing, share it, etc.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... looks like you are no longer streaming.  If you resume streaming and are interested in joining, please re-open this ticket
