### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by brunogdz** [livecoders/Home#333]
**What is the URL for your Twitch channel?**
https://twitch.tv/dmitritv

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Yes, I have Twitch Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
C, C++, Nodejs, JavaScript, Vue, Nextjs, Discord Bot with nodejs, Apps with MongoDB and Node

**Why do you write code on stream?**
Show people that you dont need to be expect or know everything about the language to start to programming, I do some homeworks in live, show how works. I study Computer Science

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Developing a Tinder Clone and my friends laughing at me because I know how works tinder haha
https://clips.twitch.tv/SwissDaintyPrariedogCharlieBitMe

**What do you want to accomplish with the Live Coders?**
I want to contribute to and support the community, making networking and help the community grow up in brazil too.

**What do you want the Live Coders team to help you with?**
Some tips showing what I have to change and know more about other programmer around the world.

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... we would like to invite you to join the team!  Look for an invite email from Twitch with a link to join the Live Coders.  Once you have accepted the Team invite, I will send a whisper on Twitch with a link to join the team Discord.

Congratulations!
