### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by lukeocodes** [livecoders/Home#336]
Popping this in, for some time in the future when processing begins again.

Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/lukeocodes

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)

Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**

JavaScript/TypeScript

**Why do you write code on stream?**

To raise money for BlackGirlsCode and GirlsWhoCode

**What is your favorite moment from coding on stream?  Share a clip if one is available**

https://www.twitch.tv/videos/915306624

**What do you want to accomplish with the Live Coders?**

Give support to (and find support from) other tech streamers streaming for charities, and share my community.

**What do you want the Live Coders team to help you with?**

To help folks in the Twitch tech community, to be able to contribute to or participate in live coders events.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... we would like to invite you to join the team!  Look for an invite email from Twitch with a link to join the Live Coders.  Once you have accepted the Team invite, I will send a whisper on Twitch with a link to join the team Discord.

Congratulations!
