### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by dmfigol** [livecoders/Home#338]
**What is the URL for your Twitch channel?**
https://twitch.tv/dmfigol

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Yes, I am a twitch affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Python / FastAPI

**Why do you write code on stream?**
I focus on quite a niche area - network automation, where there aren't many best practices established. Live coding is a way for me to have a set time on my calendar to explore this area more in-depth and share my findings with the community - some find it useful.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
When audience helps me find a bug.

**What do you want to accomplish with the Live Coders?**
Help create a strong community around live coding, connect and collaborate more with other content creators in this space.

**What do you want the Live Coders team to help you with?**
I would appreciate an advice on growing the audience around live coding. I have been streaming for almost 3 years and I have no idea how to keep growing the channel - I have the same numbers as I had a year ago.

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... looks like you are no longer streaming.  If you resume streaming and are interested in joining, please re-open this ticket
