### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by LarissaAzevedo** [livecoders/Home#339]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://www.twitch.tv/usakimodoki

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Yes, affiliate 

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Javascript/ReactJs
Css/Sass

**Why do you write code on stream?**
It was a way that I found to show my work to people, find newbies in the field and help them as I can. I like to receive questions and find out the answers with those who asked, besides generating curiosity in those who never programmed.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I try to interact a lot with the chat during the live, I put the songs they ask for and I see memes that send me, a lot of people arrive at these moments of relaxation and already ask what I'm doing. I greet, make a joke and explain what we are doing.
https://www.twitch.tv/usakimodoki/clip/GentleSquareHeronDuDudu-SqUB_WKiwMK0IdME

**What do you want to accomplish with the Live Coders?**
I try to encourage those who also live, draw or something, so much that in the chat I always reinforce that I allow disclosures, since I want to meet other people in the business. I want to have fun and amuse other people while doing what I like. I encourage some people to study with me during the day and during lives and even ask questions live, it motivates me a lot to continue streaming. Being around other people who do what I do, besides motivating me, give me support and the knowledge I need to continue and improve.

**What do you want the Live Coders team to help you with?**
Network, friendships, new people with new jobs to be seen, reach and unity.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... we would like to invite you to join the team!  Look for an invite email from Twitch with a link to join the Live Coders.  Once you have accepted the Team invite, I will send a whisper on Twitch with a link to join the team Discord.

Congratulations!
