### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by mossyblog** [livecoders/Home#34]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/mossyblogz

**What languages / frameworks / tools do you program in while streaming on Twitch?**
C# / .NET Framework / LUA etc. 

**Why do you write code on stream?**
I've just started the twitch journey, but i was also on the team at Microsoft that created HD video for the web - so for me, this is a weird moment.  I write code on stream to share the experience and also feed off their pontential ideas as i get into more interesting parts of the projects. I am slowly learning how to enage back and forth, it took a moment or two to remember that being watched is important.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
davidortinau hackathon was an enjoyable experience, as when i worked at Microsoft i used to love these events .. it was a way to connect with the community hands on, no marketing / product positioning just reaction to the work you made with their responses to them (via code).

**Comment by csharpfritz** [comment]
Really enjoyed watching your most recent video at:  https://www.twitch.tv/videos/473924724   Great explanation of how the GTA APIs and features work.  Approved!

Look for an invite from Twitch in your email, and once accepted I will whisper you a link to the team Discord on Twitch.
