### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by giacoballoccu** [livecoders/Home#340]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/redsmoke3001

**Are you a Twitch affiliate or partner?** Yes, Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
C++, competitive programming, interview preparation, python, deep learning

**Why do you write code on stream?**
I do training for coding interviews and coding contest with viewers
**What is your favorite moment from coding on stream?  Share a clip if one is available**
When people told me that they were struggling to find motivation for interview prep and this channel is helping them

**What do you want to accomplish with the Live Coders?**
Be partner before summer 2021

**What do you want the Live Coders team to help you with?**
Make more people aware of the opportunities they have as developers and how fun competitive programming is

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... looks like you are no longer streaming.  If you resume streaming and are interested in joining, please re-open this ticket
