### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by adriancorbalan** [livecoders/Home#342]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/realcorben

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Yes.

**What languages / frameworks / tools do you program in while streaming on Twitch?**
I work with Unity. Writing code with C#.

**Why do you write code on stream?**
Because I believe that is important to share knowledge and try to make things easy. Also I'm learning a lot trying to explain everything.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
When people ask me questions about the project and I need to explain.

**What do you want to accomplish with the Live Coders?**
Try to make a effort with my language skills and get covered by the community. 

**What do you want the Live Coders team to help you with?**
Help me to be more visible and learn, always is about learn new stuff.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... looks like you are no longer streaming about software development.  If you resume streaming and are interested in joining, please re-open this ticket
