### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by arnauddupuis** [livecoders/Home#343]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://www.twitch.tv/8bitscoding

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Yes (Affiliate)

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Languages:
Python
C++
GDScript
And probably more in the future

Framework:
Godot
pygamelib
AI algorithms (so far Genetic Algorithms)
Working on adding Vulkan

**Why do you write code on stream?**
Why not? I like sharing and I'm teaching coding to young (6 to 13) kids for free to do my part in giving access to technical knowledge to kids that might not have access to it otherwise. I thought that it could translate well into a streaming experience. And although I'm a very small streamer, people are starting to ask coding questions that are not necessarily connected to what I do and the (small for now) community is helping in answering those questions. I really like that.
![image](https://user-images.githubusercontent.com/787155/114317786-a1908980-9abe-11eb-873e-268b37cef79e.png)

I also think that coding and algorithm are fun, and I'm trying to share that with people that watch my streams.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
One of the challenges in live coding, in my opinion, is that I have less time to think and need to be more dynamic than my usual workflow. And of course, it generates unwanted behaviors. This is often naturally funny (at least it makes me laugh ^^).
Example: I was coding the behavior of a toxic pool/acid lake and forgot to time the effects. Instead, I linked it to the framerate. This of course resulted in a very very quick death of the player...
https://clips.twitch.tv/BadFrigidFungusCoolCat-_D_Hl5PHfXUm04lH

**What do you want to accomplish with the Live Coders?**
Some of the live coders actually inspired me to go live and I would like to do the same for others. Hopefully, I can modestly contribute to the mission of the live coders as part of this community.
I also like to help others with their code.
Being lucky enough to not need the Twitch money, I give 100% of my channel's proceeds to charities. Hopefully, this reflects positively on the Live Coders too!

**What do you want the Live Coders team to help you with?**
Like every team: I would like to be able to ask questions and receive feedback to improve my streams. Obviously, I'd like the Live Coders community to help me grow my channel.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by arnauddupuis** [comment]
I double-checked: it is correct.

**Comment by csharpfritz** [comment]
Yea, we can tune that URL check to ensure it verifies that right one

A quick spot-check does confirm you are an affiliate


Jeff

**Comment by numbata** [comment]
@csharpfritz the related PR: https://github.com/livecoders/issues-twitch-url-checker/pull/11

**Comment by arnauddupuis** [comment]
So, do I need to do anything? Because as much as I check the URLs they are all correct.

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... looks like you are no longer streaming.  If you resume streaming and are interested in joining, please re-open this ticket
