### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by edandersen** [livecoders/Home#344]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/tedstech

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
C# / .NET Core / Visual Studio

**Why do you write code on stream?**
To connect with the world and share what I have learnt.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Someone joined a stream due to the AMA tag and asked a question regarding adding a class to a console app. Really basic stuff to us but I stopped what I was doing and hit File New Project for them and showed them. Gave me warm fuzzies being able to help. 

**What do you want to accomplish with the Live Coders?**
I'd like to collaborate on streaming tools. Huge potential here.

**What do you want the Live Coders team to help you with?**
Becoming a better technical streamer - it's hard!

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... we would like to invite you to join the team!  Look for an invite email from Twitch with a link to join the Live Coders.  Once you have accepted the Team invite, I will send a whisper on Twitch with a link to join the team Discord.

Congratulations!
