### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by parafoxia** [livecoders/Home#345]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/CarberraTutorials
(If you want a full list of all the streams I've done to look over, I upload the VODs to YouTube: https://www.youtube.com/playlist?list=PLYeOw6sTSy6YVmOn6pIV3q7_7anmwvOyv)

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Python basically. At the moment I'm going back and forth between game dev and image manipulation, but topics vary a fair amount.

**Why do you write code on stream?**
Mainly to plan series for YouTube, but streaming this planning process allows people to see what goes through my head when I actually make these things. It's an opportunity for people to see that I'm just a normal human being like them, and also allows people to contribute to the planning process and help me out when I get stuck. It's also a laugh with the community, and you can't complain with that.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I'm not really sure about any one particular moment. Being able to share the elation at finally getting something to work with people is always awesome though.

**What do you want to accomplish with the Live Coders?**
To grow, like anyone else. Ultimately though, it would be cool just to be a part of a like-minded community. Nowadays I tend to raid streamers after I finish, and happened to raid someone in this community. I found about it through them, and thought "there's no reason I shouldn't apply, really". Either way, it's a good place to find programming channels to raid.

**What do you want the Live Coders team to help you with?**
As I said before, I'm mainly joining to become part of a community. That's the main reason I started YouTube (and subsequently Twitch) in the first place, so the team would ultimately help with that. It would also be nice to reach out and get hints and tips, and just be able to chat to people.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... looks like you are no longer streaming.  If you resume streaming and are interested in joining, please re-open this ticket
