### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by phunkren** [livecoders/Home#347]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/phunkren

Past broadcasts are also available on my [YouTube channel](https://www.youtube.com/watch?v=VElugIZ6Zww&list=PL7_TxhdAmdDJAsqFmJ3A8V2jqf4Oo02kJ&ab_channel=AndrewJames). 

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Yes, I recently became an affiliate!

Your application requires a minimum average viewer count of 5. I'm currently sitting at ~4, but I've only really started streaming regularly over the last month or so and expect it to at least grow to at least that in the coming weeks. 

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Languages: JavaScript / HTML / CSS
Framework: React JS
Tools: VS Code, Chrome, StreamLabs OBS

**Why do you write code on stream?**
I've always been a fan of learning in public. Last year I documented my [#100DaysOfCode](https://twitter.com/phunkren/status/1210603544027504646?s=20), and this year I'm live streaming my progress through the [EpicReact.dev](https://epicreact.dev) course by Kent C Dodds. I plan on moving onto Josh W Comeau's [CSS course](https://css-for-js.dev/) afterwards, and then I've pencilled in converting my personal site (https://ajames.dev) to [Stitches / Radix UI](https://radix-ui.com/primitives/docs/overview/introduction)

**What is your favorite moment from coding on stream?  Share a clip if one is available**
[Kent C Dodds watching the stream and helping me out with one of the exercises on his course](https://www.twitch.tv/videos/996982312?t=00h49m30s).
What's great is I arrived at the solution, found a potential alternative, and then we explored why it wouldn't work in practice:

**What do you want to accomplish with the Live Coders?**
I'm in the process of starting to build a professional online persona. I'd love to use the Live Coders platform to increase my visibility within the Twitch community and hopefully provide some benefit for those following along.

**What do you want the Live Coders team to help you with?**
Ideally the Live Coders team can provide me with constructive feedback to improve the quality of my output. I'm also open to other approaches that you feel would bring benefit to both yourselves and my stream.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Sorry about the delay... From your Twitch channel, it doesn't look like you have been streaming about Software recently.

Are you still interested in joining the team?

**Comment by csharpfritz** [comment]
Closing with no response from @phunkren
