### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by MatissesProjects** [livecoders/Home#348]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/matissetec

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
yes, affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
List briefly here
mains Python, C#, java
also some web stuff for the obs tools I have
I use unity for game design too, and sometimes write code for blender addons.
Also blender for character design for 3d dancers program that chat can sort of control.

**Why do you write code on stream?**
briefly describe
I enjoy teaching others how to create interactions. I also have a lot of fun with trying to talk an idea out with others and get deeper integrations because of it. A few of my games are directly chat suggestions - Vehicle Hijacker, and the emoji game. To me that makes all the forgotten mid refactor because someone showed up times completely worth it!

**What is your favorite moment from coding on stream?  Share a clip if one is available**
briefly describe
Working on my new arcade project, where I have created a virtual space for twitch to come together into a location that we can 
all share and interact with. Its like a game engine, meets twitch interactivity, with a dash of streamer magic. https://www.twitch.tv/videos/1107581641

**What do you want to accomplish with the Live Coders?**
briefly describe
Meet more people that like programming streams, and other programming streamers. Also I have a few streamers I watch on the team that I have been basing my earlier content ideas from, which I hope can meld well with the crew.

Also some beta testers, I am constantly building out my system, and most people just like to interact with it. I was hoping this community might contain a few more people interested in pushing the boundaries of the projects.

**What do you want the Live Coders team to help you with?**
briefly describe
Meeting more like minded people. Beta testing new fun code im creating.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Sorry about the delay...  From your Twitch channel, it doesn't look like you have been streaming about Software recently. 

Are you still interested in joining the team?

**Comment by MatissesProjects** [comment]
Hey there!
Thank you looking forward to it.
