### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by egil** [livecoders/Home#349]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/egilhansen

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)

Twitch affiliate 

**What languages / frameworks / tools do you program in while streaming on Twitch?**

C#/.NET/Azure/Blazor/Visual Studio/Visual Studio Code/bUnit.

**Why do you write code on stream?**

To share knowledge while building open source. Have a strong focus on clean code principles, testing, etc.

**What is your favorite moment from coding on stream?  Share a clip if one is available**

I dont have a particular favorit, but I love engaging with viewers, answering questions, listening and learning from feedback.

**What do you want to accomplish with the Live Coders?**

Be part of an organized community.

**What do you want the Live Coders team to help you with?**

Become a better streamer, provider more value to folks.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... we would like to invite you to join the team!  Look for an invite email from Twitch with a link to join the Live Coders.  Once you have accepted the Team invite, I will send a whisper on Twitch with a link to join the team Discord.

Congratulations!

**Comment by csharpfritz** [comment]
Look for a message from Twitch with the subject "Live Coders just invited
you to join their team"


Jeff

**Comment by egil** [comment]
The link in the mail takes me to this page, and I cannot find anything like that on there:

![image](https://user-images.githubusercontent.com/105649/174780048-269df515-9f78-462d-b9fe-068f260738f8.png)
