### ISSUE TITLE
Application for Membership: TrezyCodes

### ISSUE THREAD

**Issue by trezy** [livecoders/Home#35]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/TrezyCodes

**What languages / frameworks / tools do you program in while streaming on Twitch?**
JavaScript
Node
React
Next.js
CSS
VS Code
https://codingame.com

**Why do you write code on stream?**
Because I want to be rich and famous? 😬 Nah, it's because teaching and mentoring has always been a huge part of my career, and streaming while I work on projects that I would normally work on in isolation is a great way to share my knowledge outside of work.

I also really enjoy social coding. Mob programming isn't really my thing, but having more opinions than just mine when building a project is something that I find really valuable. Plus I like people. ❤️

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Thus far, it's probably learning to walk on stream while I was trying to do some pixel art. 🤦🏻‍♂️
https://www.twitch.tv/trezycodes/clip/KindGrossZebraCoolStoryBob

**Comment by seekaplayer** [comment]
I believe Trezy would be an excellent person to have on the Live Coders Team. He is very helpful and very passionate about what he does!

**Comment by csharpfritz** [comment]
I really enjoy your stream, great stuff.  Approved!

Looks for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.
