### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by rickstergg** [livecoders/Home#352]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/rickstergg

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Yes

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Mainly Ruby and JavaScript, but currently learning Python!

**Why do you write code on stream?**
My stream is mostly educational, on Wednesdays I stream myself learning Chinese and while I already know how to program, it's fun being able to debunk some programming myths and also educate my viewers on programming and why it isn't scary!

**What is your favorite moment from coding on stream?  Share a clip if one is available**
My favourite moment is when a viewer said they wish they had me as a professor in college for one of their programming classes. I wish I had the clip, but here is the VOD: https://www.twitch.tv/videos/1014713899

**What do you want to accomplish with the Live Coders?**
I want to meet some cool people, share communities with them, and make sure programming can be done by anyone, and that programming is just as artsy as painting or drawing or playing the piano.

**What do you want the Live Coders team to help you with?**
Mostly to have a community to talk to about anything programming related, but also share and find solutions for programming specific issues on Twitch, such as how to get the audience more involved or providing useful links to read over and explain to viewers.

If you have any questions about this process, please email: info@livecoders.dev 

Thanks so much for your time and stay safe, take care everyone!

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... we would like to invite you to join the team!  Look for an invite email from Twitch with a link to join the Live Coders.  Once you have accepted the Team invite, I will send a whisper on Twitch with a link to join the team Discord.

Congratulations!
