### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by SimonWahlin** [livecoders/Home#353]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/SimonWSE

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Yes, affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
PowerShell
Bicep
Azure Functions

**Why do you write code on stream?**
It is a great way for me to sit down and do some coding for fun without procrastinating. At the same time I hope that my audience will learn from or be inspired by my content.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Don't have a specific moment, but anytime someone in the chat or after the stream tells me that they learned something from my stream I get really happy.

**What do you want to accomplish with the Live Coders?**
I want to share my passion for coding and the passion for sharing that passion.

**What do you want the Live Coders team to help you with?**
As a new streamer that don't know that many other streamers, getting to hang out with other streamers and learn from them would be great.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... we would like to invite you to join the team!  Look for an invite email from Twitch with a link to join the Live Coders.  Once you have accepted the Team invite, I will send a whisper on Twitch with a link to join the team Discord.

Congratulations!
