### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by pulcher** [livecoders/Home#358]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/haroldpulcher

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no) yes

**What languages / frameworks / tools do you program in while streaming on Twitch?**
C#, .NET, ROS, Visual Studio, Visual Studio Code, Arduino, Python, Raspberry Pi, Docker, GraphViz, and the list goes on.

**Why do you write code on stream?**
Attempting to build a community to learn about this Software/Hardware merger that makes me happy.  Share my passion and hope to convince others to try.  

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Most recently is it getting my GPS to respond to my ROS node on my recent robot: https://clips.twitch.tv/LuckyMistyTroutBleedPurple-vjm1awc-rUyCT85k
Having my followers inspire me for my next project.  We will be upgrading my Mr. Big Head to be smarter and more interactive.  All with a .NET worker on Linux.  Here is what that looks like: https://clips.twitch.tv/SquareBreakableBobaFUNgineer-kFHPXXa9WM4qqP5p.  It does a old school magic 8 ball thing.  Here is the github repo: https://github.com/pulcher/TalkingHead.  Checkout the comming upgrades in the my flow.dot: https://github.com/pulcher/TalkingHead/blob/main/Magic8HeadService/flow.dot

One of my most recent followers took it on themselves to learn some C# and give me some example of how I can improve the voice of MBH(Mr. Big Head): https://www.twitch.tv/videos/1088833462
Thought that we really cool.

Most of my streams at the moment have been in getting the Exomy(https://esa-prl.github.io/ExoMy/) to be autonomous.  Lots of software/hardware marriage type stuff going on there.

There are about 40 real people in my discord: https://disboard.org/server/800166520730026004
Helping people there as well.  

**What do you want to accomplish with the Live Coders?**
Be a part of some cool people.  Create some "Evil Geniuses".   Show others "How hard this isn't".

**What do you want the Live Coders team to help you with?**
Join in the team to further share my passion and knowledge.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... we would like to invite you to join the team!  Look for an invite email from Twitch with a link to join the Live Coders.  Once you have accepted the Team invite, I will send a whisper on Twitch with a link to join the team Discord.

Congratulations!
