### ISSUE TITLE
Application for Membership: jfversluis

### ISSUE THREAD

**Issue by jfversluis** [livecoders/Home#36]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream. ✅ 

**What is the URL for your Twitch channel?**
https://twitch.tv/jfversluis

**What languages / frameworks / tools do you program in while streaming on Twitch?**
It will be mainly Xamarin.Forms and anything that associates to that. I might have some other things on there but it will mainly be C#, .NET, Azure, ASP.NET

**Why do you write code on stream?**
I'm not streaming that long yet, but I just took on a role on the Xamarin.Forms team coming from the community myself. To stay in touch with my community friends, act as a bridge between the community and the team and share insights between both worlds is why I do it mostly. In addition, I have spoken to a lot of people who _want_ to contribute to the framework but feel they aren't good enough or simply can't get the environment up and running. I would like to enable and empower everyone to be able to contribute and show that we are only human as well.

I have done a lot of sessions at conferences all over the world which I really like. Now while adjusting to the new working situation that has gone to the background for now. To still be in touch I love the idea of live streaming/coding. I like to think of my streaming style more to be an improv remote conference session over people watching me code.

Long story short: mostly education, interacting with the community and hopefully a bit of entertainment as well.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I really loved my/our first stream. It was initiated after something called the #XamUIJuly. This initiative invited Xamarin.Forms developers to craft great looking designs or concepts and blog about it. Each day of the month a new blog by a different contributor. To close it off Javier (another XamForms team member), Steven (organizer of #XamUIJuly, community member and good friend) and myself went on a stream to go through all the posts and briefly address them. Very informal and fun and loved the interaction. The full archived recording can be seen here: https://www.youtube.com/watch?v=y8kmGSuyAC8

**Comment by csharpfritz** [comment]
Great interaction with chat and talking through your code.  Approved!

Looks for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.

**Comment by jfversluis** [comment]
Amazing, thanks! :)

Just accepted the invite!
