### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by brunosimon** [livecoders/Home#362]
Hello 👋
Some of my viewers recommended me to appli and it sounds like a great idea, so here I am.

**What is the URL for your Twitch channel?**
https://twitch.tv/bruno_simon_dev

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
WebGL, Three.js, Shaders, GLSL, GSAP, Webpack, VSCode, Blender, Substance Painter

**Why do you write code on stream?**
I do creative coding. It usually gravitates around 3D which is why I'm also using 3D softwares like Blender and Substance Designer.
Streaming is the perfect occasion to give life to all those ideas I have but never had time to do.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
When we get to the wanted result and the chat sheers up 😅

**What do you want to accomplish with the Live Coders?**
Be part of a the community, let my viewers discover more streamers like me and hopefully get more people to discover me 🙌

**What do you want the Live Coders team to help you with?**
Any advise would be greatly appreciate. I'm just starting in the streaming world and if it wasn't for my viewers who explain everything to me, I would be crying in a corner of my room, but I know there is a lot more to learn.

Sorry for the potential mistakes. English isn't my native language 🇫🇷

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... looks like you are no longer streaming.  If you resume streaming and are interested in joining, please re-open this ticket
