### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by markrendle** [livecoders/Home#363]
**What is the URL for your Twitch channel?**
https://twitch.tv/markrendle

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Yes (affiliate)

**What languages / frameworks / tools do you program in while streaming on Twitch?**
C#, .NET 6, ASP.NET Core, Blazor, MAUI

**Why do you write code on stream?**
I like teaching and sharing, but I especially like learning in front of people, so I try to do things that are new to me on stream
so people can learn with me. I do a lot of stuff with .NET preview releases so people can see what new stuff is coming and
how stable things are.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I tried Blazor for the first time on-stream and (Blazor creator) Steve Sanderson turned up and was watching and occasionally dropping hints, which was pretty awesome.

**What do you want to accomplish with the Live Coders?**
I want to reach more people and improve my streaming skills, and I hope I can help other members with things I'm good at too.

**What do you want the Live Coders team to help you with?**
I could definitely use some help with Twitch things like bits, rewards, clips, all that stuff, and any constructive feedback
on my streams would be a big help.

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... we would like to invite you to join the team!  Look for an invite email from Twitch with a link to join the Live Coders.  Once you have accepted the Team invite, I will send a whisper on Twitch with a link to join the team Discord.

Congratulations!
