### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by OikoumE** [livecoders/Home#367]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.
✔️

**What is the URL for your Twitch channel?**
https://twitch.tv/itsoik

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
#### Language:
- Mostly: 
    Python, Node, JavaScript,
- Some:
    HTML/CSS, C#
#### Framework:
- Some:
    Django

### Tools:
- Mostly:
    Raspberry Pi (Ubuntu server), VSC, PowerShell, Notepad & MSPaint
- Some:
    PyCharm, Blender, Twitch Developer Rig, Github CLI(rPi) & Desktop(win), Unity, Inkscape

**Why do you write code on stream?**
I have streamed since 2019, mostly games until oct 2020, upon which i started doing creative works (Blender/Art)
and discovered how awesome cummunity twitch has for creative minds.
When i started coding on stream the amount of likeminded people ive met, gotten help from and given help to has drasticly increased and i enjoy every bit of it.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
when many small things come together as a whole to make an actual functioning thing/service
when successfully deploying a new feature to the stream, that viewers can interact with. seeing them enjoy using it as much as i enjoyed making it
such as:
chat interaction with bot further interacting with overlays,
my own streamer dashboard,
making interactive games (via chat, channelpoint rewards etc.)
the collaboration of a project coming to completion thanks to help from viewers and my community
helping others, wether it be suggesting language or answering questions and raising confidence in others who migth be afraid of start coding.
- a clip of a recent success: https://clips.twitch.tv/BoxyYawningShallotResidentSleeper-PhgsMhEbFV8pBdoY 

**What do you want to accomplish with the Live Coders?**
I wish to be a part of a community of likeminded peers, grow as a streamer and as a person by interacting with, helping, getting help from people from all parts of life and the world

**What do you want the Live Coders team to help you with?**
Growing my community and channel,
Reaching more people, 
Allowing me into what i believe to be an awesome community,

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... we would like to invite you to join the team!  Look for an invite email from Twitch with a link to join the Live Coders.  Once you have accepted the Team invite, I will send a whisper on Twitch with a link to join the team Discord.

Congratulations!

**Comment by OikoumE** [comment]
Thank you so much! :D
