### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by novas1r1** [livecoders/Home#368]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/novas1r1

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Flutter/Dart/VSCode/Firebase

**Why do you write code on stream?**
I love writing code and I love sharing my passion, knowledge and experience with others. Twitch gives me the opportunity to build everything up like I want it. It's super creative and super authentic - I like that. Also there are not many Flutter streamers around yet. I'm training on speaking in front of people and try loosing my fear because I want to give some talks soon. Live-Coding on stream really helps me with that.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I have lots of favorite moments. Mostly they are because I was too dump to see something and chat helped me out :).
https://www.twitch.tv/videos/1155078845

**What do you want to accomplish with the Live Coders?**
Being the first Flutter/Dart coder in this community :)!

My overal goal is to be able to stream more often, guide my raids to cool people and exchange knowledge, tips and feedback with other streaming coders. This would help me, my channel and my community to grow and improve. I just want to spend more time with people having the same passion like me - I feel like Live Coders could be this place.

**What do you want the Live Coders team to help you with?**
Gathering some feedback, having a whole community of live-coding streamers who are willing to share their knowledge and help me improve.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... we would like to invite you to join the team!  Look for an invite email from Twitch with a link to join the Live Coders.  Once you have accepted the Team invite, I will send a whisper on Twitch with a link to join the team Discord.

Congratulations!
