### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by cpadilla** [livecoders/Home#37]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/rockzombie2

**What languages / frameworks / tools do you program in while streaming on Twitch?**
I usually code from neovim in the terminal in Arch linux using C++. Sometimes I'll do stuff in VSCode with python or javascript, but I usually try to stick to C++ as I'm trying to stream consistently the work on my game engine. I also have a pet project of getting FreeBSD installed and set up on my computer as well, so I'll stream some system setup occasionally.

**Why do you write code on stream?**
I really enjoy teaching and I hope that when I retire I can teach programming, maybe at a high school level. Coding while streaming is fun because it adds a social aspect to an otherwise anti-social hobby haha, so I really enjoy that aspect as well. I'm always impressed with the community's knowledge and how often they help in the debugging process.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I don't know if I have a single favorite moment, but in general I absolutely love when I accomplish the task I set out to do on the stream live. Especially if it's taken a while to debug or figure out, once I get it working I'm thrilled! And it's usually from help from chat. I also love it when I learn new things from much more experienced devs than I on stream.
Here's an example from when I was learning a new javascript framework and trying to make a twitch extension with it at the same time and I finally got it to work! https://www.twitch.tv/rockzombie2/clip/ThankfulAliveLyrebirdKippa

**Comment by csharpfritz** [comment]
That was great to see your clip!  Thank you for sharing.   Approved!

Looks for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.
