### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by Kiresorg** [livecoders/Home#371]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/erik_gross

**Are you a Twitch affiliate or partner?** Yes

**What languages / frameworks / tools do you program in while streaming on Twitch?**
I run a free code school. We learn HTML/CSS/JS, SQL and full stack development

**Why do you write code on stream?**
I love helping people break into tech

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Seeing someone new to tech work out for themselves why a compiler is needed

**What do you want to accomplish with the Live Coders?**
Help in creating a safe, effective way for people to learn tech. 

**What do you want the Live Coders team to help you with?**
Successful actions in the above 

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... we would like to invite you to join the team!  Look for an invite email from Twitch with a link to join the Live Coders.  Once you have accepted the Team invite, I will send a whisper on Twitch with a link to join the team Discord.

Congratulations!
