### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by FredyJabe** [livecoders/Home#374]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/fredyjabe
Im doing around 50/50 programming/gaming

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
- Visual Studio Code
    - C#
    - HTML
    - CSS
    - PHP
    - Javascript
- GameMaker
    - GML

**Why do you write code on stream?**
Working on my personal projects while chatting and showing things, enjoying chatting about gamedev in general.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
When coding something that works with the Twitch chat and viewers are testing it out right away.

**What do you want to accomplish with the Live Coders?**
Grow both myself and my channel, branch out with other developers.

**What do you want the Live Coders team to help you with?**
I'd like to know more developers, as my current social circle is far from this center of interest.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... we would like to invite you to join the team!  Look for an invite email from Twitch with a link to join the Live Coders.  Once you have accepted the Team invite, I will send a whisper on Twitch with a link to join the team Discord.

Congratulations!
