### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by ThindalTV** [livecoders/Home#375]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/thindal

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Yes, affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
C#, WebForms, MVC, JS/TS, Azure architecture, some WPF, hoping to get into Blazor & MAUI. A bit (too much) concentrated on the MS stack.

**Why do you write code on stream?**
I stream code to challenge myself and to share what I'm doing and what I know with others. When working, I'm known as the guy you can go to when something is giving you trouble, and I love being able to be the same to others. To really out myself, I have some problems with social anxiety with people I'm not familiar with, and streaming is a good middle ground that helps me deal with it and get better.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I'm a bit of a one trick pony in that as soon as someone mentions retro tech, I bring out the ZX Spectrum I have right behind me for bragging rights. Totally unrelated to what I really stream about, but it's kind of fun.

**What do you want to accomplish with the Live Coders?**
Reach more people and helping to make the software & gamedev community better. I'm also hoping to branch out and doing more than "just" coding on stream, and I think that expanding my commitment is a good first step. I would also love to do some collaborative streams or projects and make something with others in the same community.

**What do you want the Live Coders team to help you with?**
Feedback, ideas and reach basically. Sharing knowledge and working together to make the community even better and available than it was before.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Apologies for the delay in reviewing... we would like to invite you to join the team!  Look for an invite email from Twitch with a link to join the Live Coders.  Once you have accepted the Team invite, I will send a whisper on Twitch with a link to join the team Discord.

Congratulations!
