### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by EngstromJimmy** [livecoders/Home#376]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/CodingAfterWork

Past broadcasts are available on YouTube.
http://youtube.com/CodingAfterWork

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Yes, Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
C#, .NET, Blazor, RavenDB, CSS, Visual Studio, Visual Studio Code, (UX, Accessibility)

**Why do you write code on stream?**
We love to share knowledge it's a great way to learn and give back to the community.
Having discussions with fellow developers is also really valuable.
It is a great way actually take time to sit down and code on those open-source projects.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Every moment when someone (viewer, me, or Jessica) learns something new, that moment of realization.
We try to be very inclusive and beginner-friendly as well as deep dive into making real-world applications.
We are two persons with different coding experiences, which lends itself to good discussions and seeing things from different perspectives.

**What do you want to accomplish with the Live Coders?**
Making our channel the best it can be with the collective knowledge from the Live coders' team.
Support other live coders in what they would like to achieve.

**What do you want the Live Coders team to help you with?**
Growing our mutual community.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Of course!  You've helped the team previously and we'd be happy to have you!

**Comment by csharpfritz** [comment]
We would like to invite you to join the team!  Look for an invite email from Twitch with a link to join the Live Coders.  Once you have accepted the Team invite, I will send a whisper on Twitch with a link to join the team Discord.

Congratulations!
