### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by domi877** [livecoders/Home#377]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/trollhanks

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Yes, I am an affiliate.

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Current project: Java, Spring Boot, PostgreSQL, Hibernate
General: JS (Ember.js), Python, SQL, Cloud
Tools: git, VS Code, Postman

**Why do you write code on stream?**
Since I am programming in my free time anyways, I thought it would be cool to document the progress I made etc.
Addiitonally it is super cool to chat with people and learning from each other

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Getting to know what kind of languages my viewers are currently learning and why they are using it.

**What do you want to accomplish with the Live Coders?**
I think it would be cool when all the viewers that are interested in different kinds of programming languages/ tools etc. have different and specific contact persons in a community.

**What do you want the Live Coders team to help you with?**
I think I can still upgrade my stream experience and some help/ tips would be really cool.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
I don't see any recent videos.  Are you still streaming?

**Comment by csharpfritz** [comment]
Closing with no response
