### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by codercatdev** [livecoders/Home#378]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/codingcatdev

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Yes

**What languages / frameworks / tools do you program in while streaming on Twitch?**
JavaScript / Next.js, Svelte, Node.js / Firebase, Appwrite, anything OSS 😄 

**Why do you write code on stream?**
We love creating a community of coders. We want to show off new technologies and embrace those in the same industry.
This helps us to extend into our community further from https://codingcat.dev and our weekly podcast where we bring on experts. Once a week we are now bringing those same experts on to build sample applications live streamed.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
It was so fun to see the joy on Brittney's face on this one
https://clips.twitch.tv/JollyVivaciousPeafowlAMPTropPunch-Wnmzb3Ts6of-8odJ

**What do you want to accomplish with the Live Coders?**
We are still new to Live Coding, although we have run our podcast for a few years now. So it would be great to be part of the amazing community of live coders. Getting help with thought leadership, swag and interactive activities for our subs would be great.

**What do you want the Live Coders team to help you with?**
Team support with event promotions and raids. Help us fix what we are doing wrong on Twitch.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
I don't see any recent videos.  Are you still streaming?
