### ISSUE TITLE
Alphabetize List of Streamers

### ISSUE THREAD

**Issue by ardalis** [livecoders/Home#38]
The list is pretty long and has no visible order to it - I suggest alphabetizing by stream name unless someone has a better idea (perhaps by number of subs/followers?). But random sequence seems random.

**Comment by lannonbr** [comment]
I think alphabetized would be a good idea. No picking favorites or putting people on different pedestals that way

**Comment by csharpfritz** [comment]
Alphabetized with some tags around topics with it



Jeff

**Comment by lampewebdev** [comment]
Maybe some streamers have some topic they are focusing on?

So having like 2 or 3 columns.

For example with Game dev, Web dev, Hardware dev

and then they could be alphabetized.

I would not go by the follower count, there are two problems with this:
* Maintainability
* Streamers would be chosen by count, not by topic and interests

**Comment by garethhubball** [comment]
I would try to make it random and randomise it often, so that neither your name nor your follower count could be used to raise one up the list and give one arbitrary ways to game the system.

**Comment by LuckyNoS7evin** [comment]
Removed the markdown converter in #261 reason is to keep a single page for the team rather than multiple sources. as livecoders.dev didn't have a site previously this was needed, it's no longer an issue
