### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by samkitkat** [livecoders/Home#380]
**What is the URL for your Twitch channel?**
https://www.twitch.tv/samkitkat

**Are you a Twitch affiliate or partner?**
yes

**What languages / frameworks / tools do you program in while streaming on Twitch?**
javascript, reactjs, html/css, 

**Why do you write code on stream?**
keeps me accountable to have others watching. also I get to learn a bunch from chat or sometimes I happen to share something cool with them!

**What is your favorite moment from coding on stream?  Share a clip if one is available**
flexbox froggy, throwback 90's themed stream, hackermanz themed stream

**What do you want to accomplish with the Live Coders?**
be part of a positive and encouraging environment where we can all grow personally and professionally

**What do you want the Live Coders team to help you with?**
having a space where we can all learn and grow with each other

**Comment by csharpfritz** [comment]
Looks like you've got a nice growing community.  Look for an invite from Twitch and then I will send a Twitch DM to invite you to the team Discord.

Welcome to the team!
