### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by PabloCodingg** [livecoders/Home#381]
**What is the URL for your Twitch channel?**
https://twitch.tv/pablocoding

**Are you a Twitch affiliate or partner?**
Yes, partner

**What languages / frameworks / tools do you program in while streaming on Twitch?**
I mainly do Lua programming on the FiveM platform (GTA V Framework) but also Java for third party applications.

**Why do you write code on stream?**
I want to share my passion and promote programming to viewers and answer their questions.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I don't necessarily have a favorite moment but I will say that it is the fact of being able to answer the questions of the viewers but especially to give the desire to some to start and, later, to see that these same people make code their passion or their hobby.

**What do you want to accomplish with the Live Coders?**
I think that the more we are, the more we can democratize the subject of programming on Twitch

**What do you want the Live Coders team to help you with?**
I would especially like to have advice or simply evolve with you to promote development.

**Comment by csharpfritz** [comment]
Hey Pablo, it looks like you're not coding on Twitch any longer.  

Let us know how your channel grows and if you return to writing code on stream
