### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by agjs** [livecoders/Home#383]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/programmer_network

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
React, Node (Fastify), Golang, Docker, Kubernetes, GCP, AWS

**Why do you write code on stream?**
I'm developing a social networking platform for developers, with the community. I've also spent 5.5 years working as a teacher, and I enjoy sharing knowledge.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Generally seeing people learn. I don't have any clips to show.

**What do you want to accomplish with the Live Coders?**
Try to get more people into the stream, and spread the word. And of course, maybe get to know some of you folks, if you are into that. On top of that, maybe hear some tips and tricks from some of you, who have more experience in streaming then myself. 

**What do you want the Live Coders team to help you with?**
Spread the word about the stream, get some insights, and stuff like that. 

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
It doesn't look like you are actively streaming...  closing for now.  If you return to streaming and are interested in joining the team, please re-open this issue

**Comment by agjs** [comment]
> It doesn't look like you are actively streaming... closing for now. If you return to streaming and are interested in joining the team, please re-open this issue

Hey @csharpfritz. I'm not quiet sure what you mean, I'm streaming nearly 5 times a week, sometimes even 7 days a week.
