### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by iandouglas** [livecoders/Home#384]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/iandouglas736

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
I'm an affliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Python, but mostly about tech interview preparation and career advancement

**Why do you write code on stream?**
I love the idea of "learning in public" but also to share experience of being a long-time industry developer (26+ years) and why we do things a certain way.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I've had so many people come back to the stream and share that following my interview prep tips helped them get a job in the tech industry. There's nothing better than that, except ONE person got a job AND started mentoring back at their school afterward.
https://youtu.be/5wYX_3aARCQ?t=2223

**What do you want to accomplish with the Live Coders?**
To be part of a bigger community whose goal is to promote knowledge with other people, where we can help each other be better as streamers and as people, and to build others grow around us.

**What do you want the Live Coders team to help you with?**
I could use help with audio/lighting and more engagement.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Your content is GREAT and we like your goals.  Look for an invite from Twitch and then I will send a Twitch DM to invite you to the team Discord.

Welcome to the team!
