### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by TomCats** [livecoders/Home#385]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/TomCat

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Yes

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Lua, Java, JavaScript

**Why do you write code on stream?**
I create addons that work in the game World of Warcraft

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Every day that I get to code on stream is my new favorite moment

**What do you want to accomplish with the Live Coders?**
Network with and share viewers with other live coders

**What do you want the Live Coders team to help you with?**
Good question.  Aside from networking and being able to share viewers who are interested in watching live coding?  I don't really have anything else in mind but would be interested in seeing what else there is!

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
I was just watching your channel for a bit today and enjoyed your coding approach with the cat avatar. 

Look for an invite from Twitch and then I will send a Twitch DM to invite you to the team Discord.

Welcome to the team!
