### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by jessicaSz** [livecoders/Home#386]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://www.twitch.tv/gamedevlady

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Im a Twitch affiliate.

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Unity C#

**Why do you write code on stream?**
I love sharing my coding journey with other people. My main activity was uploading videos on TikTok and Youtube,
but the experience of coding actually together on stream is so cool! People can also learn so much new stuff from me, 
and even help me with my issues!

**What is your favorite moment from coding on stream?  Share a clip if one is available**
When we disscuss about some features, coding principles of other very impornant but not common things!

**What do you want to accomplish with the Live Coders?**
I would like to join to other coders because i feel lonely on Twitch. like im a freelancer not
a part of something cool.

**What do you want the Live Coders team to help you with?**
Maybe some tips what can I improve?

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Are you still actively streaming?  We'll check back with your application

**Comment by csharpfritz** [comment]
Closing with no response
