### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by DTierneyDev** [livecoders/Home#387]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/mlgesus_tv

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Unity C#

**Why do you write code on stream?**
I am developing the first game that I plan to release commercially(Gnome Post On Sundays). I decided that to keep me motivated, gain ideas and to teach/learn from others that I would stream my progress each week. Hopefully providing some entertainment to viewers in the progress.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
My favourite moments are when I get a feature working after planning and implementing it on stream. As the viewers get to see the whole progress and possibly learn something along the way, and I get to feel good about making something new that works.

Close second would be when I mess with values and put them to something ridiculous to see just how broken things can get, cars flying through walls etc.

**What do you want to accomplish with the Live Coders?**
I am new to Game Dev on twitch so I'm hoping to join a community with similar interests. That way I can learn from them about this new area, and maybe even get some tips on the programming side of things. Also, since I've been streaming for a while I could share tips with others.

**What do you want the Live Coders team to help you with?**
I would love help with tips on the best ways to get exposure in this new (for me at least) area of twitch, and how to build a brand around it. Also, possibly some tips on how to market a game, as I currently have 0 experience in that area. Finally, it would be great to get feedback/help if I get stuck, from some professional coders as I progress through development on my game.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
I enjoy how you're describing the steps as you build with Unity.  Look for an invite from Twitch and then I will send a Twitch DM to invite you to the team Discord.

Welcome to the team!
