### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by nickytonline** [livecoders/Home#389]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/nickytonline

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)

Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
TypeScript, JavaScript, HTML, CSS, and Rust (sometimes)

**Why do you write code on stream?**

To learn stuff and to meet people in the tech space

**What is your favorite moment from coding on stream?  Share a clip if one is available**

There are many, but this was a fun recent one. https://www.twitch.tv/videos/1677726236?filter=highlights&sort=time

**What do you want to accomplish with the Live Coders?**

meet more folks, potentially collab, and continue to build out my stream, and just all around have fun

**What do you want the Live Coders team to help you with?**

pretty much the same as the previous answer

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Your content looks great! Look for an invite from Twitch and then I will send a Twitch DM to invite you to the team Discord.

Welcome to the team!
