### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by wesdollar** [livecoders/Home#394]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/dollardojo

**Are you a Twitch affiliate or partner?** (Your application will be automatically rejected if the answer is no)
Affiliate

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Typescript, Express, React, Remix, Next, Prisma, Prettier, Jest, Eslint

**Why do you write code on stream?**
I write code on stream, hoping to help others grow or inspire them to become engineers. I mentor many engineers IRL, but I wanted to maximize my reach by giving back to the community and impacting the lives of others, so I turned to Twitch to share my craft and experience. 

**What is your favorite moment from coding on stream?  Share a clip if one is available**
It's not engineering-related, but we played happy birthday for my wife on stream. Chat joined in on the celebration and brought a huge smile to her face. Also engineering unrelated, Chat and I had a wonderful discussion on mental health. It's been so amazing to connect with others in the community who are autistic or face other mental health challenges. I think it's been helpful for some community members to see that it is possible to have a very successful career in this industry despite the constant battle with our brains.

**What do you want to accomplish with the Live Coders?**
I want to be in communities where I can touch people's lives and help them achieve their dreams. 

**What do you want the Live Coders team to help you with?**
I can't see my blindspots – no one can. I'm always looking for mentors. The only we grow is by growing together. A rising tide lifts all ships.

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Looks like you've got a nice growing community.  Look for an invite from Twitch and then I will send a Twitch DM to invite you to the team Discord.

Welcome to the team!

**Comment by wesdollar** [comment]
Thanks so much! Looking forward to getting to know you all!

**Comment by wesdollar** [comment]
Hi Jeffrey,

I haven't received anything from Twitch. Do you need anything from me?

Thanks!

**Comment by csharpfritz** [comment]
I've re-sent the invitation... you should receive an email shortly


Jeff
