### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by jlengstorf** [livecoders/Home#41]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/jlengstorf

**What languages / frameworks / tools do you program in while streaming on Twitch?**
JavaScript, React, Gatsby, Node, lots of CMS and SaaS tools, occasionally design tools like Figma.

**Why do you write code on stream?**
I started by livestreaming my daily work, but over time it’s grown into a kind of TV show where I pair program with people from the community to build something together. 

**What is your favorite moment from coding on stream?  Share a clip if one is available**
One thing that I got really excited recently about was learning what the Netlify CLI can do. https://www.twitch.tv/videos/435353535

**Comment by csharpfritz** [comment]
Looks for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.
