### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by YunaSw** [livecoders/Home#414]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.
Also ensure that your vods are not sub only.

**What is the URL for your Twitch channel?**
https://twitch.tv/YunaSw

**Are you a Twitch affiliate or partner?** I am affiliated

**What languages / frameworks / tools do you program in while streaming on Twitch?**
- my native language is Portuguese, but I speak English and a little Spanish.
- I use obs streamlabs to stream on twitch.

**Why do you write code on stream?**
I want to grow as a streamer and become a Twitch partner

**What is your favorite moment from coding on stream?  Share a clip if one is available**
(https://www.twitch.tv/yunasw/clip/ExuberantComfortablePuddingDendiFace-wPswcUmSPVohXqm2)

**What do you want to accomplish with the Live Coders?**
to grow up and help each others

**What do you want the Live Coders team to help you with?**
to grow up as a streamer

If you have any questions about this process, please email: info@livecoders.dev

**Comment by csharpfritz** [comment]
Thank you for the application.  We don't see any streams in the Software and Game Development space, a category that we expect to see folks streaming in that are working with software

Closing for now.  If you do have interest in software in the future, we'll be happy to review an application at that time
