### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by douglascorrea** [livecoders/Home#42]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream. I did an application before, by my GH markdown removed the last underscore from my channel url which points to a different channel, not mine.

What is the URL for your Twitch channel?
[https://twitch.tv/douglascorrea_](https://twitch.tv/douglascorrea_)

What languages / frameworks / tools do you program in while streaming on Twitch?
Currently I'm streaming Rust, I'm building a gameboy emulator live from scratch with support from the viewers of the channel.
But I also plan to stream some hardware stuff like trying to compile that GB emulator in a SAMD51 microcontroller and those type of things

Why do you write code on stream?
I'm still learning Rust, and I would like to make a complete project from scratch to feel that I'm able to do something real with the language.
Then, to avoid losing the focus and stopping the project in the middle, I decided to expose myself in the stream, and that was the best choice I would make.
Now I not only keep working for me but also for those who follow my streams. I really feel like I own them to finish the project.

What is your favorite moment from coding on stream? Share a clip if one is available
When I go the Nintendo logo into the emulator screen:
https://clips.twitch.tv/FurryQuaintSnakeAMPEnergyCherry

**Comment by csharpfritz** [comment]
The project you're working on looks REALLY neat... but it looks like you haven't been streaming recently.

Holding for now

**Comment by douglascorrea** [comment]
It is fair, I will get back to it soon (next weeks), then I will send an update here

**Comment by LuckyNoS7evin** [comment]
Closing, hasn't streamed since Sept '19
