### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by lampewebdev** [livecoders/Home#43]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://www.twitch.tv/lampewebdev

**What languages / frameworks / tools do you program in while streaming on Twitch?**
I mostly do web development and on stream, I'm trying to do some game development, since I always wanted to create a zelda: link to the past like game. Javascript, node, reactjs, svelte, meteorjs, vscode, css, html, phaserjs (game engine), git

**Why do you write code on stream?**
I really enjoy educating people and interacting with them. I started to tutor people back when I was a student at university myself, today I'm a Senior developer and teach junior devs. Also interacting with people is fun and I can work on my pet projects. Also, I saw @clarkio streaming and it looked like fun. So yeah he kind of inspired me to start streaming

**What is your favorite moment from coding on stream?  Share a clip if one is available**
My favorite until now is when a viewer asked me if I could help him with an "app" that he can not compile and if I know Java. Of course, I tried to help him so I asked for the code. He only was willing to send me a screenshot. After looking at the screenshot it was clear to me that he wanted to compile some sort of cheating software for counter strike go. It was a funny conversation with him. Sadly I have not clipped it.

**Comment by csharpfritz** [comment]
It looks like its been quite some time since you've been streaming.

Holding for now

**Comment by lampewebdev** [comment]
@csharpfritz yeah sorry for that I'm on vacation in China right now until the end of the month and it is hard to stream from here.

**Comment by csharpfritz** [comment]
No worries...  we'll check back later.


Jeff

**Comment by LuckyNoS7evin** [comment]
Closing, hasn't streamed since Sept '19
