### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by faniereynders** [livecoders/Home#44]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/faniereynders

**What languages / frameworks / tools do you program in while streaming on Twitch?**
C#, .NET, Azure, and ad-hoc cool technology experiments

**Why do you write code on stream?**
As an architect I don't get to code as much as I used to. Live coding on Twitch helps me relax and forces me to keep my hands dirty and updated with the tech. Furthermore, I am passionate about teaching others and sharing knowledge.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
It is always special when I get a follow, raid or experience a Streamception of other streamers hosting me, so I run the whole screen full of Kappagen emotes. Do not have a specific clip of it, but this one's quite close -> https://www.youtube.com/watch?v=xbEDeIy5aC0&t=10m33s

**Comment by csharpfritz** [comment]
Approved and invited to the team
