### ISSUE TITLE
Fr33maan - Application for Membership

### ISSUE THREAD

**Issue by Fr33maan** [livecoders/Home#45]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/fr33maan

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Mostly JavaScript with Node.js, PIXI.js and [DreamEngine](https://github.com/dreamirl/dreamengine).  
Some SQL and Redis too.

**Why do you write code on stream?**
I really enjoy interact with viewers, I'm lucky to have a community of skilled developers and both students. It creates a great synergy!

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I really don't have favorite moment, I enjoy when we speak about gameplay, I enjoy when everyone is quiet and I just write code quickly and efficiently, I enjoy when we share thoughts on life at the end of the stream. All the time spent with my community is a great moment.

Thanks @csharpfritz for your review !

**Comment by csharpfritz** [comment]
Your stream looks good.

Looks for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.
