### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by tbd-develop** [livecoders/Home#46]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/tbdgamer

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Mainly C#/Javascript/Angular but been expanding horizons to React

**Why do you write code on stream?**
I love software development. I feel passionate about writing good software and feel that by streaming what I do, I can engage more people in discussion and we all in turn learn more. It's great to share my experiences, my opinions and see the experiences and opinions those in my chat have. Whether it be learning about TDD or introducing Auth0 and having my chat hand hold me, every stream is rewarding. 

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I can't find a clip, but my favorite moments have been sharing the "Yes!.. it works!" moments with people in my stream. I look forward to sharing those moments on every stream

**Comment by RelevantJesse** [comment]
Great guy right here!

**Comment by csharpfritz** [comment]
Agreed @RelevantJesse - @tbd-develop is a great member of our community and I'm happy to invite to be a member of the Live Coders team.

Looks for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.
