### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by gamedolphin** [livecoders/Home#47]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://www.twitch.tv/infinitesolenoid

**What languages / frameworks / tools do you program in while streaming on Twitch?**
I am streaming the creation of a podcast app using react native right now. I plan to do a game engine stream and a unity 3d stream in the future as well. 

**Why do you write code on stream?**
I am working on creating a kick-ass portfolio and what better way to document the whole thing. I would also like to (eventually)  have live feedback but I just started out and I think that would take some time. I am looking forward to it though.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I am only 3 days in, and my favorite moment happened today when a bunch of monkeys(?) created a ruckus in the park right outside my window. I think you can catch that around the end of the stream here - https://www.twitch.tv/videos/485248212. I had to pause and catch myself for a good minute or two.

**Comment by csharpfritz** [comment]
I see no recorded videos and qualified applicants are Twitch Affiliates or Partners.

Declining, but you are welcome to re-apply in the future
