### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by judah4** [livecoders/Home#48]
**What is the URL for your Twitch channel?**
https://twitch.tv/cookiedragon4

**What languages / frameworks / tools do you program in while streaming on Twitch?**
C#, Unity3d

**Why do you write code on stream?**
I make video games on stream! I stream game development with Unity, coding with C#, and sometimes 3d modeling with blender.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Probably when previous viewers watch again and ask questions. I'm kind of just mumbling through code but specific questions can be fun to answer. More favorite moments include visual bugs that are fun to laugh at.

**Comment by csharpfritz** [comment]
Live Coders team members engage their chat and explain what they're working on as they're streaming.  I see you have low viewership currently, and that is contributing a bit to that interaction.

Holding for now

**Comment by LuckyNoS7evin** [comment]
Live Coder Intern - Nurturing Program - Acceptance

With The Live Coders growing rapidly the team introduced a minimum viewership and other criteria. 

- Interactivity
- Inclusivity
- Community
- Teaching
- Learning

You are invited to become a Live Coders Intern, not a part of the full Twitch team (some of the benefits are excluded) you will be invited to The Live Coders Discord server where you can learn from the rest of the team. (restricted access not all channels)

Please contact me to get your access

- @TheS7evin -> Twitter
- LuckyNoS7evin#0001 -> Discord
- LuckyNoS7evin -> Twitch
