### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by rjgtav** [livecoders/Home#49]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/rjgtav

(Note: I just returned from a 1 month pause of streaming, but my stream archive is available on my YouTube channel https://www.youtube.com/user/rjgtav)

**What languages / frameworks / tools do you program in while streaming on Twitch?**
I usually do Web Development and explore some of the latest trends such as PWAs and WASM. Currently, I'm working with Angular 7, Python and Postgres.

**Why do you write code on stream?**
In 2018 I've launched [tos.guru](https://tos.guru), an open-source database/wiki for Tree of Savior, a MMORPG on Steam. Since then I've been streaming all of its development, which has made it a much more relaxing and enjoyable experience.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I enjoy most of my streams, except on those weak days when barely no one comes by, as I love discussing about programming with others and I'm also able to get immediate feedback when designing a new feature

**Comment by csharpfritz** [comment]
You're building some neat projects, but I don't see any engagement with the chat room.

Live Coders team members teach and engage with chat during their streams.

Holding for now

**Comment by LuckyNoS7evin** [comment]
No stream since December 2019
