### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by copperbeardy** [livecoders/Home#50]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://www.twitch.tv/copperbeardy

the stream in mature-rated as I do swear on occasion but working on reducing the amount.

**What languages / frameworks / tools do you program in while streaming on Twitch?**
C#,
Xaml,
some javascript,
.Net Core,
Entity Framework Core
Xamarin.Forms,
Asp .net core,
Various Azure services including AzureB2c,
Visual Studio Enterprise 2019,
Git Kracken,
PostMan,
Android Emulators,
MS whiteboard,
Twilio quest 3,
Twilio Developer Kit For BroadBand IoT 
some Orchard Core CMS (asp.net core, based cms)
Azure Data Studio

**Why do you write code on stream?**
I write code and do IoT on stream, so I can learn and grow as a developer and hopefully, I can ly teach viewers what I know and Learn from the viewers as well. streaming coding also helps me gain focus and perspective on what I am doing, and the engagement with viewers helps to refine and generate ideas for the development of what I am working on.   I also have mental health problems, Acute Anxiety and depression, and want people to know that having mental health problems is not a barrier to coding and development. I enjoy promoting learning of all varieties and enjoy sharing my knowledge of learning resources and approaches. I have also watched a large number of developer streams and the community is something I have very much enjoyed and want to be a part of giving that same experience to other people.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
briefly describe
my favourite moments are whenever viewers have enjoyed the stream. but my favourite moment of something I have stream was just today when doing the TwilioQuest IoT quest and getting several images to display on the 1.12inch microdisplay, amazing feeling working with tech I have never used before streaming. https://www.twitch.tv/videos/487633483

**Comment by csharpfritz** [comment]
I LOVE your attitude on stream in throughout our Live Coders community.

Looks for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.
