### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by trevorblades** [livecoders/Home#52]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/trevorblades

**What languages / frameworks / tools do you program in while streaming on Twitch?**

- JavaScript
- CSS
- React
- Node
- Gatsby
- GraphQL
- Apollo
- Postgres
- Heroku
- Sketch

**Why do you write code on stream?**

I love writing code in my spare time, and I spend a lot of my spare-time coding sessions learning new things. I thought that it would be fun to work on my projects and learn new things in a more public space, and I happened to really enjoy the sense of community and "learning together" that code streaming offers both me and my viewers.

**What is your favorite moment from coding on stream?  Share a clip if one is available**

On a recent stream, I was about to wrap up the stream and shut it down, but I was encouraged by one of my chatters to keep going and in a burst of YOLO inspiration I decided to keep pushing and saw the feature that I was working on through to completion. Clip: https://clips.twitch.tv/BlushingWittyKoalaDansGame

**Comment by csharpfritz** [comment]
You've got a GREAT stream!  I really enjoy your engagement with chat.

Looks for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.
