### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by zorchenhimer** [livecoders/Home#53]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/zorchenhimer

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Mainly 6502 Assembly for the Nintendo Entertainment System with some Go for custom tools.

**Why do you write code on stream?**
It's a lot of fun and it keeps me motivated to work on projects.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
When things break and make a mess:
- https://clips.twitch.tv/TangentialBoxyCucumberPeteZaroll
- https://clips.twitch.tv/GoodThankfulGaurOpieOP

**Comment by csharpfritz** [comment]
I really enjoy watching your development with the NES and chatter with your chat room.

Looks for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.
