### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by rhymu8354** [livecoders/Home#54]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/rhymu8354

**What languages / frameworks / tools do you program in while streaming on Twitch?**

* C++, including custom-made:
  * HTTP (web server, client)
  * Hashing (SHA-1, SHA-2, HMAC, PBKDF2, HOTP/TOTP)
  * JSON
  * Raft Consensus
  * SASL/SMTP (authentication and e-mail)
  * Twitch messaging (chat)
  * WebSockets
* JavaScript
  * React
  * Redux
  * Phaser
* Lua
* Python

**Why do you write code on stream?**

* I get a lot more feedback streaming than I ever did at my previous full-time job of 20+ years.
* Live-streaming forces me to make a plan, stay organized, and get motivated.
* I enjoy helping others who have questions about programming, or could benefit from watching how I develop code.
* I get a lot of practice speaking: describing what I'm doing, answering questions.
* Viewers of my channel share lot of interesting things: different points of view, useful tools I didn't know about before, and their own projects which I enjoy seeing.
* Facing the community and their criticism, even the trolling, helps me "grow a thicker skin".

**What is your favorite moment from coding on stream?  Share a clip if one is available**

I was being hosted by Adam13531 one day, and he logged into my game as I was working on it.  I don't remember why exactly (maybe it was to demonstrate making changes to the game while live?) but I gave Adam's character the ability to swim.  Almost immediately, Adam shot across the water and killed a special named NPC named "Slimy" that I had been using for tests.  RIP Slimy!  :FeelsBadMan: :LUL:  Anyway, it was funny, but it also highlighted the kind of viewer interaction I'm shooting for with my game, where viewers can interact with the stream and the game in a more integrated way than most games.

Watch the clip here:  https://www.twitch.tv/rhymu8354/clip/WittyCourteousBadgerNomNom

**Comment by csharpfritz** [comment]
Great interactions and very interesting game development.  Looks for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.
