### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by zerratar** [livecoders/Home#55]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/zerratar

**What languages / frameworks / tools do you program in while streaming on Twitch?**
- C#
- Unity3D
- Maya
- ASP.NET dotnetcore
- MSSQL Server for some stuff
- TypeScript
- JavaScript
- HTML5
- CSS

**Why do you write code on stream?**
I love coding and talking to people! Especially interacting with people! So on my streams I create Twitch interactive content. Including games while having stream intrusive commands (meaning: people can interact with my keyboard, mouse and monitor. I screw myself over a bit there)f

**What is your favorite moment from coding on stream?  Share a clip if one is available**
briefly describe
https://www.twitch.tv/zerratar/clip/SincereSpicyKeyboardOSfrog

https://www.twitch.tv/zerratar/clip/IcyCautiousChamoisTwitchRPG

I dont know what to say. But Things like this happens all the time. Even at the moment when I'm typing this message. Please forgive any forgotten 'f's in this appflication. Shieeet

**Comment by csharpfritz** [comment]
I really enjoy watching your stream, you have a lot of fun with your code and chat room.

Looks for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.
