### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by pfwd** [livecoders/Home#56]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/howtocodewell

**What languages / frameworks / tools do you program in while streaming on Twitch?**
- PHP / Symfony / Laravel / Slim / composer
- Python / Flask / Django / pip
- Micro Python
- Docker
- Linux / Bash / Zsh
- JavaScript / Nodejs / NPM / Gatsbyjs / React 
- HTML
- CSS / Tailwind
- Jenkins
- PyBoard / Node MCU

**Why do you write code on stream?**
 I am a coding teacher, podcast host, freelance web developer and speaker. I learn loads from teaching others.  This is my way to give back to the community.  I host the [How To Code Well YouTube channel](http://youtube.com/howtocodewell) and [Podcast](http://howtocodewell.fm).  On the Podcast I interview developers and members of the industry. I really enjoy learning and sharing knowledge.  

**What is your favorite moment from coding on stream?  Share a clip if one is available**
- Flick (My cat) tore down the green screen whilst I was streaming
- The chat helped me come up with some talk ideas.
- The private messages I get from the community that remind me why I do this and inspire me to contiune.

**Comment by csharpfritz** [comment]
You've got a lot of really great content.  Looks for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.
