### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by AlbericoD** [livecoders/Home#57]
**What is the URL for your Twitch channel?**
https://www.twitch.tv/albericod

**What languages / frameworks / tools do you program in while streaming on Twitch?**
I program things that twitch chat can interact with me, twitch bots, discord bots, reddit bots, alexa skills, twitch extension, javascript, html, css and maybe some js framework but it's not the focus

**Why do you write code on stream?**
In my country Brazil, the profession of programmer is something that people believe is very far from reality, so I create simple environments of contribution and resolution to solve for one to two weeks, this encourages people to rethink the profession. 8 days ago I started broadcasting and we are already going to our second project with the help of chat https://github.com/AlbericoD/OBS-widgets

**What is your favorite moment from coding on stream?  Share a clip if one is available**
hahahaha, there were people who made a video of us opening some gifts that amazon sent me
https://www.twitch.tv/albericod/clip/FaithfulSmoggySkunkKappaWealth?filter=clips&range=7d&sort=time 

Although I can read and write English, I still need to train my conversational English a lot, but my twitch chat is very responsive if you are from anywhere in the world! <3

**Comment by csharpfritz** [comment]
You're off to a great start with streaming, and I'd like to invite you to join the team!

Looks for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.
