### ISSUE TITLE
Becoming a Live Coders member

### ISSUE THREAD

**Issue by ionside** [livecoders/Home#58]
Hi there,

I've been watching a few Twitch channels that stream under the Live Coders banner. I'd love to be a part of it, if possible?

My Twitch channel is [https://www.twitch.tv/ionside](https://www.twitch.tv/ionside). I stream coding and animation predominantly in Blender and Unity. C# and Python.

Kind regards,
Robert

**Comment by csharpfritz** [comment]
There’s an issue template for an application to join the team. Please use that format
