### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by ionside** [livecoders/Home#59]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/ionside

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Python (Blender scripting), C# (for Unity project), Xamarin (Visual Studio).

**Why do you write code on stream?**
I do full development whilst streaming. It helps me keep focused on production, transparent, and build a network of like-minded friends

**What is your favorite moment from coding on stream?  Share a clip if one is available**
In a stream, I helped a follower write an automated rig for fracturing in Blender. in turn, he helped me with a projectile formula that was better than the one I designed.

**Comment by csharpfritz** [comment]
You've got a fun stream, and I enjoy watching you build animations in Blender.  I definitely want to learn more about Blender, and your stream looks like a good place to chat and discuss more.

Looks for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.
