### ISSUE TITLE
I'd like to become a member

### ISSUE THREAD

**Issue by qualitycoder** [livecoders/Home#6]
I would like to become a member of your team.

My Twitch handle is QualityCoder (https://www.twitch.tv/qualitycoder)

I made affiliate status about 1.5 years ago (January 2018, if I remember correctly).
The majority of my streams are programming streams (some Python, some PHP, some just general knowledge answer/question educational type)

Right now, I am working on creating a Discord/Twitch chatbot, but have many plans for future projects. 

I do games every now and then, but it's uncommon. When I do play, it's either Path of Exile, Overwatch, trying out a new game, or joined together with another streamer, and playing whatever they want to play (Golf With Your Friends, Earthfall, Towers Unite, etc).

Please let me know what I need to do in order to join.

Thanks.

**Comment by csharpfritz** [comment]
Invite extended!  I will DM you on Twitch with an invite to the team Discord
