### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by themessycoder** [livecoders/Home#60]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/themessycoder

**What languages / frameworks / tools do you program in while streaming on Twitch?**
C# and using Unity3D mainly. However now moving to cover Unreal & Lumberyard also. Trying to get back in to C++

**Why do you write code on stream?**
To teach people how to make games and to have fun trying to make games myself. I mainly work with other developers, interviewing new guests each Saturday. Fridays I am either teaching, dev vlogging or playing games. 

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I don't really have a favourite moment, but my favourite moments are when things don't go to plan and especially when they go incredibly wrong! well as long as we get it fixed in the end :)

**Comment by csharpfritz** [comment]
Look for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.
