### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by denchp** [livecoders/Home#61]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/coachdench

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Primarily ReactJS, Firebase, in VSCode

**Why do you write code on stream?**
It keeps me motivated to move forward with my project.  Plus I enjoy interacting with other developers.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
briefly describe
This happened a while back when was discussing my 'L-Desk'; where I have to have a piece of green paper (which has since been upgraded to a green table cloth) covering the corner of the desk that appears in frame.
https://www.twitch.tv/coachdench/clip/CooperativeRacyLocustFutureMan

**Comment by LuckyNoS7evin** [comment]
Live Coder Intern - Nurturing Program - Acceptance

With The Live Coders growing rapidly the team introduced a minimum viewership and other criteria. 

- Interactivity
- Inclusivity
- Community
- Teaching
- Learning

You are invited to become a Live Coders Intern, not a part of the full Twitch team (some of the benefits are excluded) you will be invited to The Live Coders Discord server where you can learn from the rest of the team. (restricted access not all channels)

Please contact me to get your access

- @TheS7evin -> Twitter
- LuckyNoS7evin#0001 -> Discord
- LuckyNoS7evin -> Twitch
