### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by jesseskinner** [livecoders/Home#62]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/jesseskinner

**What languages / frameworks / tools do you program in while streaming on Twitch?**
JavaScript, HTML and CSS, and a lot of Svelte lately.

**Why do you write code on stream?**
I love teaching, and I work from home so it's really great to have people watching, making suggestions and asking questions as I do freelance work on stream.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
One of my favourite moments on stream was trying to learn machine learning for the first time and struggling through a basic example when a huge csharpfritz raid came in. I was in way over my head but it was exciting and fun to have the support of chat.

**Comment by mtheoryx** [comment]
@csharpfritz This is long overdue, please prioritize in processing.

![bitmoji](https://render.bitstrips.com/v2/cpanel/fe4a1c10-cce9-4b4a-a43c-6e707afcc5d1-c3b45c6e-2943-4fd5-ab6e-fe23bffcb90b-v1.png?transparent=1&palette=1&width=246)

**Comment by csharpfritz** [comment]
Look for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.
