### ISSUE TITLE
Application for Membership - Beachcasts

### ISSUE THREAD

**Issue by adamculp** [livecoders/Home#63]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://www.twitch.tv/beachcasts

**What languages / frameworks / tools do you program in while streaming on Twitch?**
PHP (broad framework portfolio), Javascript, Python, and other web-based technology.

**Why do you write code on stream?**
I love helping others, and enjoy streaming to share any knowledge I may have.

**What is your favorite moment from coding on stream?
Pretty much any moment where folks listening in share in the process. Example: [Success with help from viewers! Thanks Beau!](https://clips.twitch.tv/SpunkyBigWoodcockOneHand)

**Comment by adamculp** [comment]
WooHoo, made Twitch Affiliate today! Still growing, but really having fun!

**Comment by csharpfritz** [comment]
Congratulations on making affiliate!  Keep up the good work.

We'd like to see a few more viewers before adding you to the team.  I will check back at the end of December

**Comment by adamculp** [comment]
Thanks. Traveling last week to Japan and this week to Brasil to speak at conferences. However, will resume my normal schedule next week. ;-)

**Comment by adamculp** [comment]
Hi. Thought I'd follow up. Been a great couple of months. Thanks.

**Comment by csharpfritz** [comment]
Great consistency and a growing channel.  Look for an invite to the team, and once joined I will whisper you a link to the team Discord

**Comment by adamculp** [comment]
Thank you. Look forward to being part of the community.
