### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by Dkamps18** [livecoders/Home#64]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/DannyKampsGamez

**What languages / frameworks / tools do you program in while streaming on Twitch?**
PHP a little bit of JavaScript and sometimes Java

**Why do you write code on stream?**
I like to share my passion with other people and next to sharing my passion i just feel like something sticks more to people if you can give examples if they ask a question. And I've always streamed a lot of mixed content both Gaming and Coding and i saw a viewer from the gaming side join in during a coding stream and he learned the (sort of) basics of  PHP by watching my streams and that back then gave me more drive to do more Coding Streams. 

**What is your favorite moment from coding on stream?  Share a clip if one is available**
The moment when someone that learned coding by watching my stream found the error i was looking for earlier than i did and even came with the correct resolution to fix the error.

**Note**
At the moment there is really a lack of streams going on on my channel for some private reasons which i'll happily share with you in dm's on twitter or discord i just don't want to talk about it publicly.

**Comment by csharpfritz** [comment]
Live Coders team members write code on stream and discuss technology with their viewers.  In reviewing your channel's recent videos, There does not appear to be any content where you are writing code.

**Comment by Dkamps18** [comment]
The only available vods on my channel are coding streams i guess that twitch placed one of the collections/highlights I've made for series i had on my channel and that you looked over the actual recent broadcast.

**Comment by csharpfritz** [comment]
Welcome to the Live Coders!  Look for a Twitch team invite in your email.  Click through to accept that invite and we'll get you on our team mailing list and Discord
