### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by nathanhenniges** [livecoders/Home#65]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/mrdemonwolf

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Javascript,HTML,CSS, and NodeJS.  Mostly back-end frameworks like Express and MongoDB.  For front-end so far have used EJS and VueJS

**Why do you write code on stream?**
Programming is what started my passion.  Started with a Bootcamp and it jump-started me into the back-end of Javascript.  Most streams are either personal projects or open source ones.  Plus bits of my work projects for [scopeweb](https://www.scopeweb.nl)

**What is your favorite moment from coding on stream?  Share a clip if one is available**
There are many favorite moments.  But the most favorite would be the viewers who have helped me with my coding challenges on projects in the past.

**Comment by csharpfritz** [comment]
Look for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.
