### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by jeffblankenburg** [livecoders/Home#66]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/jeffblankenburg

**What languages / frameworks / tools do you program in while streaming on Twitch?**
I primarily focus on node.js development for Alexa skills, but I've ventured into React, AirTable, and several AWS services.

**Why do you write code on stream?**
I write code that helps me tell stories in my day job.  But the process of writing that code is incredibly educational for viewers.  If I'm going to write code, why wouldn't I do it in public?  Aside from showing them *how* to do something, they also get to see someone with 20+ years of software experience as fallible.  I make mistakes.  I have to look up simple syntax sometimes.  I own every one of those mistakes, and demonstrate how to recover, how to simplify, and how to move forward.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I no longer have this clip, but there was a moment where a viewer asked me how something would work.  I decided to just give it a try, on stream, explaining what I expected the behavior to be.  (It was a question about how Alexa would interpret and route requests related to characters, planets, vehicles, and droids from Star Wars.) After building a quick prototype, I realized that my assumptions and interpretation were actually incorrect, and if I followed their advice, I'd have a much stronger, more intuitive application.  It reminded me that keeping an open mind in software is incredibly important, because the way you've always done something might not actually be the best way.

**Comment by csharpfritz** [comment]
It looks like you haven't been streaming regularly in the last month.

Holding for more activity

**Comment by jeffblankenburg** [comment]
Yeah, travel has really gotten in the way lately.  About to start a new app, though.  Will bump this thread when it begins.

**Comment by jeffblankenburg** [comment]
Bumping this for @csharpfritz.

**Comment by csharpfritz** [comment]
Look for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.
