### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by AshDevs** [livecoders/Home#67]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/AshDev

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Mainly Java as that is the language I'm learning at the moment. Will be looking into web based development as i would like to build my website on stream as well. (HTML, CSS, SQL, JavaScript)

**Why do you write code on stream?**
I write code on stream as that is how i for my affiliation on Twitch but I started building a community while i was programming. Had to take time off streaming but now I'm back and i plan on sticking to it. I do work fulltime so things could change.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I really enjoy interacting with my viewers and learning from them as well. Sadly i don't have any clips.

Please note that I'll be looking to upgrade my PC soon so the stream quality will get better.

**Comment by csharpfritz** [comment]
I don't see any recent broadcasts of your channel.  Holding for further review

**Comment by AshDevs** [comment]
Yeah really sorry about that, Im having trouble with my PC ever since i upgraded it and someone quit from work so now im working more hours and i also picked up another job for x-mas time. I don't think I'll be back any time soon sadly but maybe next year.

**Comment by csharpfritz** [comment]
Declining for now due to lack of tech content.  You are welcome to re-apply in the future
