### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by Flavius-The-Person** [livecoders/Home#68]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/FlavCreations

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Java mostly. Android studio is sometimes used.

**Why do you write code on stream?**
The idea of interactivity and sharing with a community. Plus I'm making a game that is stream integrated like Marbles so I need to also be able to test it.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Probably when Genie showed up and I got to show him some of the sound bot stuff I was making. I'm fairly new to the scene and don't have a large viewership yet but I'm hoping to find my little pocket of space somewhere within the streaming universe.

**Comment by Flavius-The-Person** [comment]
I made a little revamp on my github name, I hope that is alright. I apologize if not. My reason for doing it was because I made an organization with the name FlavCreations in case I bring more people into that particular realm. Whether it was a good or bad idea, I don't know. I'm fairly new to github. I just wanted my business stuff to be a little separate from my other stuff.

**Comment by csharpfritz** [comment]
Look for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.
