### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by RobertGrubb** [livecoders/Home#69]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/iratetv

**What languages / frameworks / tools do you program in while streaming on Twitch?**
PHP, MySQL, JavaScript, JQuery, ReactJS, VueJS, HTML, CSS, CSS3. My IDE I usually use switches between Atom and VSCode depending on whether I'm working on backend or frontend. 

**Why do you write code on stream?**
I write code on stream to not only entertain viewers, but also to help viewers learn more about programming. I, personally, have always learned more when I'm watching someone deep dive into a project, so I want to help others accomplish the same thing. I also enjoy having people to talk to while I'm working on a project, and more pairs of eyes when I get into a weird situation (Syntax errors, a problem that requires a thoughtful solution, etc). 

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Unfortunately, I do not have a clip available. But it was when I made an application called TwitchShare (No longer live), but it would rotate through live streams based on a specific algorithm. We were able to deploy it to mobile using React Native, as well as on browser. And the whole stream was able to witness that process. 

**Extra Comments**
I just wanted to state, that I may not always stream consistently, but one thing that I do enjoy doing is going around streams that are programming related, and helping out when I can. Answering questions in the chat, possibly pointing out a solution that the streamer may not see at the time. So I would definitely be willing to do that for those who are daily active streamers here in this community.

Thanks for taking a look!
- Matt Grubb
matt@grubb.com

**Comment by seekaplayer** [comment]
I can vogue for Robert. He is the reason I'm a Web Designer/Developer. He taught me the basics of coding and we've been friends for 10+ years.

**Comment by RobertGrubb** [comment]
Just an update on this, you'll see my stream videos popping up after tomorrow. For some reason my videos were set to not save, and for that I apologize.

**Comment by csharpfritz** [comment]
I don't see any videos available on your channel.  Holding for future review

**Comment by LuckyNoS7evin** [comment]
Unfortunately, doesn't stream enough, seems like only one stream in last 90 days
