### ISSUE TITLE
Like to be added to team

### ISSUE THREAD

**Issue by sorskoot** [livecoders/Home#7]
Hi.
I stream JavaScript development in various ways. I am working on a Twitch bot and layouts running on node.js, a progressive web app using Azure functions and web bluetooth, and a WebXR game. I recently got affiliated and would love to join the team. 

Thanks!

Sorskoot
Https://twitch.tv/Sorskoot

**Comment by csharpfritz** [comment]
Invite extended!  I will whisper you a link to the team Discord
