### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by alexmeji** [livecoders/Home#70]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/alexmejidev

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Javascript, Java, Node.js, Cloud Computing, React. Visual Code, Eclipse and Terminal.

**Why do you write code on stream?**
I like to teach others, and to show them how to improve their skills and apply these skills in their current jobs. I like to interact with people and help them improve professionally.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
My favorite moment is when the viewers are impressed with something the don't know, or when i show a better way to implement some functions.

**Comment by csharpfritz** [comment]
Holding for further growth on your channel... it looks lie you JUST made Affiliate, and we'd like to see a little more development before adding a new member

**Comment by alexmeji** [comment]
Yeah!! @csharpfritz i have a little trip, this is te reason im not doing live coding, this week i start again with the live coding.

**Comment by LuckyNoS7evin** [comment]
Can re-apply in the future, please do, got to get that science and tech content going!
