### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by oscarmlage** [livecoders/Home#71]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/oscarmlage

**What languages / frameworks / tools do you program in while streaming on Twitch?**
PHP, Laravel, Python, Django, Flask, Javascript, VueJS, React, Vim + Tmux

**Why do you write code on stream?**
Because I like the iteration with the viewers, when they ask how to solve this or that and, even  better, when they offer some unexpected solutions that are perfectly fine.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I love to use vim + tmux for everything, so any vim trick, vimrc config or tmux shortcut is what I enjoy most.

Thank you so much for take a look.

**Comment by csharpfritz** [comment]
Live Coders are Affiliate or Partner streamers on Twitch.  Please re-apply when you have reached that status
