### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by glaucia86** [livecoders/Home#72]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://www.twitch.tv/glaucia_lemos86

**What languages / frameworks / tools do you program in while streaming on Twitch?**
JavaScript, Node.js, Angular, Vue.js, React, Azure, A.I, ChatBots

**Why do you write code on stream?**
Because I really enjoy to make this connection every developer whatever they're. And I love to teach and mainly is a good opportunity to share and learn even more about new things.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
It was late night and @MarcoBrunoBR was making some raid and then he sent to me some viewers to my live coding and said: "Bro! There's a girl programming here! I neve seen this before." 
It was insane and very motivated for me! :)

**Comment by csharpfritz** [comment]
Live Coders are Twitch Affiliate or Partner streamers.  Holding until you reach affiliate status

**Comment by glaucia86** [comment]
Thanks!
