### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by linuxgurugamer** [livecoders/Home#73]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/linuxgurugamer

**What languages / frameworks / tools do you program in while streaming on Twitch?**
C#, Visual Studio
I also use Github, and a local jenkins server

**Why do you write code on stream?**
For fun, to get feedback,and to teach players about coding

**What is your favorite moment from coding on stream?  Share a clip if one is available**

I got a 1000 person raid one time from EJ_SA.  Kind of floored me.

Other comments:
I stream two days a week, Sunday night and Monday night.  Sunday is when I play Kerbal Space Program, Monday is when I work on mods for it

**Comment by csharpfritz** [comment]
Look for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.
