### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by Mochlate** [livecoders/Home#74]
**What is the URL for your Twitch channel?**
https://www.twitch.tv/itlatte

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Javascript!!!!
Node.js + React mainly

**Why do you write code on stream?**
I write random javascript web-apps mainly

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Was able to get the training to work for the machine learning, clip unavailable as I just enabled saving broadcasts yesterday.

**Comment by Mochlate** [comment]
Changed username to https://m.twitch.tv/latteandmia

**Comment by csharpfritz** [comment]
Look for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.
