### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by alexanderrost** [livecoders/Home#77]
What is the URL for your Twitch channel?
https://www.twitch.tv/fakezer0

What languages / frameworks / tools do you program in while streaming on Twitch?
Java (School)
C# (If I feel like doing some unity)
Python (For small scripts and conviniance programs!)
(In the future I'll also learn C, C++ , assembly & other languages recuired for a Computer Science degree)

Why do you write code on stream?
Mainly work on assignments from University alongside other projects that catch my eye. The plan is the let the followers join as if we're taking courses together and hopefully it makes the experience more enjoyable.

What is your favorite moment from coding on stream? Share a clip if one is available
Having my real first interactions with other people that code, seeing how they think and being able to brainstorm with people from all over the world is a magical feeling.

**Comment by csharpfritz** [comment]
There aren't any past broadcasts available on your channel where you are writing code.  Please re-apply when there are some live coding sample videos available
