### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by mbcrump** [livecoders/Home#78]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/mbcrump

**What languages / frameworks / tools do you program in while streaming on Twitch?**
C#, Azure, Visual Studio Code, Visual Studio, Xcode + Swift

**Why do you write code on stream?**
I like to interact and learn with the community and share what knowledge that I currently have. I am a big believer in "we are in this together" and that we should help one another regardless of current skill level. I also want to teach my daughter programming so that others could be inspired and join the technical community.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
hips or https? https://www.twitch.tv/mbcrump/clip/SleepyMildArugulaStinkyCheese 

Thanks for considering me!

**Comment by csharpfritz** [comment]
Look for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.
