### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by LuckyNoS7evin** [livecoders/Home#79]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/SlevinthHeaven

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Mainly dotnet stack in terms of creating and developing software, so C#, Visual Studio, Azure however over the last few years I have started to include Node, Frontend JS Frameworks like Vue and React

**Why do you write code on stream?**
When I started writing code on stream I did it because I could, in other words I had a beast PC that allowed for streaming so why not. I joined several streaming communities however "didn't fit in" due to being the only one writing code.

Now I write code on stream as I like to, still because I can but over the time I have been doing it that has evolved into more teaching, mentoring and learning (by myself) which has lead to not only others improving but also me. 

This channel is a 2nd channel and is linked to the company I created with my wife. The reason we have this channel is due to creating software for Twitch the first project being https://featured.chat. The reason we would like the channel (including myself and Claire) to be on the team is hopefully to help push the team forward even further in the future. 

We intend to use the channel for Mrs S7evin (Claire) to learn to develop code along side me, we also intend to use it as the full time coding channel when we are allowed to stream client work, for example from January featured.chat will be in development full time for 6 months

**What is your favorite moment from coding on stream?  Share a clip if one is available**
https://www.twitch.tv/luckynos7evin/clip/FaintPrettiestDragonfruitJKanStyle
A complete success moment in my first year as a streamer, when I started in a damp basement.

**Comment by csharpfritz** [comment]
Approved - Done
