### ISSUE TITLE
[@ben_greenier] Application for Membership

### ISSUE THREAD

**Issue by bengreenier** [livecoders/Home#81]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**

https://twitch.tv/ben_greenier

**What languages / frameworks / tools do you program in while streaming on Twitch?**

+ C++
+ C#
+ JS/TS/CSS/HTML => Node/Electron/Browser (most content)
+ VS Code
+ https://github.com/bengreenier

**Why do you write code on stream?**

I spend a lot of time coding personal projects. One of the ways that I'm motivated to keep at something is through shared enthusiasm with others. I also really enjoy sharing knowledge and bouncing ideas off others - Building things together with other folks that are equally excited and knowledgeable is super fun. It turns out that's a lot of what live streaming is, so it ends up being a great time! Hope my viewers agree. 😅

**What is your favorite moment from coding on stream?  Share a clip if one is available**

Back when I was streaming from Boston (before the move to London) I was doing a segment with one of my colleagues at the time live building a webrtc signaling app, and @clarkio raided us - Had a ton of fun answering questions for the new viewers while coding (and then switching roles w/ my colleague and she answered q's while I coded). Wish I still had the VOD... 😿 

**Why the break?**

I made some pretty huge life changes over the last 5 months - getting things ready for these changes, and settling into a new country has been pretty time consuming. But i'm fairly settled now, excited to get back at it. @TylerLeonhardt encouraged me to apply for the team once I got back into things, which I guess is now. 😸

**Comment by csharpfritz** [comment]
Look for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.
