### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by MarcTowler** [livecoders/Home#82]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/itslittany

**What languages / frameworks / tools do you program in while streaming on Twitch?**
PHP mainly with a bit of NodeJS at times in terms of languages but for IDEs it is VS Code

**Why do you write code on stream?**
I have been hobbying at coding on and off for a few years but the past few months, I have been working on building a community RPG system which has been helping me work on building my knowlsge and skills.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Seeing the community using the RPG project whilst building on it and getting them involved.

**Comment by csharpfritz** [comment]
Look for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.
