### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by MaryJoStaebler** [livecoders/Home#83]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/maryjostaebler

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Any web dev/design... HTML, JS, CSS, SASS, PHP, C#, ReactJS, AngularJS, Gulp, NPM, VS Code, SQL things, other JS things, UI things

**Why do you write code on stream?**
I enjoy working with others to learn, think of new ideas, and chat on tech life.  More brains the better.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Favorite moment i had was when a person in chat comes up with an idea or solution for a project I'm streaming and it makes the project better.  I do enjoy helping newbies figure out what to focus on when learning something new too.

**Comment by mtheoryx** [comment]
Due to unanimous approval, I'm gonna close this as an absolute win for our team, and welcome aboard @MaryJoStaebler !!!
