### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by TutorExilius** [livecoders/Home#84]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/TutorExilius

**What languages / frameworks / tools do you program in while streaming on Twitch?**
---Languages---
Mainly: C++, Python
New: C#
Sometimes: Java, New Languages
---Frameworks---
Qt-Framework
C++ STL
.NET
---Tools/IDE---
Visual Studio
Visual Studio Code
Qt Creator
MS PAINT :D
Eclipse/JetBrains IDEA (for Java/Java EE)
Notepad++
etc...
 

**Why do you write code on stream?**
- Teaching/Supporting people in programming
(on every Sunday 18pm (german time) C++ Live Support for C++ Beginner)
- creating some interesting apps

**What is your favorite moment from coding on stream?  Share a clip if one is available**
To realise how stupid I was, when someone from my community is telling me a simple way to solve my problem ^^"

**Comment by csharpfritz** [comment]
Look for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.

**Comment by TutorExilius** [comment]
Hello :)
Thanks you for inviting me! :)
