### ISSUE TITLE
Application for Membership: ChaelCodes

### ISSUE THREAD

**Issue by ChaelCodes** [livecoders/Home#85]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/ChaelCodes

**What languages / frameworks / tools do you program in while streaming on Twitch?**
I'm building a React/Rails app. 
Repo here: 
https://github.com/ChaelCodes/HuntersKeepers
It's got a lovely continuous integration setup that I built off stream.

I also play programming games. That isn't part of this team's jam, but just so you know what you're looking at when reviewing my past broadcasts.

**Why do you write code on stream?**
I want to share the joy and frustrations of programming with my viewers. I include the googling, the gnarly specs, and fighting with the syntax. I'm a senior developer, and I've seen impostor syndrome so many times. I want people to see what it's like to really code, and I want to share some laughs and techniques while I do it. I really enjoy sharing that space with my viewers and communicating with them.

**What is your favorite moment from coding on stream?  Share a clip if one is available**

Spinning up a PR in 15 minutes to exclude my `db/schema.rb` from rubocop. Lol, at the beginning of the video, I figured it was a later problem, but I was waiting on the build from my main branch. :sparkles: Surprise PR! :sparkles: 
https://m.twitch.tv/videos/512781045

I also really enjoyed working through this refactor on stream:
https://m.twitch.tv/videos/516841703
https://m.twitch.tv/videos/516841702

**Comment by csharpfritz** [comment]
Look for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.

**Comment by ChaelCodes** [comment]
Thank you for adding me! Happy to join the team.
