### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by larryny** [livecoders/Home#87]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://www.twitch.tv/larryny

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Python3, C/C++, emacs

**Why do you write code on stream?**
Learning python and algorithms.  Competitive programming, going over leetcode problems, explain my thought process while solving problems, talking about interviewing in the tech industry.  I 

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I've been doing this stream for about half a year, long enough that one of my regular viewers mentioned getting a job at a tech company after the stream!  Not to take too much credit for it, but it still feels great to contribute!

If you have any questions about this process, please contact [_KittyKerns on Twitter](https://twitter.com/_kittykerns)

**Comment by csharpfritz** [comment]
Nice interactions with your viewership and a growing stream that talks tech.  Welcome to the Live Coders!
