### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by rancoud** [livecoders/Home#88]
**What is the URL for your Twitch channel?**
https://twitch.tv/megadamage

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Javascript (ES5), HTML, CSS, PHP, go, Unreal Engine, Twitch game...

**Why do you write code on stream?**
For multiple reasons:  
* keep focus (avoid procrastination)
* share knowledge
* discover new languages/paradigms
* be challenged by viewers

It's be a long time I do that.
I was on Twitch then Livecoding.tv and finally I came back on Twitch.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
My favorite moment is when viewers ask me why I do stuff in a certain way and I explain why.
And sometimes viewers correct me :)

**Comment by csharpfritz** [comment]
Looks like a good stream.  Welcome to the Live Coders!   You'll have an email from Twitch with instructions to join the team.  Once joined, I'll Twitch whisper a link to the team Discord.
