### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by anahleticiaa** [livecoders/Home#89]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/ana_geek

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Unreal Engine, Maya, Photoshop

**Why do you write code on stream?**
I'm developing a game

**What is your favorite moment from coding on stream?  Share a clip if one is available**
For me the best moment is when i'm thinking and sharing with viewers the best logic to solve one problem

If you have any questions about this process, please contact [_KittyKerns on Twitter](https://twitter.com/_kittykerns)

**Comment by csharpfritz** [comment]
Look for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.

**Comment by anahleticiaa** [comment]
I didn't receive any invite from twitch yet

**Comment by csharpfritz** [comment]
Re-sent the invite.  The invite comes from Twitch, and would be sent to
your Twitch profile connected email address.


Jeff

**Comment by anahleticiaa** [comment]
It's done, thank you
