### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by illuminatedspace** [livecoders/Home#9]
Hello, my name is Liz Phillips. I'm a full stack software engineer primarily working in web development.
Twitch: [twitch.tv/illuminatedspace](https://www.twitch.tv/illuminatedspace)
Twitter: [@lizcodes](https://www.twitter.com/lizcodes)

## Qualifications
1. Twitch Affiliate or Partner status
I have Twitch Affiliate status.

2. During broadcasts, politely answer questions from viewers
Answering questions from viewers is my favorite thing to do on stream. I regularly remind viewers that they can ask questions and I try to answer every question my viewers have, or at least point them in the right direction.

3. Promote a positive, inclusive, and welcoming chat room
My Code of Conduct enforces a welcoming community for coders of all levels.
I try to use accessible color combinations and recently started using an overlay that allows live closed captions. My stream is family friendly as well. (No bad words, no vulgar content)

My Code of Conduct also prohibits:
* gatekeeping language
* discriminatory language
* objectifying comments
* tool/language bashing

4. Are a person, not a brand or company account
Definitely a person, at least last time I checked.

5. Regularly write code or make hardware with technology. Other content is cool.
My regular stream is every Saturday from 7:45pm EST till at least 9:45pm EST.
During this stream I have been live coding on a portfolio website using React and Gatsby.
I've done other streams like, one for beginner algorithms starting with Hash Tables, and sometimes games.

**Comment by illuminatedspace** [comment]
Oops. Accidentally hit Open early.

**Comment by csharpfritz** [comment]
Invite extended!  Check you Twitter DM for an invite to the team private Discord.
