### ISSUE TITLE
Proxy Application for Membership - SausageCam

### ISSUE THREAD

**Issue by mtheoryx** [livecoders/Home#90]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://www.twitch.tv/sausagecam

**What languages / frameworks / tools do you program in while streaming on Twitch?**
- Unity
- Sarcasm
- Inside Jokes
- Community fun

**Why do you write code on stream?**
It's a desperate 2020 goal, really.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
When the interaction of chat causes me to actually keep my word on promises.

If you have any questions about this process, please contact [_KittyKerns on Twitter](https://twitter.com/_kittykerns)

**Comment by mtheoryx** [comment]
Into it.

![bitmoji](https://render.bitstrips.com/v2/cpanel/4d8b3130-c973-4622-9695-60cf577fec44-c3b45c6e-2943-4fd5-ab6e-fe23bffcb90b-v1.png?transparent=1&palette=1&width=246)

**Comment by mtheoryx** [comment]
Update:

Week of Jan 10, son has done them streams:

- [x] [Modeling weapons and body parts](https://www.twitch.tv/videos/533442396?filter=archives&sort=time)
- [x] [Blender and Rigging](https://www.twitch.tv/videos/532494944?filter=archives&sort=time)
- [x] [Weapons rigging](https://www.twitch.tv/videos/530044044?filter=archives&sort=time)

**Comment by csharpfritz** [comment]
Agreed - SausageCam has been doing some great streams and has been interacting with his audience in a great way.  His enthusiasm as part of the SushiCodes stream is contagious, and we're happy to see it on his own channel.

Look for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.
