### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by heybourn** [livecoders/Home#91]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/heybourn

**What languages / frameworks / tools do you program in while streaming on Twitch?**
JavaScript, HTML and CSS. I also love using Vue and other static site generators.

**Why do you write code on stream?**
I love teaching, learning and interacting with others. Working from home prevents me from doing so, however streaming opens up these opportunities for me.

**What is your favorite moment from coding on stream? Share a clip if one is available**
I recently held a charity stream to raise money for WIRES (an organisation helping wildlife affected by the AUS bushfires). One viewer popped into the stream and generously donated over $100NZD - pushing my original $50 goal over. 

https://clips.twitch.tv/SneakyThoughtfulClintMoreCowbell

**Comment by csharpfritz** [comment]
Look for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.
