### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by sadmoody** [livecoders/Home#92]
**What is the URL for your Twitch channel?**
https://twitch.tv/sadmoody

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Currently using Unity (C#) and C++ for my current project, but I quite like and am most comfortable with Python! I'll use whatever I need to get the job done!

**Why do you write code on stream?**
To solve interesting problems, show how things work. My mission, really, is to make technically-dense knowledge accessible to non-technical people. I'll do this by creating fully produced videos on Youtube, but Twitch is where I'll put together the simulators/scripts and supplemental material that I need. It's nice to have people along the way seeing how things are done.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Someone came in my stream not knowing how needs-based AI worked and linked a paper. We worked through it together and he ended up understanding it after I explained what all the math symbols meant and implemented in a quick Python script on-stream. Fully derailed the project I was working on at the time, but it's really nice to be able to explain something to someone who thought it was too hard!

**Comment by csharpfritz** [comment]
The team really likes your contributions, and agrees that we should invite you to join the team.

Look for an invite from Twitch with a link to join the team.  Once you have joined, I will whisper you on Twitch with a link to the team Discord.
