### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by xdesro** [livecoders/Home#94]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/xdesro
http://xdesro.live

**What languages / frameworks / tools do you program in while streaming on Twitch?**
HTML, CSS, JS, Vue, WebGL.

**Why do you write code on stream?**
I love exploring weird idiosyncrasies of style code, bending the rules of CSS, and struggling through learning new tech. I think there's a ton of value, esp. to newer developers, in seeing that Literally Everyone deals with Googling their way out of stuff, etc. Additionally, I'm really excited about showing how powerful CSS and SVG are on their own.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I don't know if I have any clipped instances of this, but my favorite moments are any time someone in the chat backseats me through a bug — "you missed X on line 35" is such a perfect example of why the Twitch format is perfect for social coding. You get to pair program with dozens of other people!

If you have any questions about this process, please contact [_KittyKerns on Twitter](https://twitter.com/_kittykerns)

Thanks in advance for your consideration! I'm really excited to be a part of this.

**Comment by csharpfritz** [comment]
I don't see any streaming over the last two months on your channel.

Declining.  You're welcome to re-apply when your stream activity picks up again
