### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by polerin** [livecoders/Home#95]
**What is the URL for your Twitch channel?**
https://twitch.tv/polerin  -- not family friendly.  Not explicitly unfriendly, I just have a cussing habit.

**What languages / frameworks / tools do you program in while streaming on Twitch?**
Unity3d (C#) and probably some PHP/JS when I get to the point I'm doing a web backend.

**Why do you write code on stream?**
I love the fact that coding in front of people keeps me focused and moving, keeps me away from rabbit holing too much.  It also lets me give back..  I'm a professional webdev with ~15 years experience doing production code.  A lot of what I learned was through by being mentored and the writing people did on the net.  I'm not a blogger, but I'm comfortable on a microphone and I come from a teaching family.  I love teaching, and this is a useful way to scratch that itch.  I also like doing code review or one on one instruction on stream, but fewer people take me up on that.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
Hm.  Working through a demo of dependency injection in unity with someone who hadn't seen it before, and showing him how you could switch from singletons to a static facade, and then from a static facade to an injected instance pretty easily.  When it clicked he was like "That's So fucking cool [...] it's like one shot sphaghetti killer."  I ended up putting the whole walkthrough and discussion on youtube.  A bit long but that specific moment is right here: https://youtu.be/Efs6k_iqxdY?t=4569

**Comment by csharpfritz** [comment]
Lots of great activity here, and endorsements from other team members.

Welcome to the Live Coders!  You'll receive an email with an invite from Twitch.  Once you join the team, I'll Twitch whisper you a link to join the team Discord
