### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by davidbegin** [livecoders/Home#97]
**What is the URL for your Twitch channel?**

https://twitch.tv/beginbot

**What languages / frameworks / tools do you program in while streaming on Twitch?**

Python is the primary language currently. Although we often talk about many languages,
and compare different approaches and communities. I also often do "Devops" type work, which can be terraform, cloudformation, or bash. Devops work is primarily AWS Serverless architecture explorations, which is what I do for work. So I like to explore new tools and techniques on stream.

**Why do you write code on stream?**

I like to explaining things to others, and do it while I working to myself anyway! I also throughly enjoy pondering/discussing the nuances and trade offs in the imperfect world of technology with viewers.
Finally I came into coding later in life, and want to share my techniques for navigating the industry and having fun, without going through tradition paths, while also identifying gaps in my knowledge like math and computer science, that I other missed from said non-traditional path into programming.

**What is your favorite moment from coding on stream?  Share a clip if one is available**

All the times someone has take some advice and said it helped has been amazing. I also really like when I realize I don't know a fundamental idea in computer science/programming/python etc. and the chat both commiserates and helps, with the appropriate amount of roasting. Or we end up in some weird rabbit hole, like where did the term Grok come from and what does it really mean: https://www.twitch.tv/videos/540373779?filter=highlights&sort=time

**Comment by csharpfritz** [comment]
Great looking stream

Welcome to the Live Coders!  You'll receive an email with an invite from Twitch.  Once you join the team, I'll Twitch whisper you a link to join the team Discord
