### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by jlcarvalho** [livecoders/Home#98]
**What is the URL for your Twitch channel?**
https://twitch.tv/jeanss

**What languages / frameworks / tools do you program in while streaming on Twitch?**
React, Angular, Vue, Ionic, JavaScript, CSS, HTML and frontend stuff in general.

**Why do you write code on stream?**
The interaction with chat looks like a pair programming for me and it's a great way to learn and teach stuff.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I really like to discuss how to do something or when someone comes up with a new idea for a problem that I'm stuck.

**Comment by csharpfritz** [comment]
This channel does not exist... closing

**Comment by jlcarvalho** [comment]
@csharpfritz I change the channel name, sorry.

The url is https://twitch.tv/JeanLucasDev now.
