### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by nopogo** [livecoders/Home#99]
Please make sure that 'Store Past Broadcasts' is enabled on your channel so that we can review examples of your coding stream.

**What is the URL for your Twitch channel?**
https://twitch.tv/nopogo_tv

**What languages / frameworks / tools do you program in while streaming on Twitch?**
I am the coding side of a stream duo that is making a video game entirely on stream. I use vscode to program C# within the unity engine.

My other main languages are python and ruby (django, ruby on rails) but I believe that never came up on stream.

**Why do you write code on stream?**
the whole reason I started streaming was connecting to the ludumdare community during the game jam. I love the sharing of knowledge, both as a host or as a viewer. I try to encourage any and all viewer questions regarding code. This includes getting shouted at by chat if I am being a dumb. I am in this thing to learn and teach in equal portions.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
the name of our future gamestudio was born in this moment:
https://clips.twitch.tv/MoralGentleShrewOMGScoots

**Comment by csharpfritz** [comment]
Nice amount of activity and neat Unity work. 

Welcome to the Live Coders!  You'll receive an email with an invite from Twitch.  Once you join the team, I'll Twitch whisper you a link to join the team Discord
